### PR TITLE
[java] NPE in InvalidSlf4jMessageFormatRule if a logger call with a variable as parameter is not inside a method or constructor

### PR DESCRIPTION
**Pull request by kris-scheibe**
When checking if the slf4j message is a local variable, InvalidSlf4jMessageFormatRule#expectedArguments expects the logger call to be inside a method or constructor. This fails if the logger call is in an initializer block or a lambda call at class level.

This PR also checks initializer and lambda blocks and adds a null-check if the logger call is somewhere else.

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">This changeset introduces 0 new violations and 0 new errors,<br />
removes 0 violations and 0 errors. <a href="http://chunk.io/pmd/157d44e9a4024234b243a8192f8415bb/diff/index.html">Full report</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by adangel** [comment]
Awesome, thanks!

**Comment by kris-scheibe** [comment]
You're welcome!
@adangel Would it help you guys if I also create an issue for the bug/enhancement?
We've recently started using PMD enforce our coding-standards and fix up a lot of our old code and while I don't hope to find more bugs, I've written/extended a few rules that might be useful to the public.

**Comment by adangel** [comment]
@kris-scheibe For bugs, yes, a issue will be good, since we can then add this easily to the release notes. For an enhancement, it depends: If it changes/enhances a rule, then, yes, we'd like to have a issue, too. For other general enhancements, the pull request is enough.

**Pull request merged**
