### PR TITLE
[java] Updated Doc on AvoidThrowingNullPointerException to close Issue #832

### PR DESCRIPTION
**Pull request by refactormyself**
I Updated Doc on AvoidThrowingNullPointerException to close Issue #832

### CODE REVIEW

**Comment by refactormyself** [comment]
@adangel :+1: Hope it is alright now

**Comment by refactormyself** [comment]
@adangel I suggest an Issue be created to extend [Writing Document](https://pmd.github.io/pmd-6.1.0/pmd_devdocs_writing_documentation.html) to include the second case of xml file. I will like to work on it.

**Comment by oowekyala** [comment]
@refactormyself You can keep the documentation you originally wrote (including the markdown) if you wrap it inside a `CDATA` section in the xml, eg
 ```xml
<rule ...>
  <description>
  <![CDATA[
    Full description, can contain markup
  ]]>
  </description>
  ...
</rule>
```

CDATA sections preserve all formatting inside the delimiters, and are not interpreted as xml. You can see such sections in the rule's `<example>` nodes for example

Also, in github flavoured markdown, you can use syntax highlighting for your java examples by fencing the code inside
<pre>
```java
  ...
``` 
</pre>

**Comment by oowekyala** [comment]
@refactormyself You can put all the description inside a single CDATA tag, it will be cleaner

**Comment by oowekyala** [comment]
Nice! I'll merge that asap, thanks for your contribution :)

**Comment by oowekyala** [comment]
@refactormyself Merged! I took the liberty to remove the first code example you added, since it would actually have been flagged by the rule. The paragraph about `requireNonNull` is preserved. I'll assign you to a ticket about the update to "Writing Documentation"

**Pull request merged**
