### PR TITLE
Removed unnecessary comment in AbstractMultiPackagedProperty

### PR DESCRIPTION
**Pull request by plan3d**
Found unnecessary comment while fixing checkstyle issue 618

### CODE REVIEW

**Comment by jsotuyod** [comment]
@plan3d thanks and welcome.

However, this comment is not really "unnecessary", as it honors the [`CommentDefaultAccessModifier`](https://pmd.github.io/pmd-6.32.0/pmd_rules_java_codestyle.html#commentdefaultaccessmodifier) rule.

**Comment by plan3d** [comment]
I see. Would you agree with something like

```
@Deprecated
/* default */
abstract class ...
```
instead of 
```
@Deprecated
/* default */ abstract class ...
```
? A prefixed comment in the same line as the class/method/field definition looks strange to me...

**Comment by jsotuyod** [comment]
@plan3d I fear that won't work with the current implementation for that rule.

That being said, this is a codestyle rule, so it's inherently opinionated.

**Comment by plan3d** [comment]
Yes, I see. I'll close this pull request and adjust my checkstyle code changes to accept class definitions starting with a comment :-)

**Pull request closed without merging**
