### PR TITLE
[doc] Create a logo page for the new logo

### LINKED ISSUE #2497: PMD 7 Logo page
Part of #1931 

Create a page, where the official PMD logo can be downloaded. Decide and describe the license (probably CC BY).

This is the go-to-page in our documentation from where to get the logo in order to integrate it into other products

The Logo needs to be provided ready to use in different formats / sizes as a logo and icon.

### PR DESCRIPTION
**Pull request by adangel**
## Describe the PR

Adds the logo in some formats. Maybe we need to extend the sizes later on, but for now, that should be good.

I'm not sure about the Icon - we might need to come up with some square format, that better fits as icon.

Preview of the page:

grafik

Or here: https://chunk.pmd-code.org/pmd/2cc98cd3-65d6-4a5a-8c0b-1391ee30afd2/pmd_projectdocs_logo.html

## Related issues

- Fixes #2497

## Ready?

- [ ] Added unit tests for fixed bug/feature
- [ ] Passing all unit tests
- [ ] Complete build `./mvnw clean verify` passes (checked automatically by travis)
- [ ] Added (in-code) documentation (if needed)

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">No java rules are changed!</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by oowekyala** [comment]
I'm not sure where to comment this, but will we remove the tagline from the logo in the end? At the end of #1663 I thought it was our consensus

**Comment by adangel** [comment]
I didn't remember this :smile: But you are right.
I just used the zip file attached to the comment - and the tagline was still present.... I'll update it tomorrow....

**Comment by oowekyala** [comment]
Ok thanks! Just for reference, pmd/pmd.github.io#8 needs to be updated as well

**Pull request merged**
