### PR TITLE
Improves JDK8 support for default methods and static methods in interfaces

### PR DESCRIPTION
**Pull request by bric3**
Current version of PMD fails on classes with default methods or static methods. JDK8 has updated semantics for `invokespecial` / `invokestatic` opcodes, upgrading to ASM 5 is not enough to support Java 8 opcodes like in commit 9b91690. In order to support these new semantics it is necessary to indicate to ASM to use the updated `ASM5` op code dictionary. Also this PR replaces the deprecated `visitMethodInsn` with the new version that takes an additional `boolean`

This PR also brings another maven module to allow to test PMD with JDK8 code, however for that one must run maven with the JDK 8.

Here's the stacktrace of the current failure

```
java.lang.IllegalArgumentException: INVOKESPECIAL/STATIC on interfaces require ASM 5
	at org.objectweb.asm.MethodVisitor.visitMethodInsn(Unknown Source) ~[asm-5.0.3.jar:5.0.3]
	at org.objectweb.asm.ClassReader.a(Unknown Source) ~[asm-5.0.3.jar:5.0.3]
	at org.objectweb.asm.ClassReader.b(Unknown Source) ~[asm-5.0.3.jar:5.0.3]
	at org.objectweb.asm.ClassReader.accept(Unknown Source) ~[asm-5.0.3.jar:5.0.3]
	at org.objectweb.asm.ClassReader.accept(Unknown Source) ~[asm-5.0.3.jar:5.0.3]
	at net.sourceforge.pmd.lang.java.typeresolution.PMDASMClassLoader.getImportedClasses(PMDASMClassLoader.java:77) ~[pmd-java-5.2.1.jar:na]
	at net.sourceforge.pmd.lang.java.typeresolution.ClassTypeResolver.populateClassName(ClassTypeResolver.java:728) ~[pmd-java-5.2.1.jar:na]
	at net.sourceforge.pmd.lang.java.typeresolution.ClassTypeResolver.visit(ClassTypeResolver.java:153) ~[pmd-java-5.2.1.jar:na]
	at net.sourceforge.pmd.lang.java.ast.ASTCompilationUnit.jjtAccept(ASTCompilationUnit.java:42) ~[pmd-java-5.2.1.jar:na]
	at net.sourceforge.pmd.lang.java.typeresolution.TypeResolutionFacade.initializeWith(TypeResolutionFacade.java:17) ~[pmd-java-5.2.1.jar:na]
	at net.sourceforge.pmd.lang.java.AbstractJavaHandler$5.start(AbstractJavaHandler.java:88) ~[pmd-java-5.2.1.jar:na]
	at net.sourceforge.pmd.SourceCodeProcessor.usesTypeResolution(SourceCodeProcessor.java:127) ~[pmd-core-5.2.1.jar:na]
	at net.sourceforge.pmd.SourceCodeProcessor.processSource(SourceCodeProcessor.java:142) ~[pmd-core-5.2.1.jar:na]
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:76) ~[pmd-core-5.2.1.jar:na]
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:43) ~[pmd-core-5.2.1.jar:na]
```

### CODE REVIEW

**Comment by adangel** [comment]
You're right - I didn't think about the bytecode compatibility :)

Thanks for you pull request - I'll have a closer look soon.

**Comment by bric3** [comment]
Hi @adangel,

I'm a github regular and project owner, so I'm open to comments, history rewrite etc...

In other news I don't know if you know this part, but on the JDK8 front I opened this issue too http://sourceforge.net/p/pmd/bugs/1317/, however I don't really have the _design clue _ to fix that one.

**Comment by bric3** [comment]
By the way on mockito, we migrated from google code to GH ; the plan was to migrate google code issues on GH but we let the PR open, and PR and issues share the same counter. Yet somehow we still decided it was more productive to work with GH issue than use the old tracker.

Plus GH really helps in this matter, compared to old _forges_.

**Comment by adangel** [comment]
Thanks!

**Comment by bric3** [comment]
Cool, thanks to you @adangel ;)

**Pull request merged**
