### PR TITLE
[java] Fix False-positive UnnecessaryFullyQualifiedName when nested and non-nest…

### LINKED ISSUE #4085: [java] UnnecessaryFullyQualifiedName false positive when nested and non-nested classes with the same name and in the same package are used together
One can find a project to reproduce this issue here: https://github.com/OlegAndreych/PMDNestedClassFQNTest.

```java
package some.pkg;

public class Test {
}
```

```java
package some.pkg;

public class OuterTest {
    public static class Test{
        private final some.pkg.Test test; // line 5 - false positive

        public Test(some.pkg.Test test){ // line 7 - false positive

            this.test = test;
        }
    }
}
```

PMD Reports the following violations:

```
[INFO] PMD Failure: some.pkg.OuterTest$Test:5 Rule:UnnecessaryFullyQualifiedName Priority:4 Unnecessary use of fully qualified name 'some.pkg.Test' due to existing same package import 'some.pkg.*'.
[INFO] PMD Failure: some.pkg.OuterTest$Test:7 Rule:UnnecessaryFullyQualifiedName Priority:4 Unnecessary use of fully qualified name 'some.pkg.Test' due to existing same package import 'some.pkg.*'.
```

Both are false positives - the fully qualified name is necessary, since the enclosing class has the same name (`Test`).

### PR DESCRIPTION
**Pull request by OlegAndreych**
…ed classes with the same name and in the same package are used together #4085

## Describe the PR

Additional search and exclusion of inner classes/interfaces with the same simple name as fully qualified class usage is added.

## Related issues

- Fixes #4085 

## Ready?

- [X] Added unit tests for fixed bug/feature
- [X] Passing all unit tests
- [X] Complete build `./mvnw clean verify` passes (checked automatically by github actions)
- [ ] Added (in-code) documentation (if needed)

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">Compared to master:<br />
This changeset changes 0 violations,<br />
introduces 0 new violations, 0 new errors and 0 new configuration errors,<br />
removes 50 violations, 2 errors and 6 configuration errors.<br />
<a href="https://chunk.io/pmd/07f9b7da4d404e328741fa9da9340a3d/diff1/index.html">Full report</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by adangel — CHANGES_REQUESTED** [review]
Thanks for the PR!

It seems your check "hasSameSimpleNameInScope" is too simple - we now get some false negatives, e.g. the following two unnecessary FQNs are not found anymore:

* https://github.com/checkstyle/checkstyle/blob/checkstyle-9.1/src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/classfanoutcomplexity/InputClassFanOutComplexityPackageName.java#L24
* https://github.com/checkstyle/checkstyle/tree/checkstyle-9.1/src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/classfanoutcomplexity/InputClassFanOutComplexityPackageName.java#L27

You can see the full regression report here: https://chunk.io/pmd/07f9b7da4d404e328741fa9da9340a3d/diff1/index.html

The removed violation all seem to have in common, that they don't have nested classes... only one main class - and this class is referenced via a FQN.

Can you please check these cases?

**Comment by OlegAndreych** [comment]
> Can you please check these cases?

Yes, sure.

**Comment by OlegAndreych** [comment]
Please help me to replicate regressions.

I've ran `pmdtester` locally and haven't got any difference between upstream master and my branch.  
The command I ran:
```sh
bin/pmdtester -b upstream/master -p master -r ~/devel/pmd
```

**Pull request closed without merging**
