### PR TITLE
[java,apex] Remove deprecated and unused rules

### LINKED ISSUE #1629: [java] UselessAssignment is not references by any ruleset
**Affects PMD Version:** ./.

**Rule:** UselessAssignment

**Description:**
https://github.com/pmd/pmd/blob/master/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/UselessAssignment.java is not available in any ruleset and has a comment
```
//FUTURE This is not referenced by any RuleSet?
```
which indicates that this has been forgotten. If it's no longer use it should be marked deprecated or removed all together (and its removal should be noted somewhere since users will search for the functionality it provides).

**Code Sample demonstrating the issue:** ./.

**Running PMD through:** ./.

### PR DESCRIPTION
**Pull request by oowekyala**
This PR 
* removes the rules that were not referenced by any ruleset (fixes #1629)
  * Those not listed in #1629 are GenericLiteralCheckerRule, GenericClassCounterRule, HeaderCommentsRule 
* removes the deprecated VariableNamingConventions from the java and apex modules
* removes the deprecated cyclomatic complexity rules from the java module
* **edit:** removes all other deprecated rules from PMD java

This is just legacy code that makes it harder to do progress on other parts of 7.0.x (eg some of them use the old property constructors).

### CODE REVIEW

**Comment by oowekyala** [comment]
@jsotuyod The build is failing because the old deprecated rulesets (eg `codesize.xml`) reference inexistent rules now. Can I remove them in this PR too? I don't see the point of fixing the files only to remove them later on.

**Comment by adangel** [comment]
At some point before releasing pmd 7, we need to delete the pmd 5 rulesets, which are all deprecated.
We might deprecate more rules until we release pmd 7 (like UseObjectForClearerApi, SimplifyStartsWith - see https://github.com/pmd/pmd/wiki/PMD-7.0.0). Not sure however, whether we would directly remove these rules with pmd 7 - but I think, that's ok, because it's a major version change.
For removing the old rulesets, we need to consider the other languages as well (not only apex and java).

**Comment by adangel** [comment]
Oh, and before actually deleting these "unlinked/unused" rules, we should collect them, if they sound useful, to have suggestions for new rules (see also https://github.com/pmd/pmd/wiki/Project-Ideas-%5BMature%5D#new-rules) - even if we don't implement them now.

**Comment by oowekyala** [comment]
@adangel I think it's ok to remove rules that were not necessarily deprecated for 7.0.x. I think though, that it would be nice for rules that are not found to cause a warning instead of a ruleset parsing error. At the very least, we should collect all failures and present them all to the user instead of one by one. This will make version transitions smoother for the user

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">No java rules are changed!</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Pull request merged**
