### PR TITLE
[java] Make CommentDefaultAccessModifier work for top-level classes

### LINKED ISSUE #1793: [java] CommentDefaultAccessModifier not working for classes
This is a feature-request.

The [documentation](https://pmd.github.io/pmd-6.13.0/pmd_rules_java_codestyle.html#commentdefaultaccessmodifier) specifies that this rule works only for `Method, Constructor, Field or Nested class`. Why not make it work for top-level classes?

### PR DESCRIPTION
**Pull request by boris-petrov**
Fixes #1793.

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">This changeset introduces 1668 new violations, 0 new errors and 0 new configuration errors,<br />
removes 0 violations, 2 errors and 2 configuration errors.<br />
<a href="https://chunk.io/pmd/56b12e52800f48a496cfdac0c71b0bd9/diff/index.html">Full report</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by jsotuyod** [comment]
@boris-petrov thanks for the PR! This looks good, but I wonder if we are missing on reporting top-level enums and top-level annotations as it currently stands. We should probably do it for completeness.

**Comment by boris-petrov** [comment]
@jsotuyod - right now it preserves the old behavior - it doesn't check nested interfaces, annotations and enum constructors. Do we still want that or only to check top-level enums and annotations?

**Comment by jsotuyod** [comment]
I didn't mean for nested ones (ie: a nested annotation within a public interface is public even if nor explicitly said).

But top level enums / annotations:

Foo.java
```java
@interface Foo {}
```

Bar.java
```java
enum Bar {
  A, B, C;
}
```

**Comment by boris-petrov** [comment]
@jsotuyod - done. But what are we going to do with the millions of warnings that appeared in PMD itself because of this change? :)

**Comment by jsotuyod** [comment]
@boris-petrov PMD itself? you mean [this](https://github.com/pmd/pmd/pull/1798#issuecomment-487315975)?

That's PMD running on some baseline projects (checkstyle and spring for the time being), we use it as real-case scenarios to evaluate the changes to rules… making sure we don't introduce new false positives, and that the new violations make sense.

This change in particular seems more than ok, we should be able to merge it as is.

**Comment by boris-petrov** [comment]
@jsotuyod - no, I mean [this](https://github.com/pmd/pmd/pull/1798#issuecomment-487315975) where it says `This changeset introduces 1965 new violations`. :D

**Comment by jsotuyod** [comment]
@boris-petrov nope, that is just our [regression tester](https://github.com/pmd/pmd-regression-tester) letting us now what would change from the baseline (master) by including this PR. No need to worry about it.

**Comment by adangel** [comment]
While looking through the changes, have the following questions:

* Should we add a property for this new behaviour? The PR as it is would cause new violations, if users have this rule enabled and just upgrade PMD. With the property, we could preserve the default behaviour (of ignoring top-level classes).
** It boils probably down to: is this a enhancement or a fix for a false-negative?
** Side note: similar case is #1799, which I already merged: This is a false-negative - so fixing this also creates new violations.
* The test cases cover annotations, classes and enum. I was wondering, why interfaces are not covered by this rule. It seems, they are deliberately ignored... anybody knows why? I found this old issue #1211 - which indicates that we should maintain some kind of compatibility between minor versions.
** supporting interfaces would definitely be a feature/enhancement and require a property switch
** if we do this, that's probably for another PR

**Comment by boris-petrov** [comment]
@adangel - this PR is definitely a breaking change and will cause errors in user code but I think it fixes false-negatives so perhaps there should be no flag for it.

As for the interfaces - not sure why they are not handled. I also wondered that while I was looking through the code. Perhaps another PR for them is a good idea, yes.

**Comment by KroArtem** [comment]
@adangel , @boris-petrov 

Hello there!
I came to this ticket after upgrading PMD in our project to 6.15

Consider I have the following enum:

```
package com.ourapp.constants.forms;

import java.util.Arrays;
public enum OptionConditionsMenu {
    REDIRECT(Constants.REDIRECT),

    CONTINUE_TO_NEXT_PAGE(Constants.REDIRECT, "Continue to next page"),
    GO_TO_PAGE(Constants.REDIRECT, "Go to page %d"),

    private String[] titles;

    OptionConditionsMenu(String... titles) {
        this.titles = Arrays.copyOf(titles, titles.length);
    }

    public String[] getTitles() {
        return titles.clone();
    }

    @Override
    public String toString() {
        return titles[0];
    }

    private static class Constants {
        static final String REDIRECT = "Redirect";
    }

}
```

I've reduced it a bit just not to be that big. When PMD checks this file, it shows the following warning:
```
May 26, 2019 8:30:59 PM net.sourceforge.pmd.RuleSet apply
WARNING: Exception applying rule MethodReturnsInternalArray on file /directory/com/ourapp/constants/forms/OptionConditionsMenu.java, continuing with next rule
java.lang.NullPointerException
	at net.sourceforge.pmd.lang.java.rule.bestpractices.AbstractSunSecureRule.isField(AbstractSunSecureRule.java:42)
	at net.sourceforge.pmd.lang.java.rule.bestpractices.MethodReturnsInternalArrayRule.visit(MethodReturnsInternalArrayRule.java:52)
	at net.sourceforge.pmd.lang.java.ast.ASTMethodDeclaration.jjtAccept(ASTMethodDeclaration.java:33)
	at net.sourceforge.pmd.lang.java.ast.AbstractJavaNode.childrenAccept(AbstractJavaNode.java:60)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:84)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:130)
	at net.sourceforge.pmd.lang.java.ast.ASTClassOrInterfaceBodyDeclaration.jjtAccept(ASTClassOrInterfaceBodyDeclaration.java:43)
	at net.sourceforge.pmd.lang.java.ast.AbstractJavaNode.childrenAccept(AbstractJavaNode.java:60)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:84)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:135)
	at net.sourceforge.pmd.lang.java.ast.ASTEnumBody.jjtAccept(ASTEnumBody.java:22)
	at net.sourceforge.pmd.lang.java.ast.AbstractJavaNode.childrenAccept(AbstractJavaNode.java:60)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:84)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:260)
	at net.sourceforge.pmd.lang.java.ast.ASTEnumDeclaration.jjtAccept(ASTEnumDeclaration.java:23)
	at net.sourceforge.pmd.lang.java.ast.AbstractJavaNode.childrenAccept(AbstractJavaNode.java:60)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:84)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:280)
	at net.sourceforge.pmd.lang.java.ast.ASTTypeDeclaration.jjtAccept(ASTTypeDeclaration.java:37)
	at net.sourceforge.pmd.lang.java.ast.AbstractJavaNode.childrenAccept(AbstractJavaNode.java:60)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:84)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:255)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visitAll(AbstractJavaRule.java:39)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.apply(AbstractJavaRule.java:27)
	at net.sourceforge.pmd.lang.rule.AbstractDelegateRule.apply(AbstractDelegateRule.java:336)
	at net.sourceforge.pmd.RuleSet.apply(RuleSet.java:499)
	at net.sourceforge.pmd.RuleSets.apply(RuleSets.java:143)
	at net.sourceforge.pmd.SourceCodeProcessor.processSource(SourceCodeProcessor.java:184)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:96)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:51)
	at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:78)
	at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:24)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

I believe the source of the problem is that in `MethodReturnsInternalArrayRule:49` there is this line of code:
```ASTClassOrInterfaceDeclaration td = method.getFirstParentOfType(ASTClassOrInterfaceDeclaration.class);
```
This one becomes null as it's a enum and this check fails:
```            if (!isField(vn, td)) {```

**Comment by adangel** [comment]
Hi @KroArtem , thanks for reporting!
This looks like a bug in another rule: [MethodReturnsInternalArray](https://pmd.github.io/pmd-6.15.0/pmd_rules_java_bestpractices.html#methodreturnsinternalarray). Seems like this rule can't cope with enums.
Could you please create a new issue for that?
Thanks!

**Comment by KroArtem** [comment]
@adangel , that's corrrect! Will create one.

I've looked through changelog and saw changes in MethodReturnsInternalArray https://github.com/pmd/pmd/pull/1799 
Those PR referred to this one where I saw some thoughts about breaking changes and talks about enums/interfaces not being handled. This made me think it's the root of the problem.

**Pull request merged**
