### PR TITLE
[java] Relax AbstractClassWithoutAnyMethod when class is annotated by @AutoValue

### LINKED ISSUE #438: [java] Relax AbstractClassWithoutAnyMethod when class is annotated by @AutoValue
**Rule Set:**
```xml
<rule ref="rulesets/java/design.xml"/>
```

**Description:**
I have an abstract class that implements an interface. The implementation will be generated by [AutoValue](https://github.com/google/auto/tree/master/value).

**Code Sample demonstrating the issue:**

```java
@AutoValue public abstract class Something implements Some {
}
```

**Running PMD through:** *[Gradle]*

How do you guys feel about relaxing `AbstractClassWithoutAnyMethod` if you have an abstract class that implements an interface? If you feel like it's to much of a relaxation we could also apply the constraint of having an `@AutoValue` annotation on the type.

### PR DESCRIPTION
**Pull request by vanniktech**
Please, prefix the PR title with the language it applies to within brackets, such as *[java]* or *[apex]*. If not specific to a language, you can use *[core]*

Before submitting a PR, please check that:
 - [X] The PR is submitted against `master`. The PMD team will merge back to support branches as needed.
 - [X] `mvn test` passes.
 - [X] `mvn checkstyle:check` passes. [Check this for more info](https://github.com/pmd/pmd/blob/master/CONTRIBUTING.md#code-style)

**PR Description:**

Fixes #438 thanks to @oowekyala in #556.

### CODE REVIEW

**Comment by jsotuyod** [comment]
@vanniktech thanks for the PR! It's amazing you managed to get it done.

As with #556, this won't work if instead of an import we annotate the class with `@com.google.auto.value. AutoValue`. The fix is the exact same one: use type resolution.

[This commit](https://github.com/pmd/pmd/pull/556/commits/41123508bc7ebad814f024232d5b894a69c6365e) shows exactly how to do it. Use the `typeof` function on the `@Image` instead of direct string matching, and add `typeResolution="true"` to the rule definition on the design ruleset xml.

With that, this PR is good to go into 6.0.0.

**Comment by vanniktech** [comment]
Whops should have seen that from the first place. I addressed the comments and added another test for the fully qualified name case.

**Comment by jsotuyod** [comment]
Thanks! I'll get this merged once I have some spare time.

**Comment by jsotuyod** [comment]
Merged! This will be part of PMD 6.0.0, thanks again for the contribution!

**Pull request merged**
