### PR TITLE
[apex] Improving detection of SOQL injection

### PR DESCRIPTION
**Pull request by sgorbaty**
Hey @jsotuyod!

This enhancement improves detection of SOQL injection in variables passed to Database.query.

Cheers,
Sergey

### CODE REVIEW

**Comment by jsotuyod** [comment]
This will be released in PMD 5.5.3 and later. Thanks again!

**Comment by up2go-rsoesemann** [comment]
@jsotuyod When will 5.5.3 be released?

**Comment by adangel** [comment]
@up2go-rsoesemann Is this a request to release 5.5.3 soon or is this a request to hold, because you want to add more PRs to this release? In any case, I won't release before the holidays. And as @jsotuyod mentioned in a different thread, if your PRs don't make it into 5.5.3, then they will be in 5.5.4...

**Comment by up2go-rsoesemann** [comment]
@adangel sorry for the confusion. @sgorbaty the contributor of security rules was asking how much time there is for him to add more rules and get them into the next release. So neighter a release sooner nor later.

**Pull request merged**
