### PR TITLE
[java] Exclude ByteArrayInputStream from CloseResource

### LINKED ISSUE #1921: [java] CloseResource false positive with ByteArrayInputStream
**Affects PMD Version:** 6.16
**Rule:** [CloseResource](https://pmd.github.io/latest/pmd_rules_java_errorprone.html#closeresource)
**Description:**

The rule makes an exception for `ByteArrayOutputStream` but not the input stream. From the doc:

> Closing a ByteArrayInputStream has no effect. The methods in this class can be called after the stream has been closed without generating an IOException.

**Code Sample demonstrating the issue:**
```java
import java.io.ByteArrayInputStream;
import java.nio.charset.StandardCharsets;

class Foo {

    {
        ByteArrayInputStream bis = new ByteArrayInputStream("fooString".getBytes(StandardCharsets.UTF_8));
    }
}
```

### PR DESCRIPTION
**Pull request by oowekyala**
Fixes #1921

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">This changeset introduces 0 new violations, 0 new errors and 0 new configuration errors,<br />
removes 24 violations, 0 errors and 2 configuration errors.<br />
<a href="https://chunk.io/pmd/6e9afd547cb243c5a54a4719392e7947/diff/index.html">Full report</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by jsotuyod** [comment]
@adangel @oowekyala thinking out loud… wouldn't `StringReader` have the same issue?

**Comment by oowekyala** [comment]
@jsotuyod You're probably right. `StringReader::close` is not a noop and releases the reference to the underlying string... But so, the StringReader instance becoming unreachable (garbage collectable) is in the most common case equivalent to closing it, meaning there's rarely a point in closing it explicitly at all...

**Comment by adangel** [comment]
Since `StringReader::close` is *not* a noop (see http://hg.openjdk.java.net/jdk/jdk/file/aaa83519e723/src/java.base/share/classes/java/io/StringReader.java#l200), I simply thought, then we indeed *should* request to have it closed and cannot ignore it.

It's on the one side just a reference to the string, but a closed StringReader behaves differently than a [ByteArrayInputStream](http://hg.openjdk.java.net/jdk/jdk/file/aaa83519e723/src/java.base/share/classes/java/io/ByteArrayInputStream.java#l289): you can't read from a closed StringReader, but you can read from a closed ByteArrayInputStream... 

We could however add `java.io.CharArrayWriter` to the ignored classes. Its implementation is similar to  ByteArrayOutputStream or StringWriter.

**Comment by jsotuyod** [comment]
@adangel good point! I agree with you

**Comment by adangel** [comment]
@jsotuyod @oowekyala I've just now added `java.io.CharArrayWriter` to the ignores for CloseResource.

**Pull request merged**
