### PR TITLE
CPD: Remove invalid positioned BOM character

### PR DESCRIPTION
**Pull request by wener-tiobe**
## Describe the PR

I have encoutered situations where comment headers are injected programmatically. This results in the BOM character being pushed away from the beginning of the file. When CPD encounters this character, it breaks. As I do not consider this a flaw of CPD, I would like to propose this PR as an enhancement.  This PR checks for the existense a BOM character and cuts it out.
I could have defined the BOM character as a character to skip in the Grammar/Lexer. However then this has to be done for all languages. As this phenomenon is language independent, I'd like to propose this solution. Of course I'm open to any suggestions to have a better solution.

## Related issues

- Fixes #

## Ready?

- [x] Added unit tests for fixed bug/feature
- [x] Passing all unit tests
- [x] Complete build `./mvnw clean verify` passes (checked automatically by github actions)
- [x] Added (in-code) documentation (if needed)

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">Compared to master:<br />
This changeset changes 0 violations,<br />
introduces 0 new violations, 0 new errors and 0 new configuration errors,<br />
removes 0 violations, 0 errors and 0 configuration errors.<br />
<a href="https://github.com/pmd/pmd/actions/runs/6156084014">Download full report as build artifact</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by oowekyala** [comment]
The BOM character is potentially not only used to represent a BOM but it's a kind of zero-width space in unicode. It shouldn't be interpreted as a BOM unless it's the first character of a data stream. I therefore don't think it's a good idea to make a provision for a misplaced BOM in our implementation. The problem is with the code that injects the comments and breaks the file encoding, not with CPD.

**Comment by wener-tiobe** [comment]
Hi oowekyala, I agree the code is wrong. However it just compiles perfectly. Also IDE's do not have a problem with this.
Therfore I think it would be good if CPD could also handle this. Another route we could go is to specify the BOM character in the grammar so that at least CPD does not break. What do you think?

**Comment by oowekyala** [comment]
Hum ok, if other tools handle it then why not. 

If this is only relevant to C/C++ then I would only fix the grammar file to ignore that character.

Otherwise I would put the implementation not in AntlrTokenizer but at the place we remove regular BOMs, ie in TextFileContent::normalizingRead and normalizeCharSeq. This makes sure PMD and non-Antlr CPD languages also get this fix.

Eg there
https://github.com/pmd/pmd/blob/347d5992d13be82418cc1c7018bf6f7e4db7853d/pmd-core/src/main/java/net/sourceforge/pmd/lang/document/TextFileContent.java#L263C18-L263C18
you can add something like
```java
if (c == IOUtil.UTF8_BOM) {
    // Random misplaced BOM, copy up to and not including it.
    result.append(cbuf, nextCharToCopy, i - nextCharToCopy);
    nextCharToCopy = i; // set the next char to copy to be the next one
}
```
(not tested)

**Comment by wener-tiobe** [comment]
Thanks for your suggestion! I'll try to implement that and write a test for that.
Shall I do that in this pull request or shall I create another one?

**Comment by oowekyala** [comment]
Cool, thanks. You can do that in this PR I'll just mark it as WIP.

**Comment by adangel** [comment]
Sorry, I'm a bit late to this, but here are my thoughts:
I don't think we should remove the BOM character in general - if it is not at the beginning of a UTF-8 encoded file, then it is a valid character although deprecated. See https://www.unicode.org/faq/utf_bom.html#bom6

> For backwards [compatibility](https://www.unicode.org/glossary/#compatibility) it should be treated as [ZERO WIDTH](https://www.unicode.org/glossary/#zero_width) NON-BREAKING SPACE (ZWNBSP), and is then part of the content of the file or string.

When we remove U+FEFF in general, then we might run into two problems:
* when we report exact locations (instead of just line numbers), they might be off by a few bytes. Which means, the reported violations would be misplaced. We would need to leverage something like `BaseMappedDocument`/`FragmentedTextDocument` to account for this (which is a bit more complicated I guess).

Note: We already remove the BOM character, if it is the first character of the content. But that is probably OK in terms of reported locations, because the editors don't count the BOM character and start counting with the first character afterwards.

* We wouldn't be able anymore to write rules, that explicitly search for occurrences of U+FEFF. I could see a use case for that, as one should use U+2060 instead.

These two arguments are targeting PMD, but the area, that we change with this PR would not only affect CPD, but PMD as well (TextContent is used now universally for both tools).

I've tested a bit:
* java:
  * Official Java Compiler doesn't support UTF-8+BOM - while PMD supports it, because we remove this character in general. Maybe we should revisit this at some point, to align the behaviors.
  * The character U+FEFF is possible in java code and the java compiler compiles it. Also PMD currently supports this character. Even for identifiers.
  * We explicitly allow this character for identifiers: https://github.com/pmd/pmd/blob/347d5992d13be82418cc1c7018bf6f7e4db7853d/pmd-java/etc/grammar/Java.jjt#L906
  * However, the character is not allowed outside of identifiers or String literals. And this is consistent with how the java compiler behaves: `Test.java:4: error: illegal character: '\ufeff'`
    * That's the actual usecase you have...
* c:
  * GCC supports both UTF-8 with BOM and U+FEFF as part of an identifier or string literal
  * As does PMD (actually CPD)
  * This is, because we already explicitly allow this character in the grammar: https://github.com/pmd/pmd/blob/347d5992d13be82418cc1c7018bf6f7e4db7853d/pmd-cpp/etc/grammar/Cpp.jj#L305
  * However, if U+FEFF is placed somewhere else, then GCC fails with various errors, because it expects that this character starts some identifier etc.
    * Interesting enough, PMD/CPD doesn't have this problem. I don't understand this, because we don't have U+FEFF as whitespace or something declared. I've verified it: We tokenize it as an identifier, as we wrongly allow U+FEFF as a ID_START character (which it is not).
      * However, gcc supports identifiers starting with U+FEFF - which means PMD should do as well. I guess, the difference between gcc failing on compiling such a file (with moving U+FEFF just before a #include or before a typename) is that while PMD is able to tokenize the file, we don't parse it - so in the end it is invalid syntax.


> However it just compiles perfectly. Also IDE's do not have a problem with this, as do other code checkers.

I agree with that. When the official language tools (compilers, interpreters, IDEs) allow this character, PMD/CPD should so as well.


In general, I would prefer to update the grammar of the individual languages to align them to behave like they should (either allow or disallow U+FEFF anywhere or somewhere).

@wener-tiobe Can you please open a new issue with collecting examples for each language that have this problem? So that we both exactly know, what problem we are talking about and what problem we are trying to fix. And which languages are affected - because Java and C are obviously not the problematic languages.

Thanks.

**Review by adangel — CHANGES_REQUESTED** [review]
@wener-tiobe Can you please open a new issue with collecting examples for each language that have this problem? So that we both exactly know, what problem we are talking about and what problem we are trying to fix. And which languages are affected - because Java and C are obviously not the problematic languages.

**Comment by wener-tiobe** [comment]
At this moment only C# is affected. However, I don't see why C and Java could not be affected.
I'll create a new PR where I will adapt the Grammar for C# to ignore/skip the U+FEFF character.

**Comment by adangel** [comment]
> I don't see why C and Java could not be affected.

As in my comment above: If U+FEFF appears somewhere in the Java code (outside of identifiers), the java code is invalid - that means, the java compiler won't compile it anymore. We assume, that with PMD/CPD only valid code is analyzed.
With C, it's a bit different: We only tokenize C code (e.g. no syntax checking by parsing) and CPD already swallows U+FEFF. While putting a U+FEFF character somewhere in C source might render the whole file invalid (compile errors).

**Comment by adangel** [comment]
> I'll create a new PR where I will adapt the Grammar for C# to ignore/skip the U+FEFF character.

Closing this one in favor of a potential future PR.

**Pull request closed without merging**
