### PR TITLE
[java] ConstructorCallsOverridableMethod should consider method calls…

### LINKED ISSUE #1718: [java] ConstructorCallsOverridableMethod false positive when calling super method
Affects PMD Version: 6.12.0
Rule: [ConstructorCallsOverridableMethod](https://pmd.github.io/latest/pmd_rules_java_errorprone.html#constructorcallsoverridablemethod)
Running PMD through: PMD Eclipse Plugin version 4.1.0

Code Sample demonstrating the issue:

```java
public class A {
    public void doA() {}
}

public class B extends A {
    public B() {
        super.doA();  // <-- PMD: Overridable method 'doA' called during object construction
    }

    @Override
    public void doA() {
        throw new UnsupportedOperationException();
    }
}
```

Description:

In B's constructor, PMD reports that an overridable method is called. However, it is a super method call. So I think it is a false positive.

### LINKED ISSUE #2348: [java] ConstructorCallsOverridableMethod occurs when unused overloaded method is defined
**Affects PMD Version:** 6.11.0, 6.21.0

**Rule:** [ConstructorCallsOverridableMethod](https://pmd.github.io/latest/pmd_rules_java_errorprone.html#constructorcallsoverridablemethod)

**Description:**
If a constructor calls a non-overridable public method, and this method has an overridable overloaded version (which is not called from the constructor or from the non-overridable version,) then a ConstructorCallsOverridableMethod rule exception is raised.

**Code Sample demonstrating the issue:**

```java
public class Scratch {
    private Long member = 0L;

    public Scratch(final Long v) {
        setMember(v);
    }

    public final void setMember(final Long v) {
        this.member = v;
    }

    // Renaming this or marking it as final prevents the
    // 'ConstructorCallsOverridableMethod' rule from being broken.
    public void setMember(final String n) {
        setMember(Long.valueOf(n));
    }
}
```

**Running PMD through:** Gradle (with version 6.11.0) and CLI (with version 6.21.0)

### LINKED ISSUE #4099: [java] ConstructorCallsOverridableMethod should consider method calls with var access
**Affects PMD Version:6.47.0** 

**Rule:ConstructorCallsOverridableMethod**

Please provide the rule name and a link to the rule documentation:
<https://pmd.sourceforge.io/pmd-6.48.0/pmd_rules_java_errorprone.html#constructorcallsoverridablemethod>

**Description:**
Hi, we are doing research in testing static analyzer. Our approach found a false negative about the rule ConstructorCallsOverridableMethod.

In the first example below, PMD should have reported a warning at line 4, but not. However, PMD can report  the warning at line 3 in the second example. Hence, I think this is a false negative.

**First example (False negative)**
```java
public class Foo {
  final boolean tag = true;
  public Foo() {
    bar(tag);  // should report a warning at this line
  }
  public void bar(boolean b) {}
}
```
**Second example (Can be detected)**
```java
public class Foo {
  public Foo() {
    bar(true);  // should report a warning at this line
  }
  public void bar(boolean b) {}
}
```

**Expected outcome:**

PMD should report a violation at line 4, but doesn't. This is a false-negative.

**Running PMD through:** *[CLI]*

### PR DESCRIPTION
**Pull request by adangel**
… with var access

- Fixes #4099
- Fixes #1718
- Fixes #2348

The rule `ConstructorCallsOverridableMethod` now:
* finds method calls with parameters more reliably -> this adds new violations (fixes the false negative in #4099)
* reports for indirect calls (method chains) the found call stack - allowing to understand the message better
* ignores method calls on super - there the problem that an unknown subclass would override the method isn't given. At the time you write the code, your superclass is known. The rule previously noticed some super method calls, but not all. Now all super method calls are ignored. (fixes #1718)

## Ready?

- [x] Added unit tests for fixed bug/feature
- [x] Passing all unit tests
- [x] Complete build `./mvnw clean verify` passes (checked automatically by github actions)
- [x] Added (in-code) documentation (if needed)

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">Compared to master:<br />
This changeset changes 0 violations,<br />
introduces 20 new violations, 0 new errors and 0 new configuration errors,<br />
removes 204 violations, 2 errors and 6 configuration errors.<br />
<a href="https://chunk.io/pmd/ea8c74232fb24bed9df9cce91b25bbbf/diff1/index.html">Full report</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by adangel** [comment]
There seems to be new false negatives now:

* https://github.com/checkstyle/checkstyle/tree/checkstyle-9.1/src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4841indentation/ClassWithChainedMethodsCorrect.java#L9

* https://github.com/openjdk/jdk/blob/jdk-11%2B28/src/java.base/share/classes/java/io/PipedInputStream.java#L126

* https://github.com/openjdk/jdk/blob/jdk-11%2B28/src/java.base/share/classes/jdk/internal/org/xml/sax/InputSource.java#L140

* https://github.com/spring-projects/spring-framework/tree/v5.3.13/spring-aop/src/main/java/org/springframework/aop/aspectj/TypePatternClassFilter.java#L60

The new violations seem to be correct, though.

**Comment by adangel** [comment]
We should maybe not merge this in this state yet: It introduces some false negatives now, e.g. https://github.com/spring-projects/spring-framework/blob/v5.3.13/spring-beans/src/main/java/org/springframework/beans/factory/support/AbstractBeanDefinition.java#L230 is not detected anymore now...

**Comment by adangel** [comment]
Ok, this is finally ready.

The rule now:
* finds method calls with parameters more reliably -> this adds new violations (fixes the false negative in #4099)
* reports for indirect calls (method chains) the found call stack - allowing to understand the message better
* ignores method calls on super - there the problem that an unknown subclass would override the method isn't given. At the time you write the code, your superclass is known. The rule previously noticed some super method calls, but not all. Now all super method calls are ignored.

**Pull request merged**
