### PR TITLE
[java] Update rule AvoidInstantiatingObjectsInLoops

### PR DESCRIPTION
**Pull request by adangel**
## Describe the PR

- Part of #2701

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          2 Messages
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">Compared to pmd/7.0.x:<br />
This changeset changes 0 violations,<br />
introduces 1537 new violations, 0 new errors and 0 new configuration errors,<br />
removes 0 violations, 2 errors and 0 configuration errors.<br />
<a href="https://chunk.io/pmd/ce00f4e1eeee47b7bc2ab3b2643e2ed1/diff1/index.html">Full report</a></td>
    </tr>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">Compared to master:<br />
This changeset changes 0 violations,<br />
introduces 28 new violations, 1 new errors and 0 new configuration errors,<br />
removes 229 violations, 8 errors and 3 configuration errors.<br />
<a href="https://chunk.io/pmd/ce00f4e1eeee47b7bc2ab3b2643e2ed1/diff2/index.html">Full report</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by adangel** [comment]
1. false-negative:

```java
WRONG_LANGUAGE_CODE_KEY, new Object[] {code}, getId(), getClass(), null);
```

(https://github.com/checkstyle/checkstyle/blob/checkstyle-8.10/src/main/java/com/puppycrawl/tools/checkstyle/checks/TranslationCheck.java#L209)

ArrayAllocations are not considered anymore obviously....

2. fixed false-positive:

```java
for (String configName : new String[] {"config", "test"}) {
```

(https://github.com/checkstyle/checkstyle/blob/checkstyle-8.10/src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java#L1386)

We should add a test case for this.

3. fixed false-positive:

```java
this.propertyValueList.add(new PropertyValue(pv));
```

(https://github.com/spring-projects/spring-framework/blob/v5.0.6.RELEASE/spring-beans/src/main/java/org/springframework/beans/MutablePropertyValues.java#L73)

Maybe worth to add a test case - I guess in pmd6 we stumble over "this." ...

4. fixed false-positive:

```java
this.configResources[i] = new ClassPathResource(paths[i], clazz);
```

(https://github.com/spring-projects/spring-framework/blob/v5.0.6.RELEASE/spring-context/src/main/java/org/springframework/context/support/ClassPathXmlApplicationContext.java#L200)

Same as 3 - we probably stumble in pmd6 over "this." for this array access. Maybe worth a test case.

5. accidentally fixed false-positive:

```java
dataBuffers.add(this.bufferFactory.wrap(new byte[]{b}));
```

(https://github.com/spring-projects/spring-framework/blob/v5.0.6.RELEASE/spring-core/src/test/java/org/springframework/core/codec/StringDecoderTests.java#L87)

I think, this is not reported because of the array allocation. But we should make sure, that this is not reported at all, because it is part of the "Collection.add" call - which should be ignored. In this case, it is not the direct argument, but only indirectly.

6. false-positive:

```java
cookieStrings[i] = new ToStringCreator(cookie)...
```

(https://github.com/spring-projects/spring-framework/blob/v5.0.6.RELEASE/spring-test/src/main/java/org/springframework/test/web/servlet/result/PrintingResultHandler.java#L271)

It's assigning it to an array so it should be ignored. Maybe we don't recognize the method call chain correctly...

**Comment by adangel** [comment]
New round:

1. false positive

```java
powerCache[i] = new BigInteger[] { BigInteger.valueOf(i) };
```

(https://github.com/openjdk/jdk/blob/jdk-11%2B28/src/java.base/share/classes/java/math/BigInteger.java#L1255)

ArrayAllocation should also be ignored if it is assigned to an array (like collection).

2. false positive

```java
return new Proxy[] {SocksProxy.create(saddr, socksProxyVersion())};
```

(https://github.com/openjdk/jdk/blob/jdk-11%2B28/src/java.base/share/classes/sun/net/spi/DefaultProxySelector.java#L316)

ArrayAllocation should also be ignored, if the array is returned and therefore the loop is exited.

3. fixed false positive - need to add a test

```java
pathResolver.setAllowedLocations(getLocations().toArray(new Resource[0]));
```

(https://github.com/spring-projects/spring-framework/blob/v5.0.6.RELEASE/spring-webmvc/src/main/java/org/springframework/web/servlet/resource/ResourceHttpRequestHandler.java#L390)

getLocations() returns a Collection, so the ArrayAllocation is used in a collection method call. That's correct, this usage should not be flagged.

**Review by oowekyala — APPROVED** [review]
Thanks, I think this is fine

**Pull request merged**
