### PR TITLE
[core] Fix pmd warnings (IdenticalCatchCases)

### PR DESCRIPTION
**Pull request by gibarsin**
Before submitting a PR, please check that:
 - [ ] The PR is submitted against `master`. The PMD team will merge back to support branches as needed.
 - [x] `./mvnw clean verify` passes. This will [build](https://github.com/pmd/pmd/blob/master/BUILDING.md) and test PMD, execute PMD and checkstyle rules. [Check this for more info](https://github.com/pmd/pmd/blob/master/CONTRIBUTING.md#code-style)

**PR Description:**
Fix the main pmd/7.0.x branch's build by fixing Checkstyle errors on repeated code in catch blocks.

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">No java rules are changed!</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by adangel** [comment]
Thanks  for the PR.

I have a few questions:
* What kind of build error to you experience? I don't see any: https://travis-ci.org/pmd/pmd/branches - the branch "pmd/7.0.x" is green.
* Do you mean the PMD warnings of the rule IdenticalCatchCases instead of checkstyle? These are only warnings and are not failing the build -> https://travis-ci.org/pmd/pmd/jobs/605700450#L5183
* If so, any particular reason why you want to fix this only for the pmd/7.0.x branch? We have the identical code in master (https://github.com/pmd/pmd/blob/8e745acf37c60c4b3c60eaa4a51b8d0e8e61795a/pmd-core/src/main/java/net/sourceforge/pmd/RuleSetWriter.java#L93-L101), IMHO we should fix it there first

**Comment by gibarsin** [comment]
@adangel I downloaded the branch, tried `./mvnw clean verify` and it failed because of the repeating code in the catch blocks

**Comment by adangel** [comment]
I'll cherry-pick your commit to master and merge master into pmd/7.0.x afterwards.

**Pull request closed without merging**
