### PR TITLE
[doc] Various updates and improvements

### PR DESCRIPTION
**Pull request by adangel**
This basically finishes/fixes the last point of #405: Remove old site

Additionally:

*   Fixes the images (they were broken on http://pmd.sourceforge.net/snapshot/ due to wrong paths)
*   For the ruleset pages, all the rules names are added now as keywords. This allows to find the rules via the upper right search box. However, we could still improve this: Maybe it would be better to have one page per rule instead of one page per ruleset?
*   Adjusting the "externalInfoUrl" attribute for all rules in all rulesets to point to the new site structure. Note: While adjusting these files, I took the chance to fix tab damages - so a lot of whitespace changes going on there, too. Better to use [this](https://github.com/pmd/pmd/pull/562/files?w=1) to look at the changes.
*   The code examples use now syntax highlighting

And last, but not least:
*   I've moved the changelog from src/site/... into the `docs` hierarchy: The file is now called **release_notes.md** and can be found as `docs/pages/release_notes.md`.

Note: After this is merged, travis will regenerated the rule documentation, so expect one commit by travis.

Before submitting a PR, please check that:
 - [x] The PR is submitted against `master`. The PMD team will merge back to support branches as needed.
 - [x] `mvn test` passes.
 - [x] `mvn checkstyle:check` passes. [Check this for more info](https://github.com/pmd/pmd/blob/master/CONTRIBUTING.md#code-style)

### CODE REVIEW

**Comment by jsotuyod** [comment]
This looks sets to go! @adangel shall you fix the conflicts or want me to do it as I merge?

**Comment by adangel** [comment]
@jsotuyod  I'm currently fixing it and will push again soon :) Thanks!

**Comment by adangel** [comment]
@jsotuyod Here you go! The last commit is special - I've added the unnecessaryParentheses back as deprecated. This will render in the docs as 
bildschirmfoto von 2017-08-17 20-26-53

I hope, having this rule deprecated and in the `RuleSetFactoryCompatibility` class doesn't cause any problems...

**Comment by jsotuyod** [comment]
@adangel amazing. I don't think so... the old singleton rule was deprecated and moved to the utility class one...

I'll prepare for the merge then.

**Comment by jsotuyod** [comment]
Done!

**Pull request merged**
