### PR TITLE
[java] Fix false-positive in JUnitAssertionsShouldIncludeMessage

### LINKED ISSUE #2149: [java] JUnitAssertionsShouldIncludeMessage - False positive with assertEquals and JUnit5
**Affects PMD Version:** 6.20.0

**Rule:** [JUnitAssertionsShouldIncludeMessage](https://pmd.github.io/latest/pmd_rules_java_bestpractices.html#junitassertionsshouldincludemessage)

**Additional version:**

* JUnit : 5.5.2
* Gradle : 4.6

**Description:**
With junit 5.5.2 the assertion message is on the last argument .
Here is the link to the javadoc : https://junit.org/junit5/docs/5.0.0-M3/api/org/junit/jupiter/api/Assertions.html#assertEquals-java.lang.Object-java.lang.Object-java.lang.String-
In my sample, the rule should be ok, but when i check it, i have "_JUnit assertions should include a message_" exception.

**Result files:**

```xml
<?xml version="1.0" encoding="UTF-8"?>
<pmd xmlns="http://pmd.sourceforge.net/report/2.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sourceforge.net/report/2.0.0 http://pmd.sourceforge.net/report_2_0_0.xsd"
    version="6.1.0" timestamp="2018-03-27T18:48:51.560">
<file name="D:\Project\Java\issuePmd\src\test\java\SimpleTest.java">
<violation beginline="9" endline="9" begincolumn="9" endcolumn="20" rule="JUnitAssertionsShouldIncludeMessage" ruleset="Best Practices" package="test.java" class="SimpleTest" method="simpleMethod" externalInfoUrl="https://pmd.github.io/pmd-6.1.0/pmd_rules_java_bestpractices.html#junitassertionsshouldincludemessage" priority="3">
JUnit assertions should include a message
</violation>
</file>
</pmd>
```

**Code Sample demonstrating the issue:**

```java
package test.java;

import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.Test;

class SimpleTest {
    @Test
    public void simpleMethod() {
        assertEquals(0, Integer.compare(0, 0), "Not equals 0 != 0");
    }
}
```

**Running PMD through:** _Gradle_

* build.gradle

```groovy-gradle
apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'pmd'

ext {
    junitJupiterVersion = '5.5.2'
}

repositories {
    mavenLocal()
    mavenCentral()
}

pmd{
    toolVersion = "6.20.0"
    ruleSetFiles = files("config/pmd/defaultRuleSet.xml")
    ruleSets = []
}

dependencies {
    // JUnit Jupiter API and TestEngine implementation
    testCompile("org.junit.jupiter:junit-jupiter-api:${junitJupiterVersion}")
    testRuntime("org.junit.jupiter:junit-jupiter-engine:${junitJupiterVersion}")
}

test {
    useJUnitPlatform()
}
```

* defaultRuleSet.xml

```xml
<ruleset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    name="Android Application Rules"
    xmlns="http://pmd.sf.net/ruleset/1.0.0"
    xsi:noNamespaceSchemaLocation="http://pmd.sf.net/ruleset_xml_schema.xsd"
    xsi:schemaLocation="http://pmd.sf.net/ruleset/1.0.0 
                        http://pmd.sf.net/ruleset_xml_schema.xsd" >

    <description>Standard rule set</description>
    <rule ref="category/java/bestpractices.xml" />
</ruleset>
```

### PR DESCRIPTION
**Pull request by adangel**
Fixes #2149 

Before submitting a PR, please check that:
 - [x] The PR is submitted against `master`. The PMD team will merge back to support branches as needed.
 - [x] `./mvnw clean verify` passes. This will [build](https://github.com/pmd/pmd/blob/master/BUILDING.md) and test PMD, execute PMD and checkstyle rules. [Check this for more info](https://github.com/pmd/pmd/blob/master/CONTRIBUTING.md#code-style)

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">This changeset introduces 2 new violations, 0 new errors and 0 new configuration errors,<br />
removes 2 violations, 2 errors and 2 configuration errors.<br />
<a href="https://chunk.io/pmd/b4b547a974aa44f0be74fc6728391dca/diff/index.html">Full report</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by oowekyala** [comment]
This LGTM, I just have one question: aren't those two lines false-negatives?

https://github.com/spring-projects/spring-framework/blob/f5e8f4983f7653169f3da8a3287499fce93cadd4/spring-web/src/test/java/org/springframework/http/converter/json/MappingJackson2HttpMessageConverterTests.java#L113-L114

The next line is flagged though.

**Comment by adangel** [comment]
I think (or hope) they are reported already. We probably don't see it in the regression tester output, since it worked before already - only the differences are shown. But I'll double check in the next few days... (probably not before Friday)

**Comment by adangel** [comment]
I've downloaded the baseline for pmd-regression-tester (see https://sourceforge.net/projects/pmd/files/pmd-regression-tester/) and run the following query with [xmlstarlet](http://xmlstar.sourceforge.net/doc/UG/ch04.html) against it:

```
xmlstarlet sel -N p=http://pmd.sourceforge.net/report/2.0.0 -t -m "/p:pmd/p:file[contains(@name, 'json/MappingJackson2HttpMessageConverterTests.java')]/p:violation[@rule = 'JUnitAssertionsShouldIncludeMessage']" -v "concat(../@name, ':', @beginline, ':', text())" pmd_report.xml
```

The lines 113 and 114 are present (among many others):

```
...
/home/travis/build/pmd/target/repositories/spring-framework/spring-web/src/test/java/org/springframework/http/converter/json/MappingJackson2HttpMessageConverterTests.java:97:
JUnit assertions should include a message
/home/travis/build/pmd/target/repositories/spring-framework/spring-web/src/test/java/org/springframework/http/converter/json/MappingJackson2HttpMessageConverterTests.java:113:
JUnit assertions should include a message
/home/travis/build/pmd/target/repositories/spring-framework/spring-web/src/test/java/org/springframework/http/converter/json/MappingJackson2HttpMessageConverterTests.java:114:
JUnit assertions should include a message
/home/travis/build/pmd/target/repositories/spring-framework/spring-web/src/test/java/org/springframework/http/converter/json/MappingJackson2HttpMessageConverterTests.java:119:
JUnit assertions should include a message
...
```

So, these cases are already covered.

**Pull request merged**
