### PR TITLE
[core] Fix java7 compatibility

### PR DESCRIPTION
**Pull request by adangel**
## Describe the PR

Running PMD with Java7 does not work as promised. Main problems are with JCommander and commons-text.

* Downgrade JCommander for java7 compatibility
* Downgrade commons-text for java7 compatibility
* Scala also requires java8 and it failed indirectly via a ServiceConfigurationError while discovering the language.
  The Scala module itself doesn't need java8, but its dependencies require java8.
* Add integration test

## Related issues

- none

## Ready?

- [x] Added unit tests for fixed bug/feature
- [x] Passing all unit tests
- [x] Complete build `./mvnw clean verify` passes (checked automatically by travis)
- [ ] Added (in-code) documentation (if needed)

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">This changeset introduces 0 new violations, 0 new errors and 0 new configuration errors,<br />
removes 0 violations, 0 errors and 0 configuration errors.<br />
<a href="https://chunk.io/pmd/bd3d736744c846dd8d724ee58c19c2d8/diff/index.html">Full report</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by oowekyala** [comment]
Not sure how to merge this into PMD 7... I see there's still a `jdk-8-modules` profile in `pmd-dist/pom.xml`. Should the new JDK 7 profile be removed, and that other JDK 8 profile merged into the default config?

**Comment by adangel** [comment]
> Not sure how to merge this into PMD 7... I see there's still a `jdk-8-modules` profile in `pmd-dist/pom.xml`.

It seems, we forgot this. the jdk-8-modules profile should be removed in pmd 7, as all modules are now java8 and a treated the same.

> Should the new JDK 7 profile be removed, and that other JDK 8 profile merged into the default config?

I think, it makes sense to add a integration test in PMD 7 for JDK8 - since we run the build with java11 (and therefore our tests). That requires a bit more effort (e.g. I need to make sure, that we can download jdk8 from pmd-code.org/openjdk ).

I can do the merge of this PR on master and make the merge+adjustments to PMD 7 myself, but earliest on Thursday.

**Comment by oowekyala** [comment]
I'd be more comfortable if you did the merge yourself. Thanks!

**Pull request merged**
