### PR TITLE
[core] Fix ResourceLoader open file leaks, fixes #337

### LINKED ISSUE #337: [core] Version 5.5.4 seems to hold file lock on rules JAR (affects Windows only)
**Rule Set:**

See https://github.com/gradle/gradle/blob/master/subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/PmdPluginAuxclasspathIntegrationTest.groovy#L108

**Description:**

After running PMD via the Gradle plugin, the `pmd-rule.jar` cannot deleted anymore on Windows, apparently because some file lock is held. Works with version 5.5.3, does not work with version 5.5.4. Discovered when trying to upgrade the PDM version the Gradle plugin uses, see https://github.com/gradle/gradle/pull/1623#issuecomment-293234259.

**Code Sample demonstrating the issue:**

1. Clone https://github.com/sschuberth/gradle
2. Checkout the *pmd-upgrade* branch
3. Run `./gradlew codeQuality:integTest --tests org.gradle.api.plugins.quality.PmdPluginAuxclasspathIntegrationTest`

**Running PMD through:** *Gradle*

### PR DESCRIPTION
**Pull request by ryan-gustafson**
Addresses issues with open file leaks.

### CODE REVIEW

**Comment by adangel** [comment]
Awesome! Thanks for the PR!

**Comment by adangel** [comment]
@jsotuyod Would this fix be a candidate for a 5.5.6 bugfix release?

**Comment by adangel** [comment]
References #337

**Comment by jsotuyod** [comment]
@adangel yes, most definitely this would be a good candidate for a hot fix.

**Comment by ryan-gustafson** [comment]
Are PR expected to include updates to the changelog too?  I didn't notice it in the PR template.  I seem to recalling including it in the diffs in the pre-git days.

**Comment by jsotuyod** [comment]
We usually add changelog notes ourselves when merging to produce better release notes.

**Pull request merged**
