### PR TITLE
[cpp] Ignore literals and ignore identifiers capability to C++ CPD

### LINKED ISSUE #4835: [cpd] Found match is not maximal
**Affects PMD Version:**  6.55.0

image

```c
void print_fence(short current_row, short fence_size) {
  short i = 0;
  if (current_row == 0 ||
      current_row == fence_size) { // checks for first and last row
    if (fence_size % 2 == 0) {     // checks if the fence is even
      for (; i < fence_size;
           i += 2) { // i += 2 because two characters are being printed
        printf("-|");
      }
    } else {
      printf("|");
      i++; // i++ because one character was printed
      for (; i < fence_size;
           i += 2) { // i += 2 because two characters are being printed
        printf("-|");
      }
    }
  } else {
    if (fence_size % 2 == 0) { // checks if the fence is even
      for (; i < fence_size;
           i += 2) { // i += 2 because two characters are being printed
        printf(" |");
      }
    } else {
      printf("|");
      i++; // i++ because one character was printed
      for (; i < fence_size;
           i += 2) { // i += 2 because two characters are being printed
        printf(" |");
      }
    }
  }
  printf("\n");
}
```

The for loop and if are also identical.

### PR DESCRIPTION
**Pull request by jdupak**
## Describe the PR

Adds ignore literals and ignore identifiers capability to c++ cpd.

## Related issues

- Refs #4835

## Ready?

- [ ] Added unit tests for fixed bug/feature
- [x] Passing all unit tests
- [x] Complete build `./mvnw clean verify` passes (checked automatically by github actions)
- [x] Added (in-code) documentation (if needed)

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">No regression tested rules have been changed.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by jsotuyod** [comment]
@jdupak thanks! Happy to see you were able to manage this!

Overall this looks very neat! This covers all pointers I gave you.

The one thing missing for sure are tests. You can once again get inspiration from how Java test these.

https://github.com/pmd/pmd/blob/master/pmd-java/src/test/java/net/sourceforge/pmd/lang/java/cpd/JavaCpdLexerTest.java#L85-L103

**Comment by adangel** [comment]
Hi @jdupak , thanks for the PR! Is there a chance you can look into creating a unit test for this new feature?

**Comment by jdupak** [comment]
Hi,
I am so sorry, I got my JAR and forgot about this.
I will do my best to send it by Monday.

**Review by adangel — APPROVED** [review]
Awesome, thanks!

**Pull request merged**
