### PR TITLE
Merge 2447

### PR DESCRIPTION
**Pull request by adangel**
## Describe the PR

I tried to merge #2447 into java-grammar - I'm giving up now.

## Related issues

- Relates #2447 

## Ready?

- [ ] Added unit tests for fixed bug/feature
- [ ] Passing all unit tests
- [ ] Complete build `./mvnw clean verify` passes (checked automatically by travis)
- [ ] Added (in-code) documentation (if needed)

### CODE REVIEW

**Comment by oowekyala** [comment]
@adangel Do you mind if I force push this branch ?

**Comment by adangel** [comment]
@oowekyala No problem  - you can also throw it away and just merge it fresh without a PR... just wanted to share my state...

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">No java rules are changed!</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by oowekyala** [comment]
@adangel I usually resolve merge conflicts with the GUI in my ide and didn't really know where to start there, which is why I originally wanted to start over. But actually you already have done most of the hard work. Thanks!

**Pull request merged**
