### PR TITLE
[apex] empty code ruleset for apex

### LINKED ISSUE #624: [apex] Empty catch block
**Rule Set:** Apex

**Description:** New Rule: `EmptyCatchBlock` support for Apex.

**Code Sample demonstrating the issue:**

```
public void doSomething() {
  ...
  try {
    insert accounts;
  } catch (DmlException dmle) {
    // not good
  }
}
```

### PR DESCRIPTION
**Pull request by JAertgeerts**
Please, prefix the PR title with the language it applies to within brackets, such as *[java]* or *[apex]*. If not specific to a language, you can use *[core]*

Before submitting a PR, please check that:
 - [x] The PR is submitted against `master`. The PMD team will merge back to support branches as needed.
 - [x] `mvn test` passes.
 - [x] `mvn checkstyle:check` passes. [Check this for more info](https://github.com/pmd/pmd/blob/master/CONTRIBUTING.md#code-style)

**PR Description:**
Extending the Empty rules from Java to Apex, as they're equally important and applicable. Resolves #624

### CODE REVIEW

**Comment by oowekyala** [comment]
@JAertgeerts That's nice but I think you should port the tests too ^^

**Comment by JAertgeerts** [comment]
I'll add it to the PR tonight

**Comment by jsotuyod** [comment]
@JAertgeerts amazing work!

The `since` xml attribute should be 6.0.0. PMD 5.8.2 is unlikely to exist (no critical issues reported on 5.8.1), the next planned release is 6.0.0.

Porting the test as @oowekyala suggests would be great too.

**Comment by JAertgeerts** [comment]
Can't seem to figure out why the rules aren't being picked up and hence the tests keep failing. Am I missing an obvious element?

**Comment by JAertgeerts** [comment]
I think I looked at the wrong AST. D'oh. Checking tonight.

**Comment by up2go-rsoesemann** [comment]
Hi @JAertgeerts, great to see you contributing Apex rules. It has been a while since the last rule PR.
In case you need help feel free to directly contact me. I was the guy who initiated the Apex language module.

**Comment by JAertgeerts** [comment]
@up2go-rsoesemann Thanks, I will. If you have any other rule suggestions, feel free to open the issues. Should be able to tackle them in the next couple of weeks.

**Comment by adangel** [comment]
@JAertgeerts I don't know, why the unit test are failing, but it might be due to the [apex parser update](https://github.com/pmd/pmd/blob/master/docs/pages/release_notes.md#apex-parser-update) that is on the master branch. The new parser behaves a little bit different when it generates the AST with regards to blocks. I needed to update [the braces ruleset](https://github.com/pmd/pmd/commit/9a71a6fd75b7bc899b19e249afe6bad197098b2c#diff-7bfab4cd8298ec3c1bc638b5a3f5a795) with using `@CurlyBrace='false'`.

**Comment by JAertgeerts** [comment]
@adangel I fixed it, I just wasn't using the Apex AST :-).

**Comment by JAertgeerts** [comment]
@up2go-rsoesemann I'm trying to implement a rule for empty methods but want to exclude virtual ones. Any clue on how I find out if the method has a virtual modifier? The AST is tricky to figure out (attributes and what not).

**Comment by JAertgeerts** [comment]
@up2go-rsoesemann I've added a rule around empty block statements. I've filtered out the abstract methods, but am unable to filter out the virtual ones. Should I keep it in or make it smarter?

**Comment by up2go-rsoesemann** [comment]
@JAertgeerts did you play around with PMD's XPath designer (http://pmd.sourceforge.net/pmd-4.3.0/howtowritearule.html) The virtual feature might sit somewhere else in the AST.

**Comment by JAertgeerts** [comment]
@up2go-rsoesemann Thanks. Opened issue on the force.com ide core.
Track https://github.com/forcedotcom/idecore/issues/232

**Comment by jsotuyod** [comment]
@JAertgeerts it's possible [we are simply missing it here](https://github.com/pmd/pmd/blob/master/pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ASTModifierNode.java#L24-L57).

We should check if it's not being set and we should just add a flag on [`AccessNode`](https://github.com/pmd/pmd/blob/master/pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/AccessNode.java#L12-L37).

If you need help checking this, let me know and I'll gladly give you a hand.

**Comment by jsotuyod** [comment]
I confirm we are not missing it from the modifiers. I can't seem to find it anywhere.

Apex Jorje defines `apex.jorje.data.ast.Modifier$VirtualModifier`, but it doesn't seem to be used / passed over to us. Apex is only showing us `apex.jorje.data.ast.modifier.ModifierNode`, but these 2 seems to be completely unrelated.

**Comment by jsotuyod** [comment]
@JAertgeerts I don't think salesforce will release an updated Jorje version before we hit 6.0.0. I don't feel we should leave out a complete ruleset just because of one rule. Shall we merge this as is, and endure the false positives, or disable the rule altogether?

@up2go-rsoesemann your input as an apex developer is most welcome too.

**Comment by JAertgeerts** [comment]
@jsotuyod  I suggest to merge this as-is. It will still catch the biggest ones.

**Comment by jsotuyod** [comment]
@JAertgeerts merged! Thanks again for the contribution!

**Pull request merged**
