### PR TITLE
[java] Update rule UnnecessaryWrapperObjectCreation

### PR DESCRIPTION
**Pull request by adangel**
## Describe the PR

Updates the rule UnnecessaryWrapperObjectCreation. I've removed the check for the java version, as this looked wrong: Boolean.valueOf has been introduced with java 1.4, and all other *.valueOf method with java 1.5. So actually, this rule should have a minimum language version of 1.5, but I guess, that doesn't matter anymore.

The rule is also directly deprecated, as the new UnnecessaryBoxing replaces it.

The only useful check of this rule is this: `Integer.valueOf(1).toString()` - calls to "toString()", where one should simply use `String.valueOf(1)` instead or `Integer.toString(1)`.

## Related issues

- Part of #2701 
- Relates to #3364 

## Ready?

- [x] Added unit tests for fixed bug/feature
- [x] Passing all unit tests
- [x] Complete build `./mvnw clean verify` passes (checked automatically by github actions)
- [x] Added (in-code) documentation (if needed)

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          2 Messages
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">Compared to pmd/7.0.x:<br />
This changeset changes 0 violations,<br />
introduces 4 new violations, 115 new errors and 0 new configuration errors,<br />
removes 0 violations, 0 errors and 0 configuration errors.<br />
<a href="https://chunk.io/pmd/93716c140d3f4a11a4345113975af6cb/diff1/index.html">Full report</a></td>
    </tr>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">Compared to master:<br />
This changeset changes 30753 violations,<br />
introduces 34201 new violations, 118 new errors and 0 new configuration errors,<br />
removes 141569 violations, 8 errors and 3 configuration errors.<br />
<a href="https://chunk.io/pmd/93716c140d3f4a11a4345113975af6cb/diff2/index.html">Full report</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by oowekyala** [comment]
Thanks!

Maybe if we do the "staged release" of pmd 7 we talked about, then we could remove it in pmd 7.1.0? Like other  `@DeprecatedUntil700` api.

**Comment by adangel** [comment]
So, with #3365 we actually deprecated the rule UnnecessaryWrapperObjectCreation with PMD 6.37.0 without replacement. So we can actually delete it in PMD 7...

**Comment by adangel** [comment]
> The only useful check of this rule is this: Integer.valueOf(1).toString() - calls to "toString()", where one should simply use String.valueOf(1) instead or Integer.toString(1).

Before deleting it, we should make sure, that we somewhere cover this case.

**Comment by oowekyala** [comment]
> Before deleting it, we should make sure, that we somewhere cover this case.

I think it should be part of UnnecessaryBoxing

**Comment by oowekyala** [comment]
So 85e9bfa ensures that UnnecessaryBoxing catches the string cases. So I'm going to merge this to open the pr removing deprecated rules, which includes this one

**Pull request merged**
