### PR TITLE
[Apex] Sharing violation SOQL detection bug fix

### PR DESCRIPTION
**Pull request by sgorbaty**
This is a silly bug, really.

### CODE REVIEW

**Comment by jsotuyod** [comment]
Silly indeed. Will get this merged as soon as Travis passes.

**Comment by jsotuyod** [comment]
Merged for release 5.5.3 and later. Thanks again for your sustained efforts!

Best of lucks tomorrow at the Apex PMD meetup!

**Comment by sgorbaty** [comment]
Hey @jsotuyod I wanted to chat more about creating call graph / control flow graph in Apex.
When would be a good time to sync up?

**Comment by jsotuyod** [comment]
@sgorbaty I'll contact you by email to set it up

**Pull request merged**
