### PR TITLE
[apex] Replace old Jorje parser with new one

### PR DESCRIPTION
**Pull request by adangel**
First shot at the new apex jorje jar.

There is one compilation problem (currently commented out) at `ASTMethodCallExpression.getFullMethodName()`.

There are many failing unit tests - a whole bunch of StackOverflowErrors while determining the endLine of a node...

### CODE REVIEW

**Comment by adangel** [comment]
I also think, it makes sense to use the maven dependency system instead of the uber-jar and add the following dependencies:

```
$ zipinfo apex-jorje-lsp.jar |grep pom.properties
-rw----     2.0 fat       77 bl defN 17-Nov-13 15:02 META-INF/maven/com.salesforce.apex/apex-jorje-lsp/pom.properties
-rw----     2.0 fat      129 bl defN 17-Nov-13 15:02 META-INF/maven/com.google.guava/guava/pom.properties
-rw----     2.0 fat      107 bl defN 17-Nov-13 15:02 META-INF/maven/com.google.code.gson/gson/pom.properties
-rw----     2.0 fat      124 bl defN 17-Nov-13 15:02 META-INF/maven/org.eclipse.xtend/org.eclipse.xtend.lib/pom.properties
-rw----     2.0 fat      130 bl defN 17-Nov-13 15:02 META-INF/maven/org.eclipse.xtext/org.eclipse.xtext.xbase.lib/pom.properties
-rw----     2.0 fat      130 bl defN 17-Nov-13 15:02 META-INF/maven/org.eclipse.xtend/org.eclipse.xtend.lib.macro/pom.properties
-rw----     2.0 fat      120 bl defN 17-Nov-13 15:02 META-INF/maven/ch.qos.logback/logback-classic/pom.properties
-rw----     2.0 fat      117 bl defN 17-Nov-13 15:02 META-INF/maven/ch.qos.logback/logback-core/pom.properties
-rw----     2.0 fat      110 bl defN 17-Nov-13 15:02 META-INF/maven/org.slf4j/slf4j-api/pom.properties
-rw----     2.0 fat      114 bl defN 17-Nov-13 15:02 META-INF/maven/org.apache.commons/commons-lang3/pom.properties
-rw----     2.0 fat       87 bl defN 17-Nov-13 15:02 META-INF/maven/com.salesforce.apex/apex-jorje-semantic-test/pom.properties
-rw----     2.0 fat       83 bl defN 17-Nov-13 15:02 META-INF/maven/com.salesforce.apex/apex-jorje-data-test/pom.properties
-rw----     2.0 fat       82 bl defN 17-Nov-13 15:02 META-INF/maven/com.salesforce.apex/apex-jorje-semantic/pom.properties
-rw----     2.0 fat       78 bl defN 17-Nov-13 15:02 META-INF/maven/com.salesforce.apex/apex-jorje-data/pom.properties
-rw----     2.0 fat       82 bl defN 17-Nov-13 15:02 META-INF/maven/com.salesforce.apex/apex-jorje-services/pom.properties
-rw----     2.0 fat       80 bl defN 17-Nov-13 15:02 META-INF/maven/com.salesforce.apex/apex-jorje-parser/pom.properties
-rw----     2.0 fat      112 bl defN 17-Nov-13 15:02 META-INF/maven/org.antlr/antlr-runtime/pom.properties
-rw----     2.0 fat       68 bl defN 17-Nov-13 15:02 META-INF/maven/com.salesforce.apex/apex-common/pom.properties
-rw----     2.0 fat      126 bl defN 17-Nov-13 15:02 META-INF/maven/com.google.code.findbugs/jsr305/pom.properties
-rw----     2.0 fat      106 bl defN 17-Nov-13 15:02 META-INF/maven/org.openjdk.jol/jol-core/pom.properties
-rw----     2.0 fat       95 bl defN 17-Nov-13 15:02 META-INF/maven/cglib/cglib/pom.properties
-rw----     2.0 fat      125 bl defN 17-Nov-13 15:02 META-INF/maven/org.yaml/snakeyaml/pom.properties
```

This should make the jar smaller and not using the 15MB....

**Comment by adangel** [comment]
Line/column numbering seems to be working again - however, it doesn't seem to be safe: I'm using the call `Locations.useIndexFactory()`, so that we get location information via startIndex/endIndex additionally to beginLine/beginColumn. However, this method is annotation with `com.google.common.annotations.VisibleForTesting`.... Will probably break sooner or later. Currently it seems to be working.

With that change, the StackOverflowErrors are gone.

Still a couple of test failures (20 in total), especially many about SuppressWarnings...

**Comment by adangel** [comment]
All unit tests are green now, so it seems to be working :)

I keep this still as WIP, since I want to do two things before we merge this:
* reduce the jar file size: Since downloading the jar file etc. is anyway a manual step, I plan to add a manual "unwrap uber-jar" step here - to reduce the file size size drastically and use maven's dependency system.
* attach the special jar. This would be a alternative solution to my other PR which uses the shade plugin. Maybe we can just add this jar with the build-helper-maven-plugin and have it on the compile classpath at the same time... Then it would be easy during development and easy to consume for 3rd-party integrations.

**Comment by adangel** [comment]
Oh, and I'll rebase against master, avoiding the 15MB commit and fixing the compile error (probably just a organize imports)

Any ideas what we should do with the Apex Language Version? It's currently [stuck to 35](https://github.com/pmd/pmd/blob/8405ce3d655cf4b7e79a61912cb4361660a9a50e/pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ApexLanguageModule.java#L18), but it should probably be more like 40 or 41. The current version is [41 Winter 2018](https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_reference.htm).

**Comment by adangel** [comment]
Ok, I've made the jar smaller. Interestingly, I couldn't remove com.google.collect.* - it seems like there is a custom guava lib in use. Anybody heard of the class `com.google.common.collect.MoreLists` - this one is missing in the stock guava lib.

Anyway, down to about 5mb (from 15mb).

I did a short tryout with attaching the artifact (not included in these commits here), but ran into chicken-egg-problem: If I add the additional artifact as a dependency (which has the same groupId+artifactid+version but a special classifier), it won't build - since dependencies are resolved first (and in a later stage the missing dependency would be installed).

**Comment by jsotuyod** [comment]
@adangel shall we close #759 in favor of this one then for 6.0.0?

**Comment by up2go-rsoesemann** [comment]
You guys rock!

**Comment by adangel** [comment]
I'm attaching now the jar - that way it is at least available in maven central via pmd-apex (and similar to the way it was with pmd 5.8.1).
I had no luck yet, replacing the direct dependency (which only works if the local repo is in place which is only the case if have checked out pmd sources) with the dependency using the attached artifact...

Using profiles doesn't seem to work, that was my idea:
```
    <profile>
        <id>apex-jorje-build</id>
        <activation>
            <file>
                <exists>${apex.jorje.jar.path}</exists>
            </file>
        </activation>
        <dependencies>
            <dependency>
              <groupId>apex</groupId>
              <artifactId>apex-jorje-lsp-minimized</artifactId>
              <version>${apex.jorje.version}</version>
            </dependency>
        </dependencies>
    </profile>

    <profile>
        <id>apex-jorje-classifier</id>
        <activation>
            <file>
                <missing>${apex.jorje.jar.path}</missing>
            </file>
        </activation>
        <dependencies>
            <dependency>
              <groupId>${project.groupId}</groupId>
              <artifactId>${project.artifactId}</artifactId>
              <version>${project.version}</version>
              <classifier>apex-jorje</classifier>
            </dependency>
        </dependencies>
    </profile>
```

But the dependency "net.sourceforge.pmd:pmd-apex:apex-jorje:6.0.0-SNAPSHOT" is still missing in the pmd-eclipse plugin (where we have a dependency on pmd-dist and only a transitive dependency to pmd-apex...)

**Comment by adangel** [comment]
Ok, alternative solution is ready: I've created a extra submodule called "pmd-apex-jorje" which only provides the jorje jar file and the depenencies.
pmd-apex itself depends on pmd-apex-jorje + pmd-apex-jorje-lib.
Every third party tool can now simply depend on pmd-dist (to get all languages) or pmd-apex, to get specifically all needed apex libraries.

One thing we could still improve: Figure out, which dependencies are needed at all (and double check the versions) and remove unnecessary dependencies.

This now really supercedes #759.

**Pull request merged**
