### PR TITLE
[java] Relax UncommentedEmptyConstructor when @Inject is applied on the constructor.

### LINKED ISSUE #357: [java] UncommentedEmptyConstructor consider annotations on Constructor
**Rule Set:**

```xml
<rule ref="rulesets/java/design.xml"/>
```

**Description:**

The code below will be flagged by PMD with:

```xml
<violation beginline="6" endline="8" begincolumn="11" endcolumn="3" rule="UncommentedEmptyConstructor" ruleset="Design" package="com.ovyapp.android.feature.calendar" class="MyClass" method="MyClass" externalInfoUrl="https://pmd.github.io/pmd-5.5.5/pmd-java/rules/java/design.html#UncommentedEmptyConstructor" priority="3">
Document empty constructor
</violation>
```

Maybe this rule could be relaxed when an annotation is applied on the constructor, especially if it's `javax.inject.Inject` since this annotation can be picked up by annotation processors such as Dagger 2 and let them know that they can build the `MyClass` class.

**Code Sample demonstrating the issue:**

```java
import javax.inject.Inject;

public class MyClass {
  @Inject MyClass() {

  }
}
```

**Running PMD 5.5.5 through:** *Gradle*

### PR DESCRIPTION
**Pull request by vanniktech**
Before submitting a PR, please check that:
 - [X] The PR is submitted against `master`. The PMD team will merge back to support branches as needed.
 - [ ] `mvn test` passes.
 - [X] `mvn checkstyle:check` passes. [Check this for more info](https://github.com/pmd/pmd/blob/master/CONTRIBUTING.md#code-style)

**PR Description:**

I added a test to verify the new behavior although I'm not sure if I'm at the right place for adding the check regarding the `@Inject` annotation. Could you help me there?

Fixes #357

### CODE REVIEW

**Comment by adangel** [comment]
@vanniktech Thanks for getting started on this issue. It seems, you are working on the wrong Rule (ConstructorCallsOverridableMethodRule). If you look into the [design ruleset](https://github.com/pmd/pmd/blob/master/pmd-java/src/main/resources/rulesets/java/design.xml#L1412), you can see, that the rule `UncommentedEmptyConstructor` is actually a XPath rule - and there is no extra java implementation. You'll need to fix the XPath expression, that is provided in the ruleset file.
A helpful tool for that is the [Designer](https://github.com/pmd/pmd/blob/master/pmd-core/src/main/java/net/sourceforge/pmd/util/designer/Designer.java). You can start it from the binary distribution via `run.sh designer` (or under Windows via `designer.bat`). It shows you the AST tree of the source file and allows you to execute XPath queries against it.

**Comment by vanniktech** [comment]
@adangel thanks for the starting points. I've tried `./run.sh designer` although it yields:

```
./run.sh: line 65: cd: ./../lib: No such file or directory
Picked up JAVA_TOOL_OPTIONS: -Dapple.awt.UIElement=true
Error: Could not find or load main class net.sourceforge.pmd.util.designer.Designer
```

**Comment by jsotuyod** [comment]
That's weird. Are you using a binary zip to run pmd, or doing so from sources?

Please, note Travis is failing with this PR as it stands. Let us know if you need any help.

**Comment by vanniktech** [comment]
I'm trying to run it from the sources. PR is failing since I've tried to do the rule myself (since I can't run the designer) without any knowledge of it and it does not seem to work.

**Comment by jsotuyod** [comment]
@vanniktech you are probably running the script from sources then, which is no the intended way.

I recommend you do it from a bin bundle zip, or directly running from source the main in net.sourceforge.pmd.util.designer.Designer, **making sure that pmd-java is included in the classpath**

**Comment by vanniktech** [comment]
I'm sorry but this requires too much hassle for setting up. Initially I thought it'd be easy to archive this without having to install too many things. I'll let someone else take this over.

**Pull request closed without merging**
