### PR TITLE
[java] New Java XPath functions

### LINKED ISSUE #1787: [core] Match abstract types in XPath queries
Closely related to #1785 

Turning some nodes into interfaces like in #1759 removes some nodes from the AST, and makes us rely more on the Java way of abstracting stuff (interfaces). XPath uses other mechanisms and we must also cater to them so as not to lose expressivity.

Today an XPath expression `//Expression` would match most expression nodes (though not all, see footnote 1).

Turning ASTExpression into an interface improves the Java side of the API, but now there's no more way to match *all* expressions. One possible solution that's already in #1759 is to expose an attribute on the relevant nodes: 

https://github.com/oowekyala/pmd/blob/f978a1e71171dd30a40573f9ef6f944e032d8b2f/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTExpression.java#L41-L48

This makes it possible to match expressions with `//*[@Expression=true()]`

Doing that for every interesting supertype adds noise to the Java API though, and I don't think it's a viable solution in the long run. It's also not very readable.

## Towards a better solution

The XPath specification mandates that an element have a single local name. This makes it impossible to specify that eg an InstanceOfExpression can be matched by a set of names, eg both the names `InstanceOfExpression` and `Expression`. So that means there's no way a segment `/Expression/` in the new grammar matches an InstanceOfExpression.

So we can rule that out.

### XPath Schema

XPath has a type system and some syntax to match some elements by type. The syntax is described [here](https://www.w3.org/TR/xpath-31/#prod-xpath31-ElementTest). If we could do that, then a test for an expression could look like `//element(*, Expression)`.

This syntax is nice, but schema aware processing is only available in the professional editions of Saxon. 

So we can't implement that directly with Saxon

### Some custom function

We could also expose a custom function, that tests directly the type of the node. 

E.g. 
* `//*[nodeIs('net.sourceforge.pmd.lang.java.ast.ASTExpression)]`, 
* or with some suger `//*[nodeIs('Expression')]`, where we add the necessary prefix to the string `'Expression'`

### XPath expression rewrite

If we have #1243, then we can actually rewrite segments like `//element(*, Expression)` to some type test like above, and thus mimic the normal XPath syntax transparently. 

#### Closed set of matchable supertypes

The above solution would technically allow to match any java type. Do we want that though? Should someone be able to match `AbstractJavaNode`, `Node`, or some interfaces that are just there for implementation convenience, like `AnnotatableNode`? That would increase coupling between XPath queries and the Java code...

If the answer to the above questions are *no*, then we should design a way to specify *which* type should be matchable. I expect this to use exactly the same info as #1786, so implementing it could allow us to do that.

----
 
Footnote 1: There are some corner cases in the current grammar where no ASTExpression node is pushed, even if the node is an expression. That happens eg for the concise try-with-resources statement which pushes a bare Name...

### PR DESCRIPTION
**Pull request by oowekyala**
## Describe the PR

These are changes extracted from #2899 for ease of reference, namely:
- small changes to pmd-core and pmd-lang-test
  - I just improved error reporting for XPath rules. Now a failure should give more info, also, all failures are reported as `PmdXPathException`, including failure in our custom functions (currently there's a mix of raw RuntimeException, IllegalArgumentException, IllegalStateException)
- the changes to parts of pmd-java that are not rule specific, including
  - minute improvements to the ast api
  - bugfixes for TypeTestUtil, based on the regression tester feedback from #2899
  - the new InvocationMatcher type, which matches method/constructor calls based on a string signature. There is a corresponding XPath function: `matchesSig`
  - Other new XPath functions:
    - `nodeIs`: refs #1787
    - `hasAnnotation`: refs #1787
    - `modifiers`, `explicitModifiers`: refs #1307

This should be merged before #2899, to reduce that PR's diff

## Related issues

- Fixes #1787 for java
- Refs #2701 
- Part of #2523 

## Ready?

- [x] Added unit tests for fixed bug/feature
- [ ] Passing all unit tests
- [ ] Complete build `./mvnw clean verify` passes (checked automatically by travis)
- [x] Added (in-code) documentation (if needed)

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Running pmdtester failed, this message is mainly used to remind the maintainers of PMD.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by adangel** [comment]
>   E, [2020-11-15T15:23:06.773764 #11856] ERROR -- : Running pmdtester failed: #<Slop::MissingArgument: missing argument for -b, --base-branch>

Maybe the regression tester is not working yet for PRs against pmd/7.0.x? I'm still working through mails...

**Comment by adangel** [comment]
Ok, re-running the workflow is only useful for temporary failed builds. It will re-run the builds with exactly the same git ref/sha, see https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/re-running-a-workflow:

> Re-running a workflow uses the same GITHUB_SHA (commit SHA) and GITHUB_REF (Git ref) of the original event that triggered the workflow run.

If the base branch of a PR as advanced, that's not taken into consideration. The only way to rebuild seems to be a real push to the PR branch. Then a new pull_request event is created with an update git ref/sha.

I've pushed another merge now, let's see, if the regression tester is running now correctly...

Btw: the github ref/sha in pull requests is always the test merge commit created automatically by github.

**Comment by adangel** [comment]
Isn't it fun? New error:

```
   Please update your dependency to directly use the correct version 'xml-apis:xml-apis:1.0.b2'.
  Resolution will only pick dependencies of the relocated element.  Artifacts and other metadata will be ignored.
  
  E, [2020-11-24T08:28:21.876609 #12106] ERROR -- : POM relocation to an other version number is not fully supported in Gradle : xml-apis:xml-apis:2.0.2 relocated to xml-apis:xml-apis:1.0.b2.
  
  FAILURE: Build failed with an exception.
  
  * What went wrong:
  A problem occurred configuring root project 'spring'.
  > Could not resolve all files for configuration ':classpath'.
     > Could not resolve com.beust:jcommander:1.35.
       Required by:
           project : > org.asciidoctor:asciidoctorj-pdf:1.5.0-alpha.16 > org.asciidoctor:asciidoctorj:1.5.6
        > Could not resolve com.beust:jcommander:1.35.
           > Could not get resource 'https://plugins.gradle.org/m2/com/beust/jcommander/1.35/jcommander-1.35.pom'.
              > Could not GET 'https://plugins.gradle.org/m2/com/beust/jcommander/1.35/jcommander-1.35.pom'.
                 > Read timed out
```

I'm wondering, why this didn't appear in other builds yet?
Looks like the same error in Azure clouds and incompatible TTL settings for pooled HTTP connections....

**Comment by adangel** [comment]
Rerun, now back at sourceforge failure:

```
  --2020-11-24 09:09:44--  https://master.dl.sourceforge.net/project/pmd/pmd-regression-tester/pmd_7.0.x-baseline.zip?viasf=1
  Resolving master.dl.sourceforge.net (master.dl.sourceforge.net)... 216.105.38.12
  Connecting to master.dl.sourceforge.net (master.dl.sourceforge.net)|216.105.38.12|:443... connected.
  HTTP request sent, awaiting response... 503 Service Unavailable
  2020-11-24 09:10:00 ERROR 503: Service Unavailable.
```

**Comment by oowekyala** [comment]
https://github.com/pmd/pmd/pull/2917/checks?check_run_id=1453031344#step:6:43193

> Running pmdtester failed: #<NoMethodError: undefined method `download_baseline' for #<Danger::Dangerfile:0x00005586ba34e8d8>>

Looks like it comes from [this line](https://github.com/pmd/pmd/blob/pmd/7.0.x/Dangerfile#L28) (or L44). Are these calls really needed? It looks like the baseline would be downloaded within the `Runner::run` call anyway

**Review by adangel — COMMENTED** [review]
> > Running pmdtester failed: #<NoMethodError: undefined method `download_baseline' for #Danger::Dangerfile:0x00005586ba34e8d8>
> 
> Looks like it comes from [this line](https://github.com/pmd/pmd/blob/pmd/7.0.x/Dangerfile#L28) (or L44). Are these calls really needed? It looks like the baseline would be downloaded within the `Runner::run` call anyway

I've fixed that already, probably forgot to delete these lines when merging (https://github.com/pmd/pmd/commit/ce999665b47f85a5325d75edc2f10bf036d46204)

I've pushed a small fixes commit to this PR, that should trigger the rebuild. The build of a PR happens always on a test merge commit that github automatically creates, so it should include the fix on pmd/7.0.x.

If then GH actions is happy and regression tester runs, I'll merge this PR.

**Comment by adangel** [comment]
> introduces 20 new violations
https://chunk.io/pmd/9325997603b34530a06bee6cd769917c/diff1/spring-framework/index.html

I wonder, where these come from. These are all comment rules, that have been updated with #2802 ...

**Comment by adangel** [comment]
> > introduces 20 new violations
> > https://chunk.io/pmd/9325997603b34530a06bee6cd769917c/diff1/spring-framework/index.html
> 
> I wonder, where these come from. These are all comment rules, that have been updated with #2802 ...

Ah... it's one specific file: ReactorNettyTcpStompClientTests.java - previously, we had a parser error (java.lang.IllegalStateException: Disambiguation pass should resolve everything except qualified ctor calls) which is now solved...

**Comment by oowekyala** [comment]
> Ah... it's one specific file: ReactorNettyTcpStompClientTests.java - previously, we had a parser error (java.lang.IllegalStateException: Disambiguation pass should resolve everything except qualified ctor calls) which is now solved...

I was thinking that we could add some detection of this into pmd/pmd-regression-tester. We already detect "changed" violations. There could be "lost" violations, those that were deleted because of an error, and "recovered" violations, those that appeared because some error disappeared

**Pull request merged**
