### PR TITLE
Some code enhancements

### PR DESCRIPTION
**Pull request by dionisioC**
**PMD** Splited the imports to avoid check style message: Using the '.*' form of import should be avoided - net.sourceforge.pmd.lang.*.

**AbstractNodeInfo** now has all the overrides

**StringUtils** now has the EMPTY_STRING variable declared as private and a getter method to access it. 
Refactored isSame to avoid using     @SuppressWarnings("PMD.CompareObjectsWithEquals")

**DFAPanel** now uses the getter for empty strings. Also deleted comments that seems to be old code and addd the override to valueChanged

In **DBMSMetadadataTest** we were passing a parameter to  System.out.format but it hasn't the place holder for the parameter

The second commit is just to replace tabs for spaces.

### CODE REVIEW

**Comment by dionisioC** [comment]
Two questions. 

- Is there any config file to automatically format the code in eclipse?
- Is the project still supporting java 6?

**Comment by dionisioC** [comment]
The build fails, but I am not sure why.

If I do mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V (like the build if I am correct) in my local machine builds. Please find attached the results

[result.txt](https://github.com/pmd/pmd/files/243856/result.txt)

**Comment by adangel** [comment]
Don't worry - the build on travis-ci fails because of "out of memory"...

About your question: There is no up-to-date version of the formatter. An old one is available at https://github.com/pmd/build-tools/blob/master/config/eclipse-code-formatter-settings.xml , however, it uses "mixed" indentation. Personally, I'd prefer to use spaces only... It's on my list to update this and also the checkstyle rules.

> Is the project still supporting java 6?
pmd/5.3.x is using java6 to compile, but it can analyze also java8 projects. The minimum required Java VM is 6.
pmd/5.4.x and later are using java7 - so the minimum required Java VM is 7. It can also analyze java8 projects.
master: Mostly using java7, but some modules (like pmd-apex, pmd-ui) are using java8. This means, PMD runs with java7. But to be able to analyze Salesforce.com Apex, you'll need to run PMD with a Java 8 runtime.

**Comment by adangel** [comment]
I've updated the code formatter settings and added a code template file:
* [code formatter](https://github.com/pmd/build-tools/blob/master/config/eclipse-code-formatter-settings.xml)
* [code templates](https://github.com/pmd/build-tools/blob/master/config/eclipse-codetemplates.xml)

I've slightly adjusted the [checkstyle rules](https://github.com/pmd/pmd/blob/master/pmd-core/etc/checkstyle-config.xml) regarding the tab usage. Checkstyle should be automatically active via maven (although it won't break the build).

**Pull request merged**
