### PR TITLE
[java] Implement rule NonSerializableClass

### LINKED ISSUE #1668: [java] BeanMembersShouldSerialize is extremely noisy
Rule doc: [BeanMembersShouldSerialize](https://pmd.github.io/latest/pmd_rules_java_errorprone.html#beanmembersshouldserialize)

This is more of a question but could be seen as documentation bug.
How does the `BeanMembersShouldSerialize` rule classify a class as bean or used by a bean?
I have a class that will never be serialized ever or someone did something horribly wrong.
I see that for some cases it makes sense to mark members as `transient` even if they do not implement `Serializable` as other serialization mechanisms like Gson could also take that modifier into account.
But from the description I don't see when this rule applies to a class and when not and why it is applied to my class which is actually used by no other code as it is meant to be used by consumers of my library.

### LINKED ISSUE #4176: [java] Rename BeanMembersShouldSerialize to NonSerializableClass
There are a two issues around the rule [BeanMembersShouldSerialize](https://pmd.github.io/latest/pmd_rules_java_errorprone.html#beanmembersshouldserialize):
* #403
* #1668 

The rule exists since PMD 1.1 but doesn't really check for serialization despite its name:

> The name of the rule is confusing too, since it's not checking that members should be serializable (which would be interesting on it's own), but rather if the getter / setters are in place. I suggest renaming this rule accordingly.

(https://github.com/pmd/pmd/issues/403#issuecomment-304306638)

I'm proposing the following changes:

1. Rename the rule to "NonSerializableClass" (still category "Error Prone")
2. Only consider classes, that are `java.io.Serializable`
3. Verify, that each member (= field) of the class is again serializable. This is effectively implementing SonarSource's rule https://rules.sonarsource.com/java/RSPEC-1948
4. Taking into account, that `transient` fields can be ignored
5. Don't look at getters or setters - this is something for a different rule that actually checks Java Beans conformity
6. Deprecate the property `prefix` - if a class is serializable, all members have to be serializable as well, regardless of their name

That way, we don't need to need to add a new property like #403 suggests.
And since we only consider serializable classes, the rule should be less noisy (#1668).

Note: BeanMembersShouldSerialize can be suppressed with `@SuppressWarnings("serial")`, which actually doesn't make sense, since the rule doesn't do serializability checks (originally implemented per request https://sourceforge.net/p/pmd/bugs/784/)

**Alternative**

We could actually just create a new rule "NonSerializableClass" and deprecate "BeanMembersShouldSerialize" entirely. While the implementation will be completely different, the original intention (serializability) is the same of both rules.
It probably makes not so much a difference, since the rule was probably not used at all because it's so noisy...

### PR DESCRIPTION
**Pull request by adangel**
## Related issues

- Fixes #4176 
- Fixes #1668 

Note: We still need a replacement for BeanMembersShouldSerialize, see #4177 

Not sure, whether we should deprecate BeanMembersShouldSerialize without replacements and just add NonSerializableClass as a _new_ rule. The diff shows, that the implementation is completely different...

## Ready?

- [x] Added unit tests for fixed bug/feature
- [x] Passing all unit tests
- [x] Complete build `./mvnw clean verify` passes (checked automatically by github actions)
- [x] Added (in-code) documentation (if needed)

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">Compared to master:<br />
This changeset changes 0 violations,<br />
introduces 75 new violations, 544 new errors and 0 new configuration errors,<br />
removes 19796 violations, 0 errors and 0 configuration errors.<br />
<a href="https://chunk.io/pmd/a9ef2426b69d4e78afc4745c0f4900b6/diff1/index.html">Full report</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by adangel** [comment]
Does this violation make sense? Wdyt?

https://github.com/spring-projects/spring-framework/tree/v5.3.13/spring-aop/src/main/java/org/springframework/aop/framework/AdvisedSupport.java#L90

AdvisedSupport is serializable. It has a field `interfaces` of type `java.util.List`. The List is a interface and it is itself not serializable. But the implementation used at runtime (e.g. at this specific line it is ArrayList) is serializable. So this is actually not a real problem, but just looking statically at the type of the field, we don't know, whether the value will be serializable or not at runtime.
We could make it optional to check this (e.g. by introducing a property `checkInterfaces`).


Regarding the other open point (whether to rename or deprecate the old rule BeanMembersShouldSerialize): The new rule creates significantly less violations, as it only considers serializable classes (only 232 violations vs. 19796). When we rename the rule, this helps anyone who has enabled BeanMembersShouldSerialize now, because most of the false-positive noise will be gone without changing the ruleset. However, maybe nobody has this rule enabled anyway atm? Then some change in the ruleset will be necessary either way: adding NonSerializableClass or removing the exclude for BeanMembersShouldSerialize. So I guess, it doesn't really matter.

**Comment by oowekyala** [comment]
> So this is actually not a real problem, but just looking statically at the type of the field, we don't know, whether the value will be serializable or not at runtime.

This problem is apparent in other violations, where no interface is involved. For instance here: https://github.com/openjdk/jdk/blob/jdk-11%2B28/src/java.base/share/classes/java/util/AbstractMap.java#L609

While the rule is technically right, it would be very restrictive to require the type parameters to be serializable when the serialization feature might never be used...

I think the rule is "more probably" right (true positive) when the field type is a non-abstract class. When it's an interface or abstract class or a type parameter, maybe we should skip it conservatively (with a property). If we could, it would be nice to allow reporting these with a lower priority.

**Comment by adangel** [comment]
I've added the property "checkAbstractTypes" now.

There is one more special case: the private static final field `serialPersistentFields` - if this is not defined, then all non-static and non-transient fields must be serializable. Otherwise, only the fields that are defined here, need to be serializable.

That means, that all violations in java.io.ObjectStreamClass (e.g. https://github.com/openjdk/jdk/blob/jdk-11%2B28/src/java.base/share/classes/java/io/ObjectStreamClass.java#L166) are false-positives, because this class defines actually no serializable fields: https://github.com/openjdk/jdk/blob/jdk-11%2B28/src/java.base/share/classes/java/io/ObjectStreamClass.java#L88-L89

This behavior is described here: https://docs.oracle.com/en/java/javase/19/docs/specs/serialization/serial-arch.html#defining-serializable-fields-for-a-class

**Pull request merged**
