### PR TITLE
[core] Support NoAttribute for XPath

### PR DESCRIPTION
**Pull request by adangel**
* This PR is for PMD 7.
* It's extracted from #1759 

Changes:
* Adds the `@net.sourceforge.pmd.lang.ast.xpath.NoAttribute` annotation
* With that, you can annotate getters in AST nodes, that should not be exposed as XPath attributes and thus cannot be used for xpath expressions/queries.
* The annotation can also be applied to the whole AST class - then all methods are not exposed.

Todo:
* This feature needs to be documented somewhere... it seems to be part of the AST API -> https://github.com/pmd/pmd/wiki/PMD-7.0.0-API
* We need to add a unit test

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">No java rules are changed!</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by oowekyala** [comment]
I added some unit tests. I also changed a bit the contract of `@NoAttribute`:
* Attributes from  Node and AbstractNode are never suppressed.  I don't know what might go wrong if we do suppress them.
* The scope INHERITED suppresses the attributes inherited from supertypes 
* The scope ALL suppresses the attributes defined in the class + INHERITED
* In any case, if an attribute accessor is overridden in a concrete class *C*, then it is only suppressed if either 
  1. the accessor has its own NoAttribute annotation
  1. *C* has a `@NoAttribute(scope = ALL)`.

This last point means that if you can override the method, then you can expose it as an attribute again.

**Comment by jsotuyod** [comment]
@oowekyala anything holding this from being merged?

**Comment by oowekyala** [comment]
@jsotuyod nope, i might have forgotten about it

**Pull request merged**
