### PR TITLE
[java] Update UnusedPrivateFieldRule - ignore any annotations

### LINKED ISSUE #4033: [java] UnusedPrivateField - false positive with Lombok @ToString.Include
**Affects PMD Version:LATEST** 

**Rule:UnusedPrivateField**

Please provide the rule name and a link to the rule documentation:
<https://pmd.github.io/latest/pmd_rules_java_bestpractices.html#unusedprivatefield>

**Description:**
Hi, I found a false positive about the rule UnusedPrivateField, please read the following code example. @ToString is from lombok library [Link](https://projectlombok.org/features/ToString), and it can generate a `toString` method to use the private field. Its similar annotations in lombok have been considered. Hence, I think we should consider this annotation.

I think we can add one more line `lombok.ToString.Include` in method `defaultSuppressionAnnotations` of [UnusedPrivateFieldRule](https://github.com/pmd/pmd/blob/master/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/UnusedPrivateFieldRule.java) 😄 

**Code Sample demonstrating the issue:**
```java
@ToString
public class C {
    @ToString.Include
    private int a;  // Should not report a warning in this line
}
```

**Expected outcome:**
PMD should not report a violation at line 4, but doesn't. This is a false-positive.

**Running PMD through:** *[Maven]*

### LINKED ISSUE #4037: A false positive about the rule UnusedPrivateField
**Affects PMD Version:6.47.0** 

**Rule:UnusedPrivateField**

Please provide the rule name and a link to the rule documentation:
<https://pmd.github.io/latest/pmd_rules_java_bestpractices.html#unusedprivatefield>

**Description:**
Hi, I found a false negative about the rule UnusedPrivateField, please read the following code example. In line 3, the code has an annotation `@SpyBean`, which means that the filed `service` could be used in testing. However, PMD reports a warning of this rule.

Besides, in [src file](https://github.com/pmd/pmd/blob/master/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/UnusedPrivateFieldRule.java), PMD has considered `@MockBen`, and it doesn't report identical warning for the field with `MockBean`. Hence, I think this is a false positive.

**Code Sample demonstrating the issue:**

```java
import org.springframework.boot.test.mock.mockito.SpyBean;
public class C {
    @SpyBean
    private Service service;  // a false warning of this field
}
```

**Expected outcome:**

PMD reports a violation at line 4, but that's wrong. That's a false positive.

**Running PMD through:** *[Maven]*

### PR DESCRIPTION
**Pull request by LynnBroe**
## Describe the PR

I improve the rule UnusedPrivatefield and make the annotation @SpyBean can be detected

## Related issues

- Fixes #4033 
- Fixes #4037

## Ready?

- [x] Added unit tests for fixed bug/feature
- [x] Passing all unit tests
- [x] Complete build `./mvnw clean verify` passes (checked automatically by github actions)
- [ ] Added (in-code) documentation (if needed)

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">Compared to master:<br />
This changeset changes 0 violations,<br />
introduces 15 new violations, 0 new errors and 0 new configuration errors,<br />
removes 0 violations, 0 errors and 0 configuration errors.<br />
<a href="https://chunk.io/pmd/703ea4a953684b0d880920568e1a40a1/diff1/index.html">Full report</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by adangel — CHANGES_REQUESTED** [review]
Thanks for your PR!

Please add a new test case to prove that #4037 is indeed fixed.

However, I think it's time to test another strategy for fixing these issues: Please try out what happens, if this rule just doesn't report any private fields, that has any annotations.
Because otherwise, we will keep adding one annotation after another, until every java framework is represented in this rule.
If this new strategy works and doesn't create too many false positives, then we would also have a fix for #4033 (and possible other issues).

**Comment by LynnBroe** [comment]
Hi, adangel, I have added the test case, could you please help check it? Besides, I think it is inappropriate to dismiss all fields with annotations because many annotations may do not affect the current rule under checking. Fixing these issues is very easy, but dismissing them could lead to many false negatives. Thanks

**Comment by adangel** [comment]
Thanks for the updated test case.

> Besides, I think it is inappropriate to dismiss all fields with annotations because many annotations may do not affect the current rule under checking. Fixing these issues is very easy, but dismissing them could lead to many false negatives. Thanks

That's why I wanted to try this out to see the impact. I just did it - see the last regression tester report. It's not too bad IMHO.

Static code analysis always needs to balance false positives and false negatives. In that case - the rule is in category "best practices" - there is no big harm in having some false negatives (no program will crash because of an unused private field). Therefore I believe it is more important to reduce false positives than to avoid any false negatives. If the rule is too noisy it may lead to being ignored or disabled and maybe even removed from the ruleset entirely. In the end, the rule might not be used at all anymore.

I decided to deprecate the property "ignoreAnnotations". If there are good examples for false negatives, we might think of adding a new property to change the behavior, to deal with some annotations in a special way (e.g. "reportForAnnotations") or have a boolean flag (e.g. "reportRegardlessOfAnnotations"=true) which could be enabled if needed and would report all unused private fields whether annotated or not.

Having a more general solution also has the positive side effect, that #4033 is also fixed now.

**Review by adangel — APPROVED** [review]

**Pull request merged**
