### PR TITLE
[java] Improve DoNotCallSystemExit (Fixes #2157)

### LINKED ISSUE #2157: [java] Improve DoNotCallSystemExit: permit call in main(), flag System.halt
**Affects PMD Version:** 
6.20.0.

**Rule:**
[DoNotCallSystemExit](https://pmd.github.io/latest/pmd_rules_java_errorprone.html#donotcallsystemexit)

**Description:**
This rule must make an exception if the exit methods are called from main(). This rule could add a property to dissuade System.exit() being called from any method other than main().

```java

package pmdtests;

import java.util.concurrent.ThreadLocalRandom;

public final class ThrowSwitch {

  private ThrowSwitch() {
    throw new IllegalStateException("Private constructor");
  }

  @SuppressWarnings({"fallthrough", "PMD.MissingBreakInSwitch"})
  public static void main(String... args) {
    int errCode = getSimulatedErrorCode();

    switch (errCode) {
      case 1:
      case 2:
      case 3:
      case 4:
      case 5:
        throw new AssertionError("Error code: " + errCode);
      default:
        System.exit(1);
    }
  }

  public static int getSimulatedErrorCode() {
    return ThreadLocalRandom.current().nextInt(0, 6);
  }

private static void anotherExit() {
System.exit(1);
}
}
```

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]*

### PR DESCRIPTION
**Pull request by mvitaly**
## Describe the PR

System.exit() and its equivalents should be allowed in static main() methods, added check for Runtime.getRuntime().halt()

## Related issues

- Fixes #2157 

## Ready?

- [x] Added unit tests for fixed bug/feature
- [x] Passing all unit tests
- [ ] Complete build `./mvnw clean verify` passes (checked automatically by travis)
- [ ] Added (in-code) documentation (if needed)

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">This changeset introduces 0 new violations, 0 new errors and 0 new configuration errors,<br />
removes 5 violations, 0 errors and 2 configuration errors.<br />
<a href="https://chunk.io/pmd/c9d631b89c084c54a75be3d40d98c178/diff/index.html">Full report</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by mvitaly** [comment]
I think it will skip System.exit() in constructors

**Comment by mvitaly** [comment]
Fixed the detection in constructors

**Review by adangel — CHANGES_REQUESTED** [review]
Thanks for the PR!
Please add additional test cases to https://github.com/pmd/pmd/blob/master/pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/DoNotCallSystemExit.xml
See https://pmd.github.io/latest/pmd_userdocs_extending_testing.html for the explanation.

**Comment by mvitaly** [comment]
@adangel added tests

**Review by adangel — APPROVED** [review]
Thanks, looks good!

**Pull request merged**
