### PR TITLE
[doc] Improve deadlink detection

### PR DESCRIPTION
**Pull request by jsotuyod**
- Do a HEAD request instead of a GET
 - Some minor code simplifications

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">No java rules are changed!</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by adangel** [comment]
> Since checking external links is fast enough, maybe we can enable it in the build? I don't know whether travis would allow us to make http requests though. Wdyt?

I've not tested it yet - but we should only enable it, if it works behind a corporate proxy server (that is a http(s) proxy with authentication). Otherwise the build might stall and fail.

Alternatively we could enable it only on travis?

**Comment by kris-scheibe** [comment]
@oowekyala I think if we enable checking the links for every build, we should at least not fail the build by default if some of them appear to be dead. 

Otherwise the build will fail randomly if a page is temporarily offline or if the IP gets blacklisted due to too many automated requests (this happened to me occasionally, when did multiple runs of the link checker in a short time).

**Comment by oowekyala** [comment]
> Alternatively we could enable it only on travis?

Yeah that seems ok, but @kris-scheibe is also right that we might get a failing build because of a page suddenly being down, completely unrelated to the latest code changes. But not failing the build means we probably won't see the warning. Maybe then, we should only enable it on release builds, failing for any dead link?

**Pull request merged**
