### PR TITLE
[apex] Adding XSS detection to return statements

### PR DESCRIPTION
**Pull request by sgorbaty**
Hey @jsotuyod!

This PR contains:
- NPE bug fix
- Detection of potential XSS in return statements.

Cheers,
Sergey

### CODE REVIEW

**Comment by up2go-rsoesemann** [comment]
@adangel and @jsotuyod We would like to get many more Apex rules into PMD 5.5.3. When is your planned release date?

@sgorbaty

**Comment by jsotuyod** [comment]
5.6.0 is definitely not ready, but has made some progress over November.

As for the release plans, @adangel is the one to ask. Right now the process is still manual and therefore limited by his time availability. We are discussing automating it to help define a more predictable release schedule (I personally favor the once-a-month approach for support releases), but until then...

In the meantime, I'd suggest you guys just keep submitting all you are able to produce. If it doesn't make it to 5.5.3 it will definitely do to 5.5.4 or 5.5.5; but the sooner you can submit a PR, the earlier it will get released.

**Comment by jsotuyod** [comment]
This is merged and will be included as part of pmd 5.5.3

**Comment by adangel** [comment]
@up2go-rsoesemann @jsotuyod 
Hi Robert, I probably won't do a release before the holidays. The next release will be probably mid-January. The release will then contain whatever is on 5.4.x and 5.5.x. Whether it makes sense to release already 5.6.0 with what we have now on master, we'll have to decide then.

**Pull request merged**
