### PR TITLE
[java] Update rule AssignmentToNonFinalStatic

### PR DESCRIPTION
**Pull request by adangel**
Part of #2701

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          2 Messages
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">Compared to pmd/7.0.x:<br />
This changeset changes 0 violations,<br />
introduces 886 new violations, 0 new errors and 0 new configuration errors,<br />
removes 0 violations, 0 errors and 0 configuration errors.<br />
<a href="https://chunk.io/pmd/df93d385dfba43d8809f03da6acb6ac4/diff1/index.html">Full report</a></td>
    </tr>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">Compared to master:<br />
This changeset changes 31211 violations,<br />
introduces 22146 new violations, 1 new errors and 0 new configuration errors,<br />
removes 135721 violations, 8 errors and 3 configuration errors.<br />
<a href="https://chunk.io/pmd/df93d385dfba43d8809f03da6acb6ac4/diff2/index.html">Full report</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by adangel** [comment]
A lot of new false positives. The rule should only consider assignment to non final static fields, that occur in constructors. If there is a method, e.g. https://github.com/checkstyle/checkstyle/tree/checkstyle-8.10/src/it/java/com/google/checkstyle/test/chapter5naming/rule528typevariablenames/MethodTypeParameterNameTest.java#L41
This can be considered a legitimate case. That's at least, how this rule works on PMD 6.

**Comment by adangel** [comment]
Most false positives are fixed now. 

There is one confusing thing left:

a) https://github.com/openjdk/jdk/tree/jdk-11+28/src/java.base/share/classes/com/sun/java/util/jar/pack/BandStructure.java#L375

```java
this.seqForDebug = ++nextSeqForDebug;
```

but `seqForDebug` is not a static field..., but `nextSeqForDebug` is...

Similar case: https://github.com/spring-projects/spring-framework/tree/v5.0.6.RELEASE/spring-test/src/main/java/org/springframework/mock/web/MockHttpSession.java#L95

```java
this.id = (id != null ? id : Integer.toString(nextId++));
```

`id` is not static, but `nextId` - maybe we can improve the message and say, which varId is the culprit?

**Comment by adangel** [comment]
Ok, so the message is now more helpfull. I'm going to merge this.

**Pull request merged**
