### PR TITLE
[java] Show more detailed message when can't resolve field type

### PR DESCRIPTION
**Pull request by andrey-fomin**
Before submitting a PR, please check that:
 - [x] The PR is submitted against `master`. The PMD team will merge back to support branches as needed.
 - [x] `./mvnw clean verify` passes. This will [build](https://github.com/pmd/pmd/blob/master/BUILDING.md) and test PMD, execute PMD and checkstyle rules. [Check this for more info](https://github.com/pmd/pmd/blob/master/CONTRIBUTING.md#code-style)

**PR Description:**

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">This changeset introduces 0 new violations, 0 new errors and 0 new configuration errors,<br />
removes 0 violations, 0 errors and 0 configuration errors.<br />
<a href="https://chunk.io/pmd/6189fb08d05d4bd5bb8066ab9b3fc91c/diff/index.html">Full report</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by jsotuyod** [comment]
@andrey-fomin this looks good! thank for the PR! Can't help but wonder… what were you working on that you needed this?

**Comment by andrey-fomin** [comment]
@jsotuyod, I have classpath where not all transient dependencies are available. It causes messages like `Error during type resolution due to: java.lang.NoClassDefFoundError: some/class/Here`. In most cases I want to remove incomplete dependency so my change simplifies finding class usages.

**Comment by jsotuyod** [comment]
@andrey-fomin ok. I hope we can resume #1371 some time soon then

**Comment by jsotuyod** [comment]
Merged! Will be part of PMD 6.14.0

**Pull request merged**
