### PR TITLE
Small code enhancements, basically reordering variable declarations, …

### PR DESCRIPTION
**Pull request by dionisioC**
…constructors and variable modifiers

Enhancements based on sonar advices. I tried to start for the important ones, but those are going to take more time and needs more knowledge about the project. This ones are mainly reordering the code, so first we have variables, after the variables the constructors, and after the constructors the methods.

Also some declarations have been reordered, for example instead of having

private final static

Now we have 

private static final

Trying yo give consistency

I haven't touched classes with comments like this (AbstractPLSQLNode.java)

/* JavaCC - OriginalChecksum=3f651517d5069f856891d89230562ac4 (do not edit this line) */

I am not sure what does that mean, and I was afraid that If I change something there, that could be broken

### CODE REVIEW

**Comment by adangel** [comment]
Thanks!

**Comment by dionisioC** [comment]
Do we know how ofter sonar is executed?

**Comment by adangel** [comment]
Do you mean this: https://nemo.sonarqube.org/overview?id=393826 ?
I have no idea, because I didn't set this up... I can try to get access to it, but might take a while...

**Comment by dionisioC** [comment]
Yes. Seems to be triggered when a new release comes out. It is not important, it just help to summarise the code status, so it is easier to pick thing to improve

**Pull request merged**
