### PR TITLE
[java] Update rule NullAssignment

### LINKED ISSUE #1669: [java] NullAssignment - FP with ternay and null as constructor argument
**Affects PMD Version:** *6.11.0*
**Rule:** [NullAssignment](https://pmd.github.io/latest/pmd_rules_java_errorprone.html#nullassignment)
**Description:**
Should below code really trigger the `NullAssignment` rule?
Of course I could write `"null"` instead of `null` but why should this be worse than wasting a string constant pool place?
**Code Sample demonstrating the issue:**

```java
throw new IllegalArgumentException(String.format(
        "Unsupported client with class '%s' given",
        (discordClient == null) ? null : discordClient.getClass()));
```

**Running PMD through:** *Gradle*

### LINKED ISSUE #2320: [java] NullAssignment - FP with ternary and null as method argument
**Affects PMD Version:** 
6.20

**Rule:** [NullAssignment](https://pmd.github.io/latest/pmd_rules_java_errorprone.html#nullassignment)
**Description:**

**Code Sample demonstrating the issue:**

```java
public String methodOne(String one, String two) {
        return "test";
    }
public String methodTwo(String one, String two) {
        List<String> strings = new ArrayList<>();
->>        return methodOne("one", strings.isEmpty() ? null : "two");
    }
```

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]*
Programmatically

### PR DESCRIPTION
**Pull request by adangel**
Part of #2701 

- Fixes #2320
- Fixes #1669
- Not addressed by this PR is #1050.

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          2 Messages
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">Compared to pmd/7.0.x:<br />
This changeset changes 0 violations,<br />
introduces 2163 new violations, 0 new errors and 0 new configuration errors,<br />
removes 0 violations, 0 errors and 0 configuration errors.<br />
<a href="https://chunk.io/pmd/154104a26fa34e5fb12478bbff27b7e8/diff1/index.html">Full report</a></td>
    </tr>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">Compared to master:<br />
This changeset changes 45900 violations,<br />
introduces 25761 new violations, 38 new errors and 0 new configuration errors,<br />
removes 180011 violations, 28 errors and 3 configuration errors.<br />
<a href="https://chunk.io/pmd/154104a26fa34e5fb12478bbff27b7e8/diff2/index.html">Full report</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by adangel** [comment]
**False negatives:**

a) https://github.com/checkstyle/checkstyle/tree/checkstyle-9.1/src/it/resources/org/checkstyle/suppressionxpathfilter/avoidinlineconditionals/SuppressionXpathRegressionAvoidInlineConditionalsAssign.java#L7

```
b = (a == null || a.length() < 1) ? null : a.substring(1); // warn
```

similar case, with one more parens: https://github.com/openjdk/jdk/tree/jdk-11+28/src/java.base/share/classes/com/sun/crypto/provider/GaloisCounterMode.java#L224

```
        aadBufferSave =
            ((aadBuffer == null || aadBuffer.size() == 0)?
             null : aadBuffer.toByteArray());
```

b) https://github.com/checkstyle/checkstyle/tree/checkstyle-9.1/src/main/java/com/puppycrawl/tools/checkstyle/api/Violation.java#L136 

```
this.args = null;
```

Maybe not? args is final - and this is the first assignment - could be considered as part of the declaration, which is explicitly allowed by the rule.


**False positives:**

a) https://github.com/checkstyle/checkstyle/tree/checkstyle-9.1/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/HiddenFieldCheck.java#L461

```
frameName = null;
```

frameName is final - see fn b) above.

b) https://github.com/openjdk/jdk/blob/jdk-11%2B28/src/java.base/share/classes/java/io/ObjectInputStream.java#L2017

```
int enumHandle = handles.assign(unshared ? unsharedMarker : null);
```

That's definitely a false positive: null is not assigned to enumHandle, it is a method argument...

**Correct cases - fixed false negatives:**

a) https://github.com/spring-projects/spring-framework/blob/v5.3.13/spring-web/src/main/java/org/springframework/http/codec/support/ClientDefaultCodecsImpl.java#L95

```
		Decoder<?> decoder = (this.sseDecoder != null ? this.sseDecoder :
				jackson2Present ? getJackson2JsonDecoder() :
				kotlinSerializationJsonPresent ? getKotlinSerializationJsonDecoder() :
				null);
```

This is now correctly detected - even though this is a long ternary... but eventually null could be assigned here.

**Comment by adangel** [comment]
False negatives and positives should be fixed now, but we'll get a new false negative for the corrected case (nested ternaries) - see the disabled test case.

**Comment by oowekyala** [comment]
I think I'll merge this.. In the long term I think this rule should be deprecated though. Its justification is really bad:

> Sometimes, this type of assignment is an indication that the programmer doesn't completely understand what is going on in the code.

This is completely unverifiable. The message is even worse:

> Assigning an Object to null is a code smell. Consider refactoring.

`null` is not more dangerous when assigned into a variable than in other places, so the rule really has no reason to exist. 
Using data flow analysis we should try to detect possible NPEs in a useful manner, not just blindly flag all `null` literals in the program.

**Pull request merged**
