### PR TITLE
[apex] Make Rule suppression work

### PR DESCRIPTION
**Pull request by up2go-rsoesemann**
Before submitting a PR, please check that:
 - [x] The PR is submitted against `master`. The PMD team will merge back to support branches as needed.
 - [x] `mvn test` passes.
 - [ ] `mvn checkstyle:check` passes. [Check this for more info](https://github.com/pmd/pmd/blob/master/CONTRIBUTING.md#code-style)

**PR Description:**
Enables PMD-like rule suppression for the Apex language and by that implements https://github.com/pmd/pmd/issues/265.

Not all suppression variations from Java could be ported due to the limitations of the current Apex parser to recognize undefined Annotation parameters.

Those will work on _classes_, _interfaces_, _member_ and _method variables_, _methods_ and _method parameters_:
- `@SupressWarnings('PMD')` to supress all Apex rules
- `@SupressWarnings('all')` to supress all Apex rules
- `@SupressWarnings('PMD.ARuleName')` to supress only the rule named ARuleName
- `@SupressWarnings('PMD.ARuleName, PMD.AnotherRuleName')` to supress only the rule named ARuleName or AnotherRuleName

### CODE REVIEW

**Comment by up2go-rsoesemann** [comment]
@jsotuyod I could get checkstyle installed on my eclipse. So there are Checkstyle errors left. Maybe you can reformat my code.

**Comment by jsotuyod** [comment]
@up2go-rsoesemann amazing! As for the checkstyle fixes, I may look into it myself, don't worry.

I do worry about the proposed grammar for the last case (multiple rules), as it's slightly different from what we have in Java, which is `@SuppressWarnings({"PMD.RuleA", "PMD.RuleB"})`. I believe Apex supports this syntax (I may be wrong), but if possible, I'd prefer being consistent across languages to make it easier on users and keep our manual simple (imagine an Apex developer looking for suppressing warnings in PMD, reaches a stackoverflow post concerning the same, but on Java, and the proposed solution doesn't work for them).

**Comment by up2go-rsoesemann** [comment]
@jsotuyod I agree with your goal but this is simply not possible in Apex. As the screenshot shows this syntax is not accepted by our parser. None of the Java variants. As we need a way to suppress multiple rules this was the closest I came up with that DOES parse.

bildschirmfoto 2017-03-07 um 09 55 05

**Comment by jsotuyod** [comment]
@up2go-rsoesemann too bad. Ok, I think we will have to bare with this and be extra cautious on the documentation on the site.

@adangel at some point it may even make sense to move out some of the common pages from the web (such as suppression), and have it as a per-language page. We should have a checkpoint on the efforts on the new website by Joseph Allen.

**Comment by up2go-rsoesemann** [comment]
@jsotuyod I think there is no need to extensivly document that. PMD user know that not all features that work for Java work in their language. Most languages not even support Annotations.

So I hope this will not slow down merging.

**Comment by jsotuyod** [comment]
@up2go-rsoesemann it won't stop merging, don't worry. As soon as I can I'll pick this up, fix the outstanding checkstyle issues and merge.

**Comment by jsotuyod** [comment]
@up2go-rsoesemann merged! It will be released in PMD 5.6.0. Sorry it took me so long, it's been a hell of a week.

**Comment by up2go-rsoesemann** [comment]
@jsotuyod do you already have a release date?

**Comment by jsotuyod** [comment]
@up2go-rsoesemann nothing set in stone, but should be soon. We do have a shortlist of things to get done before release, such as getting the pending PRs such as this one and #289; and there is not much left right now.

We should merge #293, fix #282 (just submitted a PR), implementing #241 (generalization from the current `UnnecessaryLocalBeforeReturn` rule), doing [#1513](https://sourceforge.net/p/pmd/bugs/1513/) (really easy) and finally, 
renaming `java-unusedcode/UnusedModifier` to `java-unnecessary/UnnecessaryModifier`(easy)...

I don't think there are any other pending issues / tasks that couldn't wait for 5.6.1 / 5.7.0 eventually.

**Comment by sgorbaty** [comment]
@jsotuyod @up2go-rsoesemann Is ```@SuppressWarnings``` the only annotation we need at this point? Do you anticipate the need for another annotation in the future?

**Comment by jsotuyod** [comment]
@sgorbaty @up2go-rsoesemann I think so, yes. Do you feel otherwise?

**Comment by up2go-rsoesemann** [comment]
I just talked to Salesforce and they kindly asked to not move this PR into PMD because it introduced a hard to cope with technical dependency into their compiler. They work on a new compiler where this (currently accidentally unsupported) annotation will be officially supported.

This might take a while but we will then be able to use the annotation with less hacks.

@jsotuyod is there a way for you to simply revert my changes or how can I undo this?

FYI: @sgorbaty

**Comment by jsotuyod** [comment]
@up2go-rsoesemann  I can always rever the merge commit, no issue.

Do they have a timeframe for this? I fear that Jorje does not expose comments to us, and without neither that or this PR there is absolutely no support for suppressions on Apex.

**Comment by jsotuyod** [comment]
@up2go-rsoesemann I'd love to see parser support to recover comments / whitespace on-demand (just like JavaCC's special tokens and Antlr's hidden tokens / channels), since that would be really useful when implementing autofixable issues / adding suppression support through comments for both PMD and CPD.

**Comment by jsotuyod** [comment]
Changes have been reverted on 63ea1906afacc108871bb42c8e98d1e684df58c8, to be reverted again once this gets a green light from the people at Salesforce.

**Comment by up2go-rsoesemann** [comment]
@jsotuyod I finally got the go from Salesforce to move this back in. They now officially support this Annotation.

Is there a way for you to just reopen and merge in this PR? Or do I have to manually readd the changes.

**Comment by up2go-rsoesemann** [comment]
Besides that I also asked the Salesforce.com guys if there annotation now support parameters like the Java counterpart so we don't have to use the hacks the we discussed in this thread.

**Comment by jsotuyod** [comment]
@up2go-rsoesemann I can revert the revert commit, no issue there. If the old hack is no longer needed, we may open a PR updating the feature.

**Comment by up2go-rsoesemann** [comment]
Yes please revert the PR. According to Salesforce only "only a single string parameter is supported within quotes, you could comma separate them in the parameter and parse them out in your tool. "

😞

**Comment by jsotuyod** [comment]
This was re-reverted on d5a83ae807299bbe0b475663f5b513873b802f8b, will be part of PMD 6.0.0

**Comment by up2go-rsoesemann** [comment]
Thanks! When will 6.0 be released?

**Comment by jsotuyod** [comment]
@up2go-rsoesemann no hard date set, but hopefully soon. We did great progress so far, but there are a couple of big things still left to do (specially the rule reorg). You can follow our progress [here](https://github.com/pmd/pmd/milestone/12)

**Pull request merged**
