### PR TITLE
[java] issue983 Add new UnnecessaryAnnotationValueElement rule

### LINKED ISSUE #983: [java] Detect annotations with single value element
The Java standard for annotations states that if the only element used in the annotation is value, then an explicit value element is not required.

This rule will find annotations where the only element used is value and flag it as a violation, if the value element is explicit.

**Rule:** UnnecessaryAnnotationValueElementRule

**Description:** 
Avoid the use of value in annotations when it's the only element.

**Example:**

```
@TestClassAnnotation(value = "TEST")
public class Foo {

    @TestMemberAnnotation(value = "TEST")
    private String y;

    @TestMethodAnnotation(value = "TEST")
    public void bar() {
        int x = 42;
        return;
    }
}
```

**Becomes:**
```
@TestClassAnnotation("TEST")
public class Foo {

    @TestMemberAnnotation("TEST")
    private String y;

    @TestMethodAnnotation("TEST")
    public void bar() {
        int x = 42;
        return;
    }
}
```

### PR DESCRIPTION
**Pull request by clem0110**
Fixes #983 

New rule to detect when the value element is the only element in the annotation

### CODE REVIEW

**Comment by jsotuyod** [comment]
@clem0110 thanks for the contribution! This looks outstanding!

The rule however is a good match for the rulechain. Consider:
1. Adding a constructor to the rule, simply calling super + `addRuleChainVisit(ASTAnnotation.class);` (or something similar, I'm writing this off the top of my head)
2. On the `visit(ASTAnnotation node, Object data)` simply return `data` without calling super

 That way tree transversal is minimized and performance improved.

**Comment by clem0110** [comment]
@jsotuyod I updated the rule to to use the chain visit pattern.  I used UnusedLocalVariableRule as kind of the template for how to implement it.  Let me know if it needs anything else.

**Comment by jsotuyod** [comment]
It looks great! As soon as I am with thr computer I'll merge this.

**Comment by clem0110** [comment]
Cool.  Thanks.

**Comment by jsotuyod** [comment]
@clem0110 this will be part of PMD 6.2, congratulations!

**Pull request merged**
