### PR TITLE
[swift] Support Swift 4 grammar

### LINKED ISSUE #678: [swift][cpd] Exception when running for Swift 4 code (KeyPath)
`cpd` stopped working after I migrated the source code to Swift 4.

*The problem*: `pmd cpd` quits with an exception.

A full command showcasing the problem:
`pmd cpd --language swift --minimum-tokens 50 --files source.swift`

Result of running the command above:
```
net.sourceforge.pmd.lang.ast.TokenMgrError: Lexical error in file <path to file> at line 62, column 60.  Encountered: token recognition error at: '\.'
	at net.sourceforge.pmd.cpd.SwiftTokenizer.tokenize(SwiftTokenizer.java:48)
	at net.sourceforge.pmd.cpd.CPD.addAndThrowLexicalError(CPD.java:142)
	at net.sourceforge.pmd.cpd.CPD.add(CPD.java:137)
	at net.sourceforge.pmd.cpd.CPD.add(CPD.java:107)
	at net.sourceforge.pmd.cpd.CPD.add(CPD.java:69)
	at net.sourceforge.pmd.cpd.CPD.addDirectory(CPD.java:79)
	at net.sourceforge.pmd.cpd.CPD.addRecursively(CPD.java:64)
	at net.sourceforge.pmd.cpd.CPDCommandLineInterface.addSourcesFilesToCPD(CPDCommandLineInterface.java:125)
	at net.sourceforge.pmd.cpd.CPDCommandLineInterface.addSourceFilesToCPD(CPDCommandLineInterface.java:105)
	at net.sourceforge.pmd.cpd.CPDCommandLineInterface.main(CPDCommandLineInterface.java:83)
	at net.sourceforge.pmd.cpd.CPD.main(CPD.java:177)
```

The line of code for which `cpd` throws an exception is:
```
let observation = scrollView.observe(\.contentOffset, options: .new) { [weak self] (scrollView, _) in
```
Aparently `cpd` cannot handle the [new Swift 4 syntax](http://skyefreeman.io/programming/2017/06/28/kvo-in-ios11.html) for KeyPath, which is **\\.**

### PR DESCRIPTION
**Pull request by kenji21**
Here is the PR for Swift 4 support
Resolves #678

### CODE REVIEW

**Comment by jsotuyod** [comment]
The grammar seems to be backwards compatible (that is, new things were added, but nothing "grammatically" valid on the previous version is invalid now, so this should be safe for merging.

Support for versions of the grammar is unneeded as this is still a CPD-only language.

**Comment by jsotuyod** [comment]
I've re-reviewed the grammar and found some breaking changes I missed on my first review.

In particular I found two changes (there may be more I missed):
1. the keywords `__FILE__`, `__LINE__`, `__COLUMN__` and `__FUNCTION__` have been replaced by `#file`, `#line`, `#column`, `#function`
2. the traditional for loop has been removed, only for-in is supported now, using the range operators for an equivalent behavior

This means we either drop support for old Swift versions completely, or we reintroduce these along Swift versions and proper guards on usage of features for different versions. This last option being more costly, as I have little idea of Swift grammar other than reading the Antlr definition. Any input on this?

/cc @adangel

**Comment by kenji21** [comment]
For information, theses #line/#file appeared in swift 2.2 : https://swift.org/blog/swift-2-2-new-features/

**Comment by jsotuyod** [comment]
@kenji21 interesting, so these broke in Swift 3... I guess having version support on this will be harder than anticipated...

**Comment by kenji21** [comment]
Updated PR for swift 4.1, as there is now `#if canImport(ModuleName)` and `#if targetEnvironment(simulator)`

https://swift.org/blog/swift-4-1-released/
https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/Statements.html#//apple_ref/doc/uid/TP40014097-CH33-ID539

**Comment by jsotuyod** [comment]
@kenji21 thanks! I remain to figure out how to add proper version guards on Antlr. Otherwise, merging this before PMD 7.0.0 would be a breaking change for active users...

On the other hand, given the immaturity of Swift and the inability to merge libraries written in different versions, I have a strong intention of just moving towards latest versions....

**Comment by kenji21** [comment]
We mainly use pmd copy paste detector, and our CI jobs was failing (due to cpd failing) when encountering a swift 4 keyPath syntax, which leads me to this PR
We often update Xcode the day it is shipped by Apple (and sometimes before using betas), and Xcode embed a tool to help 2 -> 3 -> 4 migrations (Edit -> convert -> To current swift syntax) in parallel with compiler warnings
I don't know what active users are doing, maybe a "benchmark" of the [top ten swift project](https://github.com/topics/swift?l=swift&o=desc&s=stars) could be useful to see if grammar is better, maybe I could write a simple shell script to show this

**Comment by jsotuyod** [comment]
@adangel what do you think? @oowekyala what about you?

**Comment by jsotuyod** [comment]
Nevermind, the checklist was outdated. Later commits (and comments) added the support and test samples. This is awesome.

**Comment by kenji21** [comment]
👍🏻

The best test is still to run cpd on "top swift projects" like RxSwift / Alamofire which often updates to latest swift very quickly (but too hard to have in some unit/integration tests)

**Pull request merged**
