### PR TITLE
[plsql] Fixed issue with missing optional table alias in MERGE usage

### PR DESCRIPTION
**Pull request by duursma**
## Describe the PR
The newly introduced MERGE support didn't handle the case in which the table alias was missing as the next keyword was
accepted as being the alias.

## Related issues

- Fixes #
Added a LOOKAHEAD checking whether the found alias is not the expect keyword following the optional alias.
And added test-code which would break in the original version.

- redoes the changes from #5086, as those changes were removed by #5087 and #5088 and didn't end up in the master branch.

## Ready?

- [X] Added unit tests for fixed bug/feature
- [X] Passing all unit tests
- [X] Complete build `./mvnw clean verify` passes (checked automatically by github actions)
- [X] Added (in-code) documentation (if needed)

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">No regression tested rules have been changed.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by adangel** [comment]
Thanks for the PR. However, isn't that the same as #5086?

**Comment by duursma** [comment]
It is the same (with one extra test-case). Previous version was merge but then got lost in the process.

**Comment by adangel** [comment]
I see, thanks for following up.
The change was in the original PR #5086, but got removed with #5088 (however, github doesn't show the changes of this commit https://github.com/pmd/pmd/pull/5088/commits/45b75c5ca0e5cd281609b6a0f20c7bd98bafa4be in the overall change).

**Pull request merged**
