### PR TITLE
change CSVRenderer to adapt the huge project and huge output.

### PR DESCRIPTION
**Pull request by yalechen-cyw3**
Signed-off-by: yalechen

Please, prefix the PR title with the language it applies to within brackets, such as *[java]* or *[apex]*. If not specific to a language, you can use *[core]*

Before submitting a PR, please check that:
 - [ ] The PR is submitted against `master`. The PMD team will merge back to support branches as needed.
 - [ ] `mvn test` passes.
 - [ ] `mvn checkstyle:check` passes. [Check this for more info](https://github.com/pmd/pmd/blob/master/CONTRIBUTING.md#code-style)

**PR Description:**

### CODE REVIEW

**Comment by jsotuyod** [comment]
@yalechen-cyw3 thanks for the attempt, but I am rejecting this PR as it stands.

The proposed alternative doesn't fix the underlaying issue (rendering in memory to a string), and has no guarantee of working on larger workloads. It also breaks the current `render` contract, which in turn breaks the [`CPD Ant task`](https://github.com/yalechen-cyw/pmd/blob/a88a075fc71ff51c977f165e520c03484a9cf7fc/pmd-core/src/main/java/net/sourceforge/pmd/cpd/CPDTask.java#L127-L135)

To actually fix this, we need *all CPD renderers* (not just CSV) to change from returning `String` to return `void`, and simply receive a  `java.io.Writer` (which may wrap a file or stdout) in which to append output directly instead of using a `StringBuilder` as it currently does.

**Comment by yalechen-cyw3** [comment]
@jsotuyod 
Ok.
But when do you fix this bug and release a version?

**Comment by jsotuyod** [comment]
@yalechen-cyw3 the task is in the backlog, but currently unscheduled. I guess at the very latest it will be part of 7.0.0 (assuming we can't tackle it without a breaking API change), but I'd hope to get it done earlier, during a minor 6.x release.

PRs are welcomed to help move this forward faster.

**Comment by jsotuyod** [comment]
Closing this. I'm currently testing a fix for 6.1.0

**Pull request closed without merging**
