### PR TITLE
[java] Update ExcessiveSomething rules

### PR DESCRIPTION
**Pull request by oowekyala**
## Describe the PR

Update rules
- ExcessiveClassLengthRule
- ExcessiveImportsRule
- ExcessiveMethodLengthRule
- ExcessiveParameterListRule
- ExcessivePublicCountRule

most of them without changes.

## Related issues

- Items of #2701

## Ready?

- [ ] Added unit tests for fixed bug/feature
- [ ] Passing all unit tests
- [ ] Complete build `./mvnw clean verify` passes (checked automatically by github actions)
- [ ] Added (in-code) documentation (if needed)

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          2 Messages
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">Compared to pmd/7.0.x:<br />
This changeset changes 0 violations,<br />
introduces 304 new violations, 0 new errors and 0 new configuration errors,<br />
removes 0 violations, 0 errors and 0 configuration errors.<br />
<a href="https://chunk.io/pmd/21f16d5b72d84252a6c7558239e43f75/diff1/index.html">Full report</a></td>
    </tr>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">Compared to master:<br />
This changeset changes 0 violations,<br />
introduces 0 new violations, 1 new errors and 0 new configuration errors,<br />
removes 303556 violations, 8 errors and 2 configuration errors.<br />
<a href="https://chunk.io/pmd/21f16d5b72d84252a6c7558239e43f75/diff2/index.html">Full report</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by adangel** [comment]
It looks like only ExcessiveImports and ExcessiveParameterList report violations, the other rules (ExcessivePublicCount, ExcessiveMethodLength and ExcessiveClassLength) are missing.... although they should have been executed (https://chunk.io/pmd/21f16d5b72d84252a6c7558239e43f75/diff2/patch_config.xml), they look like, they are just skipped....

I'll have a look at this.

**Comment by adangel** [comment]
Maybe it's really because there were literally now changes for these rules. The regression tester for pmd7 really didn't execute these: https://chunk.io/pmd/21f16d5b72d84252a6c7558239e43f75/diff1/patch_config.xml

But for the comparison with master, they should have been there... but I see false-negatives now. Actually, there are only removed violations. Maybe we filter really only to the two rules that have changes?

**Comment by adangel** [comment]
Ok, so we first execute pmd-regression-tester against pmd/7.0.x. There we figured out (from git diff), that only the rules ExcessiveImports and ExcessiveParameterList have been changed and run PMD with a ruleset only with these two rules enabled.
After that, we create the comparison against master - we don't run PMD again, we use the report from the previous run. So in effect, only the two rules have been executed.

**Review by adangel — APPROVED** [review]

**Pull request merged**
