### PR TITLE
[java] Fix NonStaticInitializer FP in anonymous classes

### LINKED ISSUE #1853: [java] False positive for NonStaticInitializer in anonymous class
Rule: [NonStaticInitializer](https://pmd.github.io/pmd-6.15.0/pmd_rules_java_errorprone.html#nonstaticinitializer)

An instance initializer is the only way to initialize an anonymous class. The alternative is to create a local class with a constructor but quite honestly it's verbose and not that useful.

Test case:

```java
public class Foo {
       public Animation getStatusTransition() {
          return new Transition() {

            {
                setCycleDuration(Duration.millis(1200));
            }

            @Override
            protected void interpolate(double frac) {
               // magic
            }
        };
     }
}
```

### PR DESCRIPTION
**Pull request by oowekyala**
Fix #1853

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">This changeset introduces 0 new violations, 0 new errors and 0 new configuration errors,<br />
removes 54 violations, 0 errors and 2 configuration errors.<br />
<a href="https://chunk.io/pmd/551ccfb1bc4e43b4b9edcc974b518f89/diff/index.html">Full report</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by jsotuyod** [comment]
@oowekyala the change looks ok, but now we are not reporting on constructs such as:

```java
Map<String, Object> expectedAttributes = new HashMap<String, Object>() {{
	put("groovyScript", "groovy!");
	put("xmlFile", "groovy!");
	put("value", "groovy!");
}}
```

I've long liked these being reported, specially on Android projects, as doing this, instead of the alternative:

```java
Map<String, Object> expectedAttributes = new HashMap<String, Object>();
expectedAttributes.put("groovyScript", "groovy!");
expectedAttributes.put("xmlFile", "groovy!");
expectedAttributes.put("value", "groovy!");
```

Introduces one extra class to the dex file (which leads to multidex and larger APKs)…

I think that if this change is introduced, we are needing a new rule to flag anon classes (not enum constants!) that **only** containt a non-static initializer.

**Comment by oowekyala** [comment]
@jsotuyod Yes that's the sense of #1854 ^^ I think it's a bit early to implement it though, since in some cases the initialiser may call protected method

**Comment by jsotuyod** [comment]
@oowekyala yeah, I just think both changes should be part of the same release for completeness.

**Pull request merged**
