### PR TITLE
[java] Fix false positive in UnnecessaryParentheses

### PR DESCRIPTION
**Pull request by AnthonyKot**
Before submitting a PR, please check that:
 - [ ] The PR is submitted against `master`. The PMD team will merge back to support branches as needed.
 - [ ] `./mvnw clean verify` passes. This will [build](https://github.com/pmd/pmd/blob/master/BUILDING.md) and test PMD, execute PMD and checkstyle rules. [Check this for more info](https://github.com/pmd/pmd/blob/master/CONTRIBUTING.md#code-style)

**PR Description:**
Allow double brackets for in and or conditions for readability reasons.

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">This changeset introduces 0 new violations, 0 new errors and 0 new configuration errors,<br />
removes 211 violations, 2 errors and 2 configuration errors.<br />
<a href="https://chunk.io/pmd/087604877da5495e9b8220e971127aef/diff/index.html">Full report</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by oowekyala** [comment]
Hi, thanks for your work on this.

Unfortunately this doesn't fix the problem described by #1918. In Java there are two sets of operators to perform boolean logical AND and OR:
* `&&` and `||`, which you are probably used to, perform [short-circuit evaluation](https://en.wikipedia.org/wiki/Short-circuit_evaluation). Those are parsed by PMD as `ConditionalAndExpression` and `ConditionalOrExpression`, respectively.
* `&` and `|`, do the same as the above but aren't short-circuiting.  Those are parsed by PMD as `AndExpression` and `InclusiveOrExpression`, respectively.

Those sets of operators are different, and the short circuiting operators have greater precedence as the other ones.

So the issue described in #1918 is that in `b || (c & d)`, the parentheses are necessary. Without the parentheses, the expression would be understood as `(b || c) & d`.

**Comment by adangel** [comment]
> So the issue described in #1918 is that in `b || (c & d)`, the parentheses are necessary. Without the parentheses, the expression would be understood as `(b || c) & d`.

I think actually, strictly speaking, the parentheses are not neccessary, because `&` is evaluated first before `||`, so effectively `b || (c & d) ` is the same as `b || c & d`. Similar with pure logic operators: `b || (c && d)` is the same as `b || c && d`.

**Comment by oowekyala** [comment]
@adangel Hum you're right. I thought short-circuit operators had the greater precedence. There's still a tricky case though, when you mix the short-circuit ops and the others:
*  `b || c && d` ->  `b || (c && d)`
*  `b || c & d` ->  `b || (c & d)`
*  **`b | c && d` ->  `(b | c) && d`**
*  `b | c & d` ->  `b | (c & d)`

In the third case, the `|` nests more closely

**Comment by AnthonyKot** [comment]
@oowekyala, @adangel  thank you for clarifications. I misunderstood the problem.
As I can see mixing with short-circuit ops is handled properly by current UnnecessaryParentheses rule.
So in original "a || b || (c & d) || e" brackets tecnically were redundant and issue can be closed.
In other hand, time to time parentheses could be used to improve readability, so less strict rule can be created to replace original in some rulesets.

**Pull request closed without merging**
