### PR TITLE
[apex] Add AvoidDirectAccessTriggerMap rule to the style set

### LINKED ISSUE #627: [apex] Direct access to Trigger.old and Trigger.new should be avoided
Please, prefix the report title with the language it applies to within brackets, such as *[java]* or *[apex]*. If not specific to a language, you can use *[core]*

**Rule Set:** Apex

**Description:** New rule: Avoid directly accessing Trigger.old and Trigger.new as it can lead to a bug. Your triggers should be bulkified and iterate through the map to handle the actions for each item separately.

**Code Sample demonstrating the issue:**

```
trigger AccountTrigger on Account (before insert, before update) {
   Account a = Trigger.new[0]; //Bad: Accessing the trigger array directly is not recommended.
   
   foreach ( Account a : Trigger.new ){   //Good: Iterate through the trigger.new array instead.
   }
}

```

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]*

### PR DESCRIPTION
**Pull request by JAertgeerts**
- [x] The PR is submitted against `master`. The PMD team will merge back to support branches as needed.
 - [x] `mvn test` passes.
 - [x] `mvn checkstyle:check` passes. [Check this for more info](https://github.com/pmd/pmd/blob/master/CONTRIBUTING.md#code-style)

**PR Description:**
Add AvoidDirectAccessTriggerMap check to resolve #627

### CODE REVIEW

**Comment by up2go-rsoesemann** [comment]
IMHO there should be no code at all in Triggers. Thats why I added https://github.com/pmd/pmd/blob/master/pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/style/AvoidLogicInTriggerRule.java

Maybe you can harmonize both rules.

**Comment by JAertgeerts** [comment]
@up2go-rsoesemann Agreed, but having 2 separate rules make sense. Some organisations might place logic in their triggers (or have a legacy code base they're unable to refactor bc of budget restraints) but should at least bulkify them to prevent immediate bugs. This way, people can plug and play the rules they find important. Harmonizing rules limits freedom.

**Comment by jsotuyod** [comment]
@JAertgeerts just wondering here... why is this in the performance ruleset?

The description states:

> Avoid directly accessing Trigger.old and Trigger.new as it can lead to a bug. Triggers should be bulkified and iterate through the map to handle the actions for each item separately

For this wording, I understand the main reasoning behind the rule is to avoid illegal index accesses (bugs), and not performance reasons...

If there is a performance difference in Apex for using different iterations patterns, then maybe the description should be reworded, and even better, a source backing that up should be referenced. Also, if there is such a difference, is this really only relevant to triggers?

As for the collision with `apex-style/AvoidLogicInTrigger`, on general terms I agree with @up2go-rsoesemann. However, on this scenario the collision doesn't seem so bad. The rules are not outright contradictory, even if having both enabled, it wouldn't lead to one triggering when fixing the other one, although certainly, having `apex-style/AvoidLogicInTrigger` enabled makes this one pointless, unless, once again, for some reason we want to suppress the other one on a specific scenario, but still want this one to apply....

**Comment by JAertgeerts** [comment]
@jsotuyod Good point, I think I looked at the rulesets descriptions. This one said overall best practices so I want with that. 

Although I don't think this is style either, like `apex-style/AvoidLogicInTrigger` definitely is. This violation can induce bugs as you'll hit governor limits or just bugs when accessing these maps directly rather than bulkifying them. This accounts for all bulkifying patterns, so maybe we should add a new ruleset with the bulkifying rules? Another example would be single object dml statements rather than lists:

```
sObject sobj = new sObject();
insert sobj; //this is bad practice

sObject[] sobjList = new List<sObject>();
sobj.add(sobj);
insert sobjList; // this is good practice
```

The problem with not only looking at triggers is that we don't know what has been passed from other classes. Let's say there's a handler class that receives this map and doesn't iterate over it but instead takes the first element, we'd have to create a rule that doesn't allow array literals `[0]` or `[1]` of which we don't have sufficient context to say it's wrong. In triggers we have an AST node that can clearly identify these, so I think this would be sufficient for now.

**Comment by jsotuyod** [comment]
@JAertgeerts ok, so we should definitely move it to a different ruleset as performance doesn't apply. May it be either a new one for bulk operations, or simply style. I'm pro having a bulk ruleset if we have 3-5 rules available.

> The problem with not only looking at triggers is that we don't know what has been passed from other classes. Let's say there's a handler class that receives this map and doesn't iterate over it but instead takes the first element, we'd have to create a rule that doesn't allow array literals [0] or [1] of which we don't have sufficient context to say it's wrong. In triggers we have an AST node that can clearly identify these, so I think this would be sufficient for now.

Yes, we could face false negatives this way until we have support for type resolution / multifile data flow analysis; however, for single file cases, we can detect it without being over-restrictive (false positives); which means it's still far better than nothing.

**Comment by JAertgeerts** [comment]
@jsotuyod sure, should be able to rework this week.

**Comment by JAertgeerts** [comment]
@jsotuyod Moved to style and added literal expression in arrayload

**Comment by jsotuyod** [comment]
Merged! This will be part of PMD 6.0.0. Thanks again for the contribution!

**Pull request merged**
