### PR TITLE
[java] AvoidReassigningParameters reports violations on wrong line numbers

### LINKED ISSUE #2219: [java] Document Reasons to Avoid Reassigning Parameters
**Affects PMD Version:** 

6.20.0

**Rule:**

Java Best Practices - AvoidReassigningParameters
https://pmd.github.io/latest/pmd_rules_java_bestpractices.html#avoidreassigningparameters

**Description:**

The comment for this rule is:

> Reassigning values to incoming parameters is not recommended. Use temporary local variables instead.

This comment does not tell me why reassigning parameters is "not recommended".  Please add reasons why this is a bad idea so that users can make better informed decisions about the rule.

I tried looking for reasons on the Internet.  One reason was due to parameters being passed via reference as in C/C++.  This is not applicable to Java since the method parameter reference can be changed without impacting the caller.  Here is another reason:

> Multiple assignments of different values to a single parameter make it difficult for you to know what data should be contained in the parameter at any particular point in time. The problem worsens if your parameter and its contents are documented but the actual value is capable of differing from what’s expected inside the method.

Please find other reasons for this rule and add it to the documentation.

### LINKED ISSUE #3254: [java] AvoidReassigningParameters reports violations on wrong line numbers
**Affects PMD Version:** 6.34.0

**Description:**

The rule [AvoidReassigningParameters](https://pmd.github.io/latest/pmd_rules_java_bestpractices.html#avoidreassigningparameters) reports each assignment. But the line reported is the declaration of the parameter instead of the assignment.

This is not helpful. Consider the example below with one parameter. Either only one violation should be reported at the declaration of the parameter or two violations on the two lines of the assignments.

**Code Sample demonstrating the issue:**

```java
public class AvoidReassigningParameters {
    public void a(String b) {  // line 2: here are two violations reported
        b = "1";               // line 3: no violation, but expected
        b = "2";               // line 4: no violation, but expected
    }
}
```

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]*

### PR DESCRIPTION
**Pull request by adangel**
- Fixes #3254
- Fixes #2219

## Ready?

- [x] Added unit tests for fixed bug/feature
- [x] Passing all unit tests
- [x] Complete build `./mvnw clean verify` passes (checked automatically by github actions)
- [x] Added (in-code) documentation (if needed)

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">This changeset changes 237 violations,<br />
introduces 392 new violations, 0 new errors and 0 new configuration errors,<br />
removes 84 violations, 2 errors and 2 configuration errors.<br />
<a href="https://chunk.io/pmd/c971f51d18f6444aab9ee0363d6d1204/diff/index.html">Full report</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by adangel** [comment]
In total, there are now 392-84=308 new violations, but these only appear as new. I think, the regression tester didn't count the violations, that were in the same file on the same line. That's why it appears as if this fixed a false negative, which it doesn't.

The alternative would be, that we only report one violation per parameter. But from the rule name, I'd expect what we have now: We report the locations, where the parameter is reassigned. Which parameter it is, that's anyway obvious (in the violation message and if you look at the line in the sources).

**Comment by oowekyala** [comment]
> The alternative would be, that we only report one violation per parameter. But from the rule name, I'd expect what we have now: We report the locations, where the parameter is reassigned. Which parameter it is, that's anyway obvious (in the violation message and if you look at the line in the sources).

I think it is good to report on an assignment and not the parameter declaration. But probably we should just report on the first assignment and not all of them, as currently the rule is very noisy.

**Comment by adangel** [comment]
> currently the rule is very noisy.

that's true. I'll give it a try to report only the first one....

**Comment by adangel** [comment]
I thinks, that's much better now. Note, I also updated the rule doc for fixing #2219.

**Review by oowekyala — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
