### PR TITLE
[java] Fix #4224 MissingStaticMethodInNonInstantiatableClass: Exclude lombok's UtilityClass 

### LINKED ISSUE #4224: [java] MissingStaticMethodInNonInstantiatableClass should consider Lombok's @UtilityClass
**Affects PMD Version:6.51.0**

**Rule: MissingStaticMethodInNonInstantiatableClass**

Please provide the rule name and a link to the rule documentation:
<https://pmd.github.io/latest/pmd_rules_java_errorprone.html#missingstaticmethodinnoninstantiatableclass>

**Description:**
In the following code example, the `@UtilityClass` generates a private constructor `private Test()` which throws an exception.So the class only has a private constructor and does not have any static methods or fields which cannot be used. But PMD considers the class doesn't have a constructor and does not report `MissingStaticMethodInNonInstantiatableClass` at line 4 which causes false negatives.

Lombok documentation: https://projectlombok.org/features/experimental/UtilityClass

**Code Sample demonstrating the issue:**

Original code:
```java
import lombok.experimental.UtilityClass;

@UtilityClass
public final class Test {
    private int x;
}
```
Changed:
```java
public final class Test {
    private static int x;

    private Test() {
        throw new UnsupportedOperationException("This is a utility class and cannot be instantiated");
    }
}
```

**Expected outcome:**

PMD should report a violation at line 4, but not. That's a false negative.

**Running PMD through:** *CLI*

### PR DESCRIPTION
**Pull request by LynnBroe**
## Describe the PR

This PR excludes lombok's UtilityClass  which create a private method which throw a exception but PMD treats it as a false negative.
## Related issues

- Fixes #4224 

## Ready?

- [x] Added unit tests for fixed bug/feature
- [x] Passing all unit tests
- [x] Complete build `./mvnw clean verify` passes (checked automatically by github actions)
- [ ] Added (in-code) documentation (if needed)

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">Compared to master:<br />
This changeset changes 0 violations,<br />
introduces 0 new violations, 0 new errors and 0 new configuration errors,<br />
removes 0 violations, 2 errors and 7 configuration errors.<br />
<a href="https://chunk.io/pmd/9542dd73be1a499586fec9c10abee383/diff1/index.html">Full report</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by adangel — CHANGES_REQUESTED** [review]
Sorry, need to revise my review: Now any class that is annotated with UtilityClass is flagged. However, this is wrong. Only classes that don't have methods should be flagged.

E.g. if you add a method in your test class, then the rule should not be triggered anymore. It doesn't matter, whether the method is static or not since the UtilityClass annotation makes all methods static.
Maybe we also need to look at the visibility of the methods - since if all methods are private, then they can't be called as well and the class remains unusable.

**Comment by LynnBroe** [comment]
Thanks, I will recheck my commit

**Review by adangel — APPROVED** [review]
Thanks!

**Pull request merged**
