### PR TITLE
Added language module for Salesforce.com Apex incl. rules ported from Java and new ones.

### PR DESCRIPTION
**Pull request by up2go-rsoesemann**
As discussed this is our v1.0 to get something and get the community involved soon enough.

### CODE REVIEW

**Comment by derekhansen** [comment]
Very excited about this. Thanks for your work @up2go-rsoesemann !

**Comment by up2go-rsoesemann** [comment]
Can you imagine contributing to the module? New or improved Apex rules. Improving the quirky Eclipse plugin. I never thought so but it actually is not that hard.

**Comment by derekhansen** [comment]
Yea, absolutely. I'll give it a spin in the next week or two on our code base and see how it goes.

**Comment by nachiket-deshpande** [comment]
Facing following exception while executing PMD through Command Line:-

`Exception applying rule StdCyclomaticComplexity on file D:\Nachiket Dev Org\Nachiket New Dev Org Dec 2015\src\triggers\AccountTrigger.trigger, continuing with next rule java.util.EmptyStackException at java.util.Stack.peek(Unknown Source) at net.sourceforge.pmd.lang.apex.rule.complexity.StdCyclomaticComplexityRule.visit(StdCyclomaticComplexityRule.java:124) at net.sourceforge.pmd.lang.apex.ast.ASTMethod.jjtAccept(ASTMethod.java:15) at net.sourceforge.pmd.lang.apex.ast.AbstractApexNode.childrenAccept(AbstractApexNode.java:101) at net.sourceforge.pmd.lang.apex.rule.AbstractApexRule.visit(AbstractApexRule.java:131) at net.sourceforge.pmd.lang.apex.rule.AbstractApexRule.visit(AbstractApexRule.java:517) at net.sourceforge.pmd.lang.apex.rule.AbstractApexRule.visitAll(AbstractApexRule.java:124) at net.sourceforge.pmd.lang.apex.rule.AbstractApexRule.apply(AbstractApexRule.java:114) at net.sourceforge.pmd.lang.rule.AbstractDelegateRule.apply(AbstractDelegateRule.java:215) at net.sourceforge.pmd.RuleSet.apply(RuleSet.java:307) at net.sourceforge.pmd.RuleSets.apply(RuleSets.java:125) at net.sourceforge.pmd.SourceCodeProcessor.processSource(SourceCodeProcessor.java:146) at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:76) at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:43) at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:78) at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:25) at java.util.concurrent.FutureTask.run(Unknown Source) at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) at java.lang.Thread.run(Unknown Source) Exception applying rule StdCyclomaticComplexity on file D:\Nachiket Dev Org\Nachiket New Dev Org Dec 2015\src\triggers\CaseTrigger.trigger, continuing with next rule java.util.EmptyStackException at java.util.Stack.peek(Unknown Source) at net.sourceforge.pmd.lang.apex.rule.complexity.StdCyclomaticComplexityRule.visit(StdCyclomaticComplexityRule.java:124) at net.sourceforge.pmd.lang.apex.ast.ASTMethod.jjtAccept(ASTMethod.java:15) at net.sourceforge.pmd.lang.apex.ast.AbstractApexNode.childrenAccept(AbstractApexNode.java:101) at net.sourceforge.pmd.lang.apex.rule.AbstractApexRule.visit(AbstractApexRule.java:131) at net.sourceforge.pmd.lang.apex.rule.AbstractApexRule.visit(AbstractApexRule.java:517) at net.sourceforge.pmd.lang.apex.rule.AbstractApexRule.visitAll(AbstractApexRule.java:124) at net.sourceforge.pmd.lang.apex.rule.AbstractApexRule.apply(AbstractApexRule.java:114) at net.sourceforge.pmd.lang.rule.AbstractDelegateRule.apply(AbstractDelegateRule.java:215) at net.sourceforge.pmd.RuleSet.apply(RuleSet.java:307) at net.sourceforge.pmd.RuleSets.apply(RuleSets.java:125) at net.sourceforge.pmd.SourceCodeProcessor.processSource(SourceCodeProcessor.java:146) at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:76) at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:43) at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:78) at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:25) at java.util.concurrent.FutureTask.run(Unknown Source) at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) at java.lang.Thread.run(Unknown Source) Exception applying rule StdCyclomaticComplexity on file D:\Nachiket Dev Org\Nachiket New Dev Org Dec 2015\src\triggers\Test_Share.trigger, continuing with next rule java.util.EmptyStackException at java.util.Stack.peek(Unknown Source) at net.sourceforge.pmd.lang.apex.rule.complexity.StdCyclomaticComplexityRule.visit(StdCyclomaticComplexityRule.java:124) at net.sourceforge.pmd.lang.apex.ast.ASTMethod.jjtAccept(ASTMethod.java:15) at net.sourceforge.pmd.lang.apex.ast.AbstractApexNode.childrenAccept(AbstractApexNode.java:101) at net.sourceforge.pmd.lang.apex.rule.AbstractApexRule.visit(AbstractApexRule.java:131) at net.sourceforge.pmd.lang.apex.rule.AbstractApexRule.visit(AbstractApexRule.java:517) at net.sourceforge.pmd.lang.apex.rule.AbstractApexRule.visitAll(AbstractApexRule.java:124) at net.sourceforge.pmd.lang.apex.rule.AbstractApexRule.apply(AbstractApexRule.java:114) at net.sourceforge.pmd.lang.rule.AbstractDelegateRule.apply(AbstractDelegateRule.java:215) at net.sourceforge.pmd.RuleSet.apply(RuleSet.java:307) at net.sourceforge.pmd.RuleSets.apply(RuleSets.java:125) at net.sourceforge.pmd.SourceCodeProcessor.processSource(SourceCodeProcessor.java:146) at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:76) at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:43) at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:78) at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:25) at java.util.concurrent.FutureTask.run(Unknown Source) at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) at java.lang.Thread.run(Unknown Source)`

**Comment by nachiket-deshpande** [comment]
Facing following exception while enabling PMD in eclipse.

pmd issue

**Comment by up2go-rsoesemann** [comment]
@nachiket-deshpande thanks for giving PMD for Apex a try and reporting problems. 

We are aware of the failure when applying some rules on trigger and I think @Up2Go-DavidRenz already fixed it. It's a Apex specific error. That's why I created a real issue in our own fork because we will take care of it. Please follow https://github.com/Up2Go/pmd/issues/38 to keep you posted.

For the eclipse problem I kindly ask you to open a regular PMD bug ticket at https://sourceforge.net/p/pmd/bugs/ as this is not connected to our Apex extension. @adangel and the PMD community will take care of such issues.

**Pull request merged**
