### PR TITLE
[java] Fix incompatible class bounds not checked during incorporation

### LINKED ISSUE #4980: [java] Bad intersection, unr elated class types java.lang.Object[] and java.lang.Number
**Affects PMD Version:**

7.1.0.

**Description:**

This code:

```java
public <T extends Number> T foo() {
	return null;
}

public Stream<Number> bar() {
	return Stream.of(foo());
}
```

Leads to:

**Exception Stacktrace:**

```
org.apache.commons.lang3.exception.ContextedRuntimeException: java.lang.IllegalArgumentException: Bad intersection, unrelated class types java.lang.Object[] and java.lang.Number in [java.lang.Number, java.lang.Object[]]
Exception Context:
        [1:Resolving type of=!debug only! [MethodCall:81:10]Stream.of(foo())]
        [2:Rule applied on node=!debug only! [MethodCall:81:10]Stream.of(foo())]
---------------------------------
        at net.sourceforge.pmd.util.AssertionUtil.contexted(AssertionUtil.java:236)
        at net.sourceforge.pmd.lang.java.ast.AbstractJavaTypeNode.getTypeMirror(AbstractJavaTypeNode.java:54)
        at net.sourceforge.pmd.lang.java.ast.ASTMethodCall.getTypeMirror(ASTMethodCall.java:22)
        at net.sourceforge.pmd.lang.java.ast.AbstractJavaTypeNode.getTypeMirror(AbstractJavaTypeNode.java:39)
        at net.sourceforge.pmd.lang.java.ast.ASTMethodCall.getTypeMirror(ASTMethodCall.java:22)
        at net.sourceforge.pmd.lang.java.ast.AbstractJavaTypeNode.forceTypeResolution(AbstractJavaTypeNode.java:29)
        at net.sourceforge.pmd.lang.java.ast.AbstractInvocationExpr.getOverloadSelectionInfo(AbstractInvocationExpr.java:27)
        at net.sourceforge.pmd.lang.java.ast.ASTMethodCall.getOverloadSelectionInfo(ASTMethodCall.java:22)
        at net.sourceforge.pmd.lang.java.ast.InvocationNode.getMethodType(InvocationNode.java:48)
        at net.sourceforge.pmd.lang.java.rule.internal.TestFrameworksUtil.isCallOnAssertionContainer(TestFrameworksUtil.java:166)
        at net.sourceforge.pmd.lang.java.rule.bestpractices.JUnitAssertionsShouldIncludeMessageRule.visit(JUnitAssertionsShouldIncludeMessageRule.java:37)
        at net.sourceforge.pmd.lang.java.ast.ASTMethodCall.acceptVisitor(ASTMethodCall.java:75)
        at net.sourceforge.pmd.lang.java.ast.AbstractJavaNode.acceptVisitor(AbstractJavaNode.java:38)
        at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.apply(AbstractJavaRule.java:30)
        at net.sourceforge.pmd.lang.rule.RuleReference.apply(RuleReference.java:415)
        at net.sourceforge.pmd.lang.rule.internal.RuleApplicator.applyOnIndex(RuleApplicator.java:77)
        at net.sourceforge.pmd.lang.rule.internal.RuleApplicator.apply(RuleApplicator.java:57)
        at net.sourceforge.pmd.lang.rule.internal.RuleSets.apply(RuleSets.java:155)
        at net.sourceforge.pmd.lang.impl.PmdRunnable.processSource(PmdRunnable.java:140)
        at net.sourceforge.pmd.lang.impl.PmdRunnable.run(PmdRunnable.java:80)
        at java.base@21.0.2/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
        at java.base@21.0.2/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base@21.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base@21.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base@21.0.2/java.lang.Thread.run(Thread.java:1583)
```

**Code Sample demonstrating the issue:**

See above.

**Steps to reproduce:**

Run PMD on that code.

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]*

Gradle.

### PR DESCRIPTION
**Pull request by jsotuyod**
## Describe the PR

If an exception occurred during applicability testing it only means the candidate method is not applicable, not that an error actually occurred during inference, there is no need to abort altogether.

## Related issues

- Fixes #4980 

## Ready?

- [x] Added unit tests for fixed bug/feature
- [x] Passing all unit tests
- [x] Complete build `./mvnw clean verify` passes (checked automatically by github actions)
- [x] Added (in-code) documentation (if needed)

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">Compared to master:<br />
This changeset changes 0 violations,<br />
introduces 0 new violations, 0 new errors and 0 new configuration errors,<br />
removes 0 violations, 0 errors and 0 configuration errors.<br />
<a href="https://github.com/pmd/pmd/actions/runs/8863412554?pr=4982">Download full report as build artifact</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by jsotuyod** [comment]
> My intuition is that we can catch that earlier and not need to create the bad intersection.

I don't see how we could do this… Assume our code is even a more adverse scenario:

```java
public <T> T foo(T t) {
    return t;
}

public void bar() {
    Stream.of(foo("hello")); // should match Stream.of(T) by strict invocation
    Stream.of(foo(new Integer[] { 1, 2, 3 })); // should match Stream.of(T...) by strict invocation
}
```

Yes, we know the method is varargs, we know we are on a `STRICT` phase (not `VARARGS`), but we can't tell if the argument is or not an array until we try to resolve the context to figure out what `foo(x)` will return (and therefore hitting `Lub`).

> Otherwise we should have a more specific exception type for this exception and only catch that one.

This is probably more reasonable…

**Comment by oowekyala** [comment]
I'm going to take a look with a debugger...

**Comment by oowekyala** [comment]
I think this should do the trick: https://github.com/oowekyala/pmd/commit/6fea861ab62f7e0ba4fff455eb6c5fb0f03cc383

This is an incompatibility between bounds and should be checked like other bounds are checked, during incorporation.

I can't write to your branch so I just pushed into my repo.

**Comment by jsotuyod** [comment]
@oowekyala there you go, I incorporated those changes to my branch

**Review by oowekyala — APPROVED** [review]
LGTM

**Comment by adangel** [comment]
@jsotuyod FYI, in case you didn't see the edit:

> Edit: Actually there are some errors I am looking into. It would be nice if you made your
> branch writeable to maintainers @jsotuyod, there's a checkbox to tick somewhere
>
> -> https://github.com/pmd/pmd/commit/5dcffcaa76ad0ec99a233225ed094eb24df2dc17

**Comment by jsotuyod** [comment]
@adangel no, Github disabled that for org-owned forks some time back… I'll have to switch my fork at some point.

**Comment by oowekyala** [comment]
I opened #4994 to continue this

**Pull request closed without merging**
