### PR TITLE
Fix some NullPointerExceptions

### PR DESCRIPTION
**Pull request by Vampire**
This PR fixes some NPEs we encountered with our production code.
Tests with the stripped down real-world code are included.

### CODE REVIEW

**Comment by MichaelZett** [comment]
+1 did fix problems in our build

**Comment by adangel** [comment]
Thanks!
Partially, this has been solved with https://sourceforge.net/p/pmd/bugs/1333/

**Comment by Vampire** [comment]
Ah, I developed the failing tests and fixes on 5.3.0, so I did not see that 1333 fix. Now it is double save. :-)
Do you have an idea when 5.3.1 will be released? As it seems at least the 1333 issue hits many ppl, amongst them SonarQube users.

**Comment by adangel** [comment]
I think, I'll release 5.3.1 early next week.

**Pull request merged**
