### PR TITLE
[doc] Add documentation as github pages

### PR DESCRIPTION
**Pull request by adangel**
This is unfortunately a very big PR - but all the changes are under the folder `docs/`.
The old maven-site doc (under `src/site`) is not removed yet, but all existing content has been migrated to the new structure.

A preview of this PR is available at http://adangel.github.io/pmd/index.html

After we merge this PR, we need to double check, that github itself generates the pages correctly. The preview is generated locally on my machine, so I don't know for sure yet, whether it'll work.

Before submitting a PR, please check that:
 - [x] The PR is submitted against `master`. The PMD team will merge back to support branches as needed.
 - [x] `mvn test` passes.
 - [x] `mvn checkstyle:check` passes. [Check this for more info](https://github.com/pmd/pmd/blob/master/CONTRIBUTING.md#code-style)

### CODE REVIEW

**Comment by jsotuyod** [comment]
Is this ready for merge or a WIP?

I see some empty pages such as http://adangel.github.io/pmd/pmd_rules_java.html

**Comment by adangel** [comment]
This PR itself is ready.

I'd wait with #508 until I finished the rule/ruleset documentation generation (that's still TODO). This will fill the empty rule reference pages.

However, the whole documentation will stay a while WIP, as there are many gaps... (especially end user documentation). And I expect the documentation to be continuously improved over time.

**Comment by oowekyala** [comment]
Shouldn't we merge that into a feature branch and keep it that way until the user doc is a little more complete ?

**Comment by adangel** [comment]
I hope, if it is merged into master, that others chime in in improving the documentation... If it is in a feature branch, I think, it's too far away to be noticed.

**Comment by jsotuyod** [comment]
Merged!

**Comment by adangel** [comment]
Thanks! The current doc is now available under https://pmd.github.io/pmd/ and http://pmd.sourceforge.net/snapshot/

**Pull request merged**
