### PR TITLE
Add rule to look for invalid message format in slf4j loggers

### PR DESCRIPTION
**Pull request by DTecheira**
I have added a rule to check the messages in slf4j loggers that have missing or extra parameters, ignoring the exception as parameter if exists because it is shown separately.

The rule was added in the logging-java file and the test cases have been added to the corresponding folders.

### CODE REVIEW

**Comment by adangel** [comment]
Thanks!

**Comment by anatoliy-balakirev** [comment]
I'm not sure if this is a correct place to report, but with this change we are getting a lot of false positive when message contains just one placeholder and we are passing parameter for that placeholder and exception itself to be logged (which is a valid scenario). So for this statement:
`LOG.warn("My message with some placeholder here: {}", valueForPlaceholder, ex);`
I'm getting:
`PMD Failure: <class name and line here> Rule:InvalidSlf4jMessageFormat Priority:5 Too many arguments, expected 1 argument but have 2.`

**Comment by adangel** [comment]
I've created a bug ticket for you -> https://sourceforge.net/p/pmd/bugs/1504/

It seems to be a false positive, as the example in the rule explicitly has this case: one placeholder + exception. -> http://pmd.github.io/pmd-5.5.0/pmd-java/rules/java/logging-java.html#InvalidSlf4jMessageFormat

**Comment by adangel** [comment]
Turns out, it has been reported already: -> https://sourceforge.net/p/pmd/bugs/1500/

**Pull request merged**
