### PR TITLE
[java] Adding test for Issue #647

### PR DESCRIPTION
**Pull request by orimarko**
Before submitting a PR, please check that:
 - [ X ] The PR is submitted against `master`. The PMD team will merge back to support branches as needed.
 - [ X ] `./mvnw clean verify` passes. This will [build](https://github.com/pmd/pmd/blob/master/BUILDING.md) and test PMD, execute PMD and checkstyle rules. [Check this for more info](https://github.com/pmd/pmd/blob/master/CONTRIBUTING.md#code-style)

**PR Description:**
Adding test for Issue #647 JUnitTestsShouldIncludeAssertRule should support `this.exception` as well as just `exception`

### CODE REVIEW

**Comment by jsotuyod** [comment]
#647 is about using `this.exception` and not just `exception` (not using `this` is already covered in a couple of test cases https://github.com/pmd/pmd/blob/83712f134a580d963dec202a5f7a8776ce1428bc/pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/JUnitTestsShouldIncludeAssert.xml#L277-L317 )

And for the issue to be resolved, it should expect 0 warnings, not 1.

**Comment by Ranjanas25** [comment]
How do i work with pmd ? Would you please tell me about it.

**Comment by jsotuyod** [comment]
@orimarko thanks! that test case is perfect. Unfortunately, the build fails because the issue isn't actually resolved as the original reported believed.

Nontheless, I'd already posted some insight into how to actually fix this: https://github.com/pmd/pmd/issues/647#issuecomment-377116426

If you feel up to it, you can probably get it done easily and wrap up a very meaningful first contribution to PMD!

**Comment by adangel** [comment]
Hi @orimarko ,

we are planning to release PMD 6.10.0 in about 2 weeks. Do you have time to work on this issue? It would be awesome, if we could include a fix in the release.

**Pull request merged**
