### PR TITLE
[core] Fix Checkstyle OperatorWrap in AbstractTokenizer

### PR DESCRIPTION
**Pull request by harsh-kukreja**
Before submitting a PR, please check that:
 - [x] The PR is submitted against `master`. The PMD team will merge back to support branches as needed.
 - [x] `./mvnw clean verify` passes. This will [build](https://github.com/pmd/pmd/blob/master/BUILDING.md) and test PMD, execute PMD and checkstyle rules. [Check this for more info](https://github.com/pmd/pmd/blob/master/CONTRIBUTING.md#code-style)

**PR Description:**

As per the discussion in https://github.com/checkstyle/checkstyle/pull/8095#issuecomment-613764460

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">This changeset introduces 0 new violations, 0 new errors and 0 new configuration errors,<br />
removes 0 violations, 0 errors and 0 configuration errors.<br />
<a href="https://chunk.io/pmd/1fbc716d46f044788d2ad0f5f5eef231/diff/index.html">Full report</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by harsh-kukreja** [comment]
Done with the changes @oowekyala please review

**Comment by oowekyala** [comment]
@harsh-kukreja Thanks, this is merged

**Comment by harsh-kukreja** [comment]
@oowekyala Welcome

**Comment by oowekyala** [comment]
@harsh-kukreja Just a tip: don't force push an open PR unless you know for sure nobody's working on it. I had to start my merge over

**Comment by harsh-kukreja** [comment]
Ohh sorry for the trouble @oowekyala i squashed the commit so i had to force push

**Pull request merged**
