### PR TITLE
[java] InsufficientStringBufferDeclaration fix FP (#1438)

### LINKED ISSUE #1438: [java] InsufficientStringBufferDeclaration false positive for initial calculated StringBuilder size
**Affects PMD Version:** 

* 6.9.0
* 5.8.1

**Rule:**

[InsufficientStringBufferDeclaration](https://pmd.github.io/latest/pmd_rules_java_performance.html#insufficientstringbufferdeclaration)

**Description:**

When calculating the size of a `StringBuilder` at runtime, e.g. by adding the lengths of strings to be appended or by adding constant values e.g. for the output of Date/DecimalFormat will result in a `InsufficientStringBufferDeclaration` even if the calculated value will be larger than the length of the constant strings alone.

**Code Sample demonstrating the issue:**

```Java
public String foo(final String x, final String y, final double z, final Date d, final double v) {
	final StringBuilder sb = new StringBuilder(20 + 9*2 + 16 + 2 * x.length() + y.length());
	final DecimalFormat df = (DecimalFormat) DecimalFormat.getInstance(Locale.GERMAN);
	df.applyPattern("#,##0.000");
	final SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy hh:mm");
	sb.append("foobar")
		.append(df.format(z))
		.append(' ')
		.append(x)
		.append(y)
		.append("foobar")
		.append(sdf.format(d))
		.append("foobar")
		.append(df.format(v))
		.append(' ')
		.append(x);
	return sb.toString();
}
```

**Running PMD through:** *Gradle*

### PR DESCRIPTION
**Pull request by adangel**
## Describe the PR

Fixes false positive for initial calculated StringBuilder size.
If possible, the literals are calculated now. If there are method
calls or variables access, then no attempt is made to calculate
the initial size.

Also calls to ensureCapacity are recognized now in addition to setLength.

## Related issues

- Fixes #1438

## Ready?

- [x] Added unit tests for fixed bug/feature
- [x] Passing all unit tests
- [x] Complete build `./mvnw clean verify` passes (checked automatically by github actions)
- [x] Added (in-code) documentation (if needed)

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">This changeset changes 39 violations,<br />
introduces 11 new violations, 0 new errors and 0 new configuration errors,<br />
removes 1 violations, 2 errors and 2 configuration errors.<br />
<a href="https://chunk.io/pmd/2fd133b1babb455486907d8c57513adf/diff/index.html">Full report</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by adangel** [comment]
I've put that one to draft, in order to fix some more problems I discovered when porting the rule to pmd7.

**Comment by adangel** [comment]
Ok, so that is now ready. The two new violations are valid, and the one removed violation is also ok (we can't really know the capacity in that case).
I'll update #3278 for pmd7 in the next days, but as far as I see, all the tests work with the rewritten rule in pmd7.

**Review by oowekyala — APPROVED** [review]
This looks fine, thanks

**Pull request merged**
