### PR TITLE
[java] Update PMDASMClassLoader.java

### PR DESCRIPTION
**Pull request by Prasanna-Loga**
Reusing Loaded classes for performance enhancement

## Describe the PR

Classes were loaded for type resolution where loading the same class leads to performance compromise. We can cache the loaded class and reuse it when needed in order to reduce class loading time.

## Ready?

- [ ] Added unit tests for fixed bug/feature
- [ ] Passing all unit tests
- [ ] Complete build `./mvnw clean verify` passes (checked automatically by github actions)
- [ ] Added (in-code) documentation (if needed)

### CODE REVIEW

**Comment by jsotuyod** [comment]
@Prasanna-Loga thanks for the PR!

Could you provide benchmark data to backup the expected gain vs increased memory usage?

The classloader only loads each class into PermGen / Metaspace memory at most once… so at some level this check is already being performed. I'm unsure of what speedup short-circuiting that could actually bring.

**Comment by oowekyala** [comment]
> The classloader only loads each class into PermGen / Metaspace memory at most once… so at some level this check is already being performed. 

Yes, there is already a map containing classes in the ClassLoader implementation (`parallelLockMap`, see #2911). I don't think replicating it would accomplish anything

**Comment by adangel** [comment]
I wanted to try to build it, in order to see via the regression tester, whether there is some performance gain/loss, but it does not build:

```
  [INFO] There are 2 errors reported by Checkstyle 8.42 with /net/sourceforge/pmd/pmd-checkstyle-config.xml ruleset.
  Error:  src/main/java/net/sourceforge/pmd/lang/java/typeresolution/PMDASMClassLoader.java:[53,39] (whitespace) WhitespaceAfter: ',' is not followed by whitespace.
  Error:  src/main/java/net/sourceforge/pmd/lang/java/typeresolution/PMDASMClassLoader.java:[96,32] (whitespace) NoWhitespaceBefore: '.' is preceded with whitespace.
```

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">This changeset changes 0 violations,<br />
introduces 0 new violations, 0 new errors and 0 new configuration errors,<br />
removes 0 violations, 0 errors and 0 configuration errors.<br />
<a href="https://chunk.io/pmd/7f8e02f5e1ce4bb8a3fe363181feb948/diff/index.html">Full report</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by adangel** [comment]
Hm... so the non-scientific benchmark with the regression tester shows this:

duration before: 00:11:56
duration after: 00:13:01

The difference is not big - it could just be the normal variance (it runs as github actions somewhere in the cloud under uncontrolled conditions). If it is not the variance, then this change makes PMD actually slower...

**Comment by Prasanna-Loga** [comment]
I have tried to parse a project with hundreds of class files along with custom rules. While debugging I found the time taken in loading classes. I tried these changes where I found reduced time consumption. Actually, there is no use of these changes as there is a parallelLockMap in java.lang.ClassLoader and the performance is not related to these changes
Thanks, @jsotuyod and @oowekyala for the clarifications and Thanks @adangel for the testing results.

**Pull request closed without merging**
