### PR TITLE
[all] Update all XPath rules to XPath 2.0

### PR DESCRIPTION
**Pull request by oowekyala**
Thanks to #2354 we shouldn't see a performance degradation. Having that many more test cases ensures that that feature works properly.

### CODE REVIEW

**Comment by oowekyala** [comment]
There's a performance problem introduced by #2354 which causes a timeout of the build. Maybe we should do it the other way around: revert #2354, merge this PR, and reopen #2354 to fix the problem.

**Comment by adangel** [comment]
> There's a performance problem introduced by #2354 which causes a timeout of the build. Maybe we should do it the other way around: revert #2354, merge this PR, and reopen #2354 to fix the problem.

I don't think, that's necessary. This PR-branch provides a good indication, whether the performance problems are fixed or not. I agree, we should in this PR not mix in the fixes for XPath 2.0 rulechain and keep it separated.... unless the rules need to be fixed.
In case, we don't find a solution, we still can revert #2354 later and just not ship it (it's currently only on master, a SNAPSHOT version).

It seems to be at least these rules:
```
Label                                              Time (secs) Self Time (secs)  # Calls     Counter
JUnitSpelling                                           1.6127           1.6127       33         184
JUnitStaticSuite                                        1.7489           1.7489       33         184
SimplifyBooleanAssertion                                2.5099           2.5099       33         336
UnnecessaryBooleanAssertion                             2.6274           2.6274       33         336
UseAssertSameInsteadOfAssertTrue                       19.9390          19.9390       33       2,747
UseAssertNullInsteadOfAssertTrue                       20.1079          20.1079       33       2,747
UseAssertEqualsInsteadOfAssertTrue                     25.1632          25.1632       33       2,747
```
These are the rules, that take between 1.6 and 25.2 seconds. We have in this simple test only 33 different files, but the rule expressions are executed more often, up to 2,747 times...

Things I'd verify:
* Did we use rulechain for these rules with XPath 1.0 as well? If not, why not?
* Looking at [UseAssertEqualsInsteadOfAssertTrue](https://pmd.github.io/latest/pmd_rules_java_bestpractices.html#useassertequalsinsteadofasserttrue) it uses a complicated expression on the node PrimaryExpression. Obviously, we have 2,747 different PrimaryExpressions in the analyzed files. It uses once ancestor:: (not sure, whether that's particulary bad) and a couple of time typeIs.
* I guess, if want to be fully compatible, we would need to figure out a rule, how we can programmatically decide, that a rule (despite it can be run as rule chain) better not being run as rule chain... maybe we should exclude certain node types, that statistically appear very often (like PrimaryExpression). Or we could exclude rules, that use typeIs / ancestor (if that's part of the problem). Or exclude rules, that use more than 2 conditions...

wild guesses...

**Comment by oowekyala** [comment]
Thanks for scoping it down to those rules. I think one thing those rules have in common, is that they all use some other `//` expression somewhere in the expression. For example:

https://github.com/pmd/pmd/blob/17ddfd2a22eb815dfbb4346ec838ff8117a0a224/pmd-java/src/main/resources/category/java/errorprone.xml#L2205-L2206

Both `//ClassOrInterfaceType` and `//MarkerAnnotation`  enumerates all nodes in the tree. Because of the rulechain these traversals will be done at least once per method declaration, instead of at least once per file (which I guess saxon factors out). 

It looks like this is implemented inefficiently: `ancestor::ClassOrInterfaceDeclaration[//ClassOrInterfaceType[pmd-java:typeIs('junit.framework.TestCase')]...` should test only the supertypes, not all ClassOrInterfaceType in the file. But even if this is badly implemented, such a bad performance hit is not ok.

I think to begin with, we could try excluding rules that mention another unbounded path expression somewhere in the predicates (so it starts with `//`, or with `/`).

**Comment by adangel** [comment]
I've created a performance test - details see here:
https://github.com/adangel/scratchpad/tree/master/xpath-perf-tests/xpath-benchmark

And yes, it definitively has to do with these `//ClassOrInterfaceType` selectors...

> I think to begin with, we could try excluding rules that mention another unbounded path expression somewhere in the predicates (so it starts with `//`, or with `/`).

Agreed - I'll work on that in a separate PR. Once that is done, this PR should be again and can be merged. After that, we should improve these rules, where possible (at least for UseAssertEqualsInsteadOfAssertTrue it seems to be very possible).

> Both `//ClassOrInterfaceType` and `//MarkerAnnotation` enumerates all nodes in the tree. Because of the rulechain these traversals will be done at least once per method declaration, instead of at least once per file (which I guess saxon factors out).

Exactly - saxon alone performs in this case automatically better than jaxen. But the tests show, that after improving the queries, the rulechain execution is still faster than the normal one.

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">This changeset introduces 0 new violations, 1 new errors and 0 new configuration errors,<br />
removes 0 violations, 0 errors and 0 configuration errors.<br />
<a href="https://chunk.io/pmd/dc0151330ea54a6e9ab69a1c5d656106/diff/index.html">Full report</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by adangel** [comment]
See https://github.com/adangel/scratchpad/blob/master/xpath-perf-tests/pmd-benchmark/results-2020-03-29/summary.md

E.g. JunitStaticSuite now pops up as very slow...

**Comment by adangel** [comment]
I did shortly exclude rules, that use "ancestor::" from rulechain (see https://github.com/adangel/pmd/commit/37479a14d1caa233d3008641b319b97d4511e258). However, this didn't solve the performance problem for JUnitStaticSuite. It is roughly the same with/without rulechain.

I rewrote then this rule (and others, see https://github.com/adangel/pmd/commit/89f0cbeff339b25a7c589671f87a9f57734cc30e). It looks more promising, the benchmark runs now again within 4 minutes.
See the updated results: https://github.com/adangel/scratchpad/blob/master/xpath-perf-tests/pmd-benchmark/results-2020-03-29/summary.md

Compared to 6.22.0, we would be slower right now.

An interesting case is JUnit4TestShouldUseBeforeAnnotation vs. JUnit4TestShouldUseTestAnnotation. If we could make all the rules as fast as JUnit4TestShouldUseTestAnnotation...

**Comment by adangel** [comment]
Update:
* Replaced ProperCloneImplementation with a Java rule, now its 10x faster than with PMD 6.22.0
* Simplified AvoidDecimalLiteralsInBigDecimalConstructor by using typeres. Now this rule is only 1.5x slower than PMD 6.22.0 (before that simplicifcation it was 4.8x slower).

Next in the row:
* JUnitSpelling: currently 4.3x slower
* PositionLiteralsFirstIn(CaseInsensitive)Comparisons: currently 3.1x slower
* AbstractClassWithoutAbstractMethod: currently 2.9x slower

**Comment by adangel** [comment]
I think, this is ready now.

Final numbers (in comparison to 6.22.0):
* Overall duration is down to 151s (from 231s in 6.22.0): 1.5x faster
* JUnitSpelling: 2.5x faster (as a Java rule)
* PositionLiteralsFirstIn(CaseInsensitive)Comparisons: 8x faster (as Java rules)
* AbstractClassWithoutAbstractMethod: 25x faster (?)

I also converted JUnitStaticSuite, but that didn't help - it's still 3x slower even as a Java rule.
Numbers are here: https://github.com/adangel/scratchpad/tree/master/xpath-perf-tests/pmd-benchmark/results-2020-04-17

**Comment by oowekyala** [comment]
@adangel Very nice! I added some optimisations to the saxon node wrappers based on profiling. I'll run my benchmark and post the results

**Comment by oowekyala** [comment]
Ok so here are my results:

https://github.com/oowekyala/scratchpad/blob/bench-xpath-update/xpath-perf-tests/pmd-benchmark/method.md

I tried with different threading configurations because I wanted to ensure there was no resource contention for the name pool. That's because the name pool we use is static and shared between threads, yet every name allocation is synchronized on the pool (saxon warns against this being a bottleneck).


So here are some general trends:
* There is no measurable contention on the name pool, and using thread local name pools is measurably worse (I did a few samples with a revision that tried that)
* These optimisations have a measurable impact on all tested configurations. For example, with one thread, execution time is down by roughly 10% compared to without these optimisations (averaging on jdk 8 and 11). With several threads this is less impactful.

So it's safe to say that this is a positive change

**Comment by adangel** [comment]
@oowekyala  Awesome! I've run my tests today and the overall duration is down to 130s (from 237s) -> 1.8x faster.
I guess your refactoring with the Attributes and NameTests improved it additionally.

I'll merge that now.

**Pull request merged**
