### PR TITLE
[java] New rule SimplifiableTestAssertion

### LINKED ISSUE #2908: [java] Merge Junit assertion simplification rules
The following rules:

* bestpractices.xml
  * UseAssertEqualsInsteadOfAssertTrue
  * UseAssertNullInsteadOfAssertTrue
  * UseAssertSameInsteadOfAssertTrue
  * UseAssertTrueInsteadOfAssertEquals
* design.xml/SimplifyBooleanAssertion

could be merged together into a new `SimplifiableTestAssertion` rule. This would 
* make them simpler to reference, you probably want all of them, and SimplifyBooleanAssertion is alone in design.xml
* simplify the implementation (currently some logic is duplicated between rules)

Category would likely be bestpractices.xml

Motivation for the rule would be readability + better error messages

**Additional context**
#2899 reimplements many of those, but not SimplifyBooleanAssertion. We can merge them later

### PR DESCRIPTION
**Pull request by oowekyala**
## Describe the PR

Fixes #2908. Note that we don't look for boxed booleans like UseAssertTrueInsteadOfAssertEquals does. I think the rule is complicated enough...

The highlights of this rule, is 
* complete handling of both positive and negative assertions (eg assertTrue(!a), assertFalse(!a)), which eg is lacking in UseAssertEqualsInsteadOfAssertTrue
* better error messages (we suggest to use the correct method)

## Related issues

- Fixes #2908 

## Ready?

- [ ] Added unit tests for fixed bug/feature
- [ ] Passing all unit tests
- [ ] Complete build `./mvnw clean verify` passes (checked automatically by github actions)
- [ ] Added (in-code) documentation (if needed)

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">This changeset changes 0 violations,<br />
introduces 1641 new violations, 0 new errors and 0 new configuration errors,<br />
removes 1724 violations, 0 errors and 0 configuration errors.<br />
<a href="https://chunk.io/pmd/ae1ccce285aa430a8e58d5663b616f51/diff/index.html">Full report</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by jsotuyod** [comment]
This seems to have introduced some false negatives (we lost ~80 violations in spite of handling more scenarios).

By inspecting the regression we have missed:

```java
assertEquals(true, context.lookupVariable("a1"));
```

so we seem to be missing unit tests for `assertEquals(true, …)`, `assertEquals(false, …)` and boxed `Booleans`.

**Comment by jsotuyod** [comment]
We also are somehow missing to report this one…

```java
assertTrue(!Thread.currentThread().getName().equals(event.content));
```

Possibly the mixed usage of `equals` and `!` confusing our logic…

**Comment by oowekyala** [comment]
Thanks for reviewing

>     assertEquals(true, context.lookupVariable("a1"));

This is a true negative though. `context.lookupVariable` most likely has return type `Object`. If you use `assertTrue`, the code doesn't compile anymore. This is explicitly checked by the new implementation and tested here:

https://github.com/pmd/pmd/pull/3363/files#diff-0d9f063f93dd465f5ff1f2d450ef0ad5557598e8622fbf7e393ee65a98b8f621R500

>     assertTrue(!Thread.currentThread().getName().equals(event.content));

> Possibly the mixed usage of equals and ! confusing our logic…

 I would think it's rather due to the call chain... IIRC we give up if there isn't a single method call, which is apparently too simple


Something else I found in the report: for the following violation

    assertFalse(pc1.hashCode() == pc2.hashCode());

we recommend using assertNotSame instead of assertNotEquals.


@jsotuyod I wonder, how you diffed the two reports to find the violations that disappeared? I don't see an easy way to do that

**Comment by jsotuyod** [comment]
> @jsotuyod I wonder, how you diffed the two reports to find the violations that disappeared? I don't see an easy way to do that

No easy way… but some heuristics. I used the file filter looking for java files where the number of differences was an odd number, so that I'm certain there is at least 1 that is not a replacement from one message/rule to another.

Also, having a odd number for paging results (25) has proved to be an issue when looking for which one we dropped.

**Comment by jsotuyod** [comment]
@oowekyala sweet! This is way more accurate!

I did find a couple of interesting scenarios 'though, but the huge majority are perfect.

We are somehow missing [on this snippet](https://github.com/spring-projects/spring-framework/tree/v5.0.6.RELEASE/spring-webmvc/src/test/java/org/springframework/web/servlet/view/BaseViewTests.java#L336)

```java
assertTrue(getApplicationContext() == wac);
```

where the old rule properly hinted at `assertSame`.

Then, I also came across [a really interesting case](https://github.com/spring-projects/spring-framework/blob/f5e8f4983f7653169f3da8a3287499fce93cadd4/spring-context-support/src/test/java/org/springframework/cache/jcache/interceptor/JCacheKeyGeneratorTests.java#L152-L154):

```java
assertTrue("Unexpected parameters: expected: "
        + Arrays.toString(this.expectedParams) + " but got: " + Arrays.toString(params),
    Arrays.equals(expectedParams, params));
```

We are actually ok missing this one (`assertEquals` would not be a replacement here, but `assertArrayEquals` would). This sparked 2 thoughts:

1. Not for this PR, but at some point we may want to add the array versions too…
2. We are not properly handling the special case of `Objects.equals`, are we? Possibly worth including a test case.

**Comment by oowekyala** [comment]
> We are somehow missing [on this snippet](https://github.com/spring-projects/spring-framework/tree/v5.0.6.RELEASE/spring-webmvc/src/test/java/org/springframework/web/servlet/view/BaseViewTests.java#L336)

This is because the class in which this thing is is not a junit class. The detection strategy of the rule should be based on whether the methods are actually from junit, not whether there are tests in the file... This is trivial in pmd 7 but harder in pmd 6.

> We are not properly handling the special case of Objects.equals, are we? Possibly worth including a test case.
> Not for this PR, but at some point we may want to add the array versions too…

Good points, thanks!

**Comment by adangel** [comment]
> Also, having a odd number for paging results (25) has proved to be an issue when looking for which one we dropped.

I've created a enhancement issue for this: https://github.com/pmd/pmd-regression-tester/issues/95

**Review by adangel — APPROVED** [review]

**Pull request merged**
