### PR TITLE
[core] RuleContext as threadlocal

### LINKED ISSUE #2019: [core] Insufficient deprecation warnings for XPath attributes
**Affects PMD Version:** 6.18

**Rule:** Builtin rulesets 'Codestyle' and 'Design'

**Description:**
Starting with 6.18 I get deprecation warnings for the builtin rulesets codestyle and design.
I tracked down the two rulesets but there might be other builtin rulesets with warnings.

> Use of deprecated attribute 'VariableDeclaratorId/@Array' in XPath query
> Use of deprecated attribute 'VariableDeclaratorId/@ArrayDepth' in XPath query
> Use of deprecated attribute 'FieldDeclaration/@Array' in XPath query
> Use of deprecated attribute 'FieldDeclaration/@VariableName' in XPath query
> Use of deprecated attribute 'FieldDeclaration/@ArrayDepth' in XPath query
> Use of deprecated attribute 'PrimitiveType/@Array' in XPath query
> Use of deprecated attribute 'PrimitiveType/@ArrayDepth' in XPath query

The problem with this warning is that there is no indication of where it is coming from or which files are affected, which might be confusing. Examples: 
https://github.com/teamed/qulice/issues/1048
https://github.com/aistomin/maven-browser/issues/54

**Code Sample demonstrating the issue:**

Reference builtin rules codestyle or design in your ruleset:
```
<rule ref="category/java/codestyle.xml">
</rule>
...
<rule ref="category/java/design.xml">
</rule>
```

**Running PMD through:** *Gradle*

### PR DESCRIPTION
**Pull request by adangel**
Before submitting a PR, please check that:
 - [x] The PR is submitted against `master`. The PMD team will merge back to support branches as needed.
 - [x] `./mvnw clean verify` passes. This will [build](https://github.com/pmd/pmd/blob/master/BUILDING.md) and test PMD, execute PMD and checkstyle rules. [Check this for more info](https://github.com/pmd/pmd/blob/master/CONTRIBUTING.md#code-style)

**PR Description:**

Introduce a rule context holder, to have access to the
current rule. This is used to log deprecated xpath attributes.

The deprecated attributes are now logged once per rule and not
once at all.

RuleContext can be considered the "analysis context". Each thread
uses its own rule context, established by PmdRunnable.

Fixes #2019

Note: #2044 is still required, because the deprecation messages are only logged once per JVM due to static caching.

The log messages might look like this:

```
Okt. 05, 2019 8:13:57 NACHM. net.sourceforge.pmd.lang.ast.xpath.Attribute getValue
WARNING: Use of deprecated attribute 'MethodDeclarator/@Image' in XPath query in rule 'Code Style/BooleanGetMethodName'.
Okt. 05, 2019 8:13:57 NACHM. net.sourceforge.pmd.lang.ast.xpath.Attribute getValue
WARNING: Use of deprecated attribute 'MethodDeclarator/@Image' in XPath query in rule 'Code Style/ShortMethodName'.
Okt. 05, 2019 8:13:57 NACHM. net.sourceforge.pmd.lang.ast.xpath.Attribute getValue
WARNING: Use of deprecated attribute 'MethodDeclarator/@Image' in XPath query in rule 'Design/TooManyMethods'.
Okt. 05, 2019 8:13:57 NACHM. net.sourceforge.pmd.lang.ast.xpath.Attribute getValue
WARNING: Use of deprecated attribute 'MethodDeclarator/@Image' in XPath query in rule 'Error Prone/CallSuperFirst'.
Okt. 05, 2019 8:13:57 NACHM. net.sourceforge.pmd.lang.ast.xpath.Attribute getValue
WARNING: Use of deprecated attribute 'MethodDeclarator/@Image' in XPath query in rule 'Error Prone/CallSuperLast'.
Okt. 05, 2019 8:13:57 NACHM. net.sourceforge.pmd.lang.ast.xpath.Attribute getValue
WARNING: Use of deprecated attribute 'MethodDeclarator/@Image' in XPath query in rule 'Error Prone/CloneMethodReturnTypeMustMatchClassName'.
Okt. 05, 2019 8:13:57 NACHM. net.sourceforge.pmd.lang.ast.xpath.Attribute getValue
WARNING: Use of deprecated attribute 'MethodDeclarator/@Image' in XPath query in rule 'Error Prone/CloneThrowsCloneNotSupportedException'.
Okt. 05, 2019 8:13:57 NACHM. net.sourceforge.pmd.lang.ast.xpath.Attribute getValue
WARNING: Use of deprecated attribute 'MethodDeclarator/@Image' in XPath query in rule 'Error Prone/EmptyFinalizer'.
Okt. 05, 2019 8:13:57 NACHM. net.sourceforge.pmd.lang.ast.xpath.Attribute getValue
WARNING: Use of deprecated attribute 'MethodDeclarator/@Image' in XPath query in rule 'Error Prone/CloneMethodMustBePublic'.
Okt. 05, 2019 8:13:57 NACHM. net.sourceforge.pmd.lang.ast.xpath.Attribute getValue
WARNING: Use of deprecated attribute 'MethodDeclarator/@Image' in XPath query in rule 'Error Prone/FinalizeDoesNotCallSuperFinalize'.
Okt. 05, 2019 8:13:57 NACHM. net.sourceforge.pmd.lang.ast.xpath.Attribute getValue
WARNING: Use of deprecated attribute 'MethodDeclarator/@Image' in XPath query in rule 'Error Prone/FinalizeOnlyCallsSuperFinalize'.
Okt. 05, 2019 8:13:57 NACHM. net.sourceforge.pmd.lang.ast.xpath.Attribute getValue
WARNING: Use of deprecated attribute 'MethodDeclarator/@Image' in XPath query in rule 'Error Prone/FinalizeOverloaded'.
Okt. 05, 2019 8:13:57 NACHM. net.sourceforge.pmd.lang.ast.xpath.Attribute getValue
WARNING: Use of deprecated attribute 'MethodDeclarator/@Image' in XPath query in rule 'Error Prone/FinalizeShouldBeProtected'.
Okt. 05, 2019 8:13:57 NACHM. net.sourceforge.pmd.lang.ast.xpath.Attribute getValue
WARNING: Use of deprecated attribute 'MethodDeclarator/@Image' in XPath query in rule 'Error Prone/JUnitSpelling'.
Okt. 05, 2019 8:13:57 NACHM. net.sourceforge.pmd.lang.ast.xpath.Attribute getValue
WARNING: Use of deprecated attribute 'MethodDeclarator/@Image' in XPath query in rule 'Error Prone/JUnitStaticSuite'.
Okt. 05, 2019 8:13:57 NACHM. net.sourceforge.pmd.lang.ast.xpath.Attribute getValue
WARNING: Use of deprecated attribute 'MethodDeclarator/@Image' in XPath query in rule 'Error Prone/ProperCloneImplementation'.
Okt. 05, 2019 8:13:57 NACHM. net.sourceforge.pmd.lang.ast.xpath.Attribute getValue
WARNING: Use of deprecated attribute 'MethodDeclarator/@Image' in XPath query in rule 'Error Prone/SuspiciousEqualsMethodName'.
```

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">This changeset introduces 0 new violations, 16 new errors and 0 new configuration errors,<br />
removes 0 violations, 16 errors and 0 configuration errors.<br />
<a href="https://chunk.io/pmd/6e3867eb5747416e8c7cd57d7f1478cb/diff/index.html">Full report</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by jsotuyod** [comment]
I'm unsure about the semantics of this change…

The `RuleContext` provides context information for rules… having it keep around the current rule (and thus introducing high coupling between rules and rule context) seems forced, as the rules themselves don't actually need to know which rule is currently being run.

The `Attribute` is accessing the `RuleContext` but it really doesn't care about it at all, only about this new "currently executing rule" attribute.

Also, we are introducing a global `RuleContextHolder` that may or may not retrieve a context depending on from where / when you are making the call…

I don't think the `RuleContext` is the right place to keep this info.

Maybe, we should aim to:

1. Build the global `AnalysisContext` described on https://github.com/pmd/pmd/pull/1371#issuecomment-538688849
2. Have within that context a `TheadLocal<Rule>` with the current rule, initialized / cleared as you do on this PR, and have `Attribute` access it from there; keeping `RuleContext` clean.

**Comment by adangel** [comment]
> I'm unsure about the semantics of this change…
> 
> The `RuleContext` provides context information for rules…
I've actually seen the rule context more like an "current PMD execution context", since the rule violations are reported through this rule context (via `ruleContext.getReport().addRuleViolation(...)`).


> The `Attribute` is accessing the `RuleContext` but it really doesn't care about it at all, only about this new "currently executing rule" attribute.
That's true, I only use the current rule. So, I could easily change the implementation just be a "CurrentRuleAccessor", which contains a thread local for the current rule. All the technique is the same, we are just talking about naming/API here.
Btw. I was shortly thinking about doing something like `ruleContext.getReport().addError(...)`, but I didn't want to go that far yet. But this made me thinking about: Are these errors, that we report here (deprecated attributes in xpath rules) of the same type as errors during rule execution (such as null pointers)? Should they be in the report? Or should they just be in the console log? Are they only interesting during development of a rule? ...


> Also, we are introducing a global `RuleContextHolder` that may or may not retrieve a context depending on from where / when you are making the call…
That was extremely funny to see - since we have no consistent way to execute PMD programmatically, the unit tests all do it in different ways. I first wanted to integrate it in PmdRunnable, but that is not always used in unit tests...


> 
> I don't think the `RuleContext` is the right place to keep this info.
> 
> Maybe, we should aim to:
> 
>     1. Build the global `AnalysisContext` described on [#1371 (comment)](https://github.com/pmd/pmd/pull/1371#issuecomment-538688849)
> 
>     2. Have within that context a `TheadLocal<Rule>` with the current rule, initialized / cleared as you do on this PR, and have `Attribute` access it from there; keeping `RuleContext` clean.

So you think, we should already build such a `AnalysisContext` on master? I've moved #1371 some time ago to 7.0.0...

**Comment by adangel** [comment]
This is replaced by #2425

**Pull request closed without merging**
