### PR TITLE
[java] Fix #4008 - ImmutableField FN with field assigned only in initializer

### LINKED ISSUE #4008: [java] ImmutableField not reporting fields that are only initialized in the declaration
**Affects PMD Version:** 
6.44, 6.45, 6.46

**Rule:**
ImmutableField

Please provide the rule name and a link to the rule documentation:
https://pmd.github.io/pmd-6.46.0/pmd_rules_java_design.html#immutablefield

**Description:**

Fields only initialized in the declaration can be made final. PMD does not report such problem since 6.44.0.

**Code Sample demonstrating the issue:**

```
public class Foo {
    private String variable = "hello";

    public String getVariable() {
        return variable;
    }
}
```

**Expected outcome:**

PMD should report a violation at line 2, but doesn't. This is a false-negative.

**Running PMD through:** *CLI, Maven*

Some of my personal idea: many issues related to ImmutableField (#3874 #3981 #3998 #4004) have occurred since PMD 6.44.0. And the solution is to keep adding annotations to `defaultSuppressionAnnotations`. Personally I don't think it a good idea...

In 6.44.0 PMD introduced some changes in the ImmutableFieldRule in #3855 , can we investigate it a little bit more?

### PR DESCRIPTION
**Pull request by oowekyala**
## Related issues

- Fixes #4008

## Ready?

- [ ] Added unit tests for fixed bug/feature
- [ ] Passing all unit tests
- [ ] Complete build `./mvnw clean verify` passes (checked automatically by github actions)
- [ ] Added (in-code) documentation (if needed)

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">Compared to master:<br />
This changeset changes 0 violations,<br />
introduces 462 new violations, 0 new errors and 0 new configuration errors,<br />
removes 764 violations, 2 errors and 6 configuration errors.<br />
<a href="https://chunk.io/pmd/8712af1d9a1441f7b0738c80b6d81738/diff1/index.html">Full report</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by oowekyala** [comment]
Seems like my change removes violations on fields that are never assigned (even in their initializer). Should we report them? It may be set via reflection, but also be a legit mistake. It doesn't feel like the correct rule to report that though. In any case the error message should be different in this case...

**Comment by HaelC** [comment]
Thanks @oowekyala. It seems that with the code change, `defaultSuppressionAnnotations()` seems not necessary in ImmutableFieldRule now. I tried to delete [line 38-49](https://github.com/pmd/pmd/blob/5c05c105b78a351234d86970695ca6c3185becf7/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/ImmutableFieldRule.java#L38-L49) and [line 7-8](https://github.com/pmd/pmd/blob/5c05c105b78a351234d86970695ca6c3185becf7/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/ImmutableFieldRule.java#L7-L8), and the build remains successful. Do we want to remove those lines?

**Review by adangel — APPROVED** [review]
Thanks!

I've verified the other issues with annotations and this PR solves them all.

Now ImmutableField only considers fields, that are initialized once and never changed - either in the constructor or in the declaration.
If the field is not initialized at all (which is the typical case when a framework will set the value by reflection), the rule won't trigger now for such fields.

I'll remove the suppressed annotations added lately, as they are not needed anymore.

We can think for the next version about removing/deprecating the property `ignoredAnnotations` for this rule entirely. Not sure about the class-level lombok annotations though...

**Comment by oowekyala** [comment]
> However, upon code review, I think that this is missing initializations on non-static initializers

I think you're right Juan, would you open an issue? I think it is rare enough that it has low priority though. The rule also does not handle very complicated control flow yet. In pmd 7 it uses the new data flow logic which is more robust, and which already handles initializers properly

**Pull request merged**
