### PR TITLE
[core] Fix a NPE in buildUsageText

### PR DESCRIPTION
**Pull request by XenoAmess**
My bad. Sorry about that.

## Describe the PR

https://github.com/pmd/pmd/pull/2730#discussion_r477273111_

## Related issues

- Fixes #

## Ready?

- [x] Added unit tests for fixed bug/feature
- [x] Passing all unit tests
- [x] Complete build `./mvnw clean verify` passes (checked automatically by travis)
- [ ] Added (in-code) documentation (if needed)

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">This changeset introduces 0 new violations, 0 new errors and 0 new configuration errors,<br />
removes 0 violations, 0 errors and 0 configuration errors.<br />
<a href="https://chunk.io/pmd/ae4e2f76e876401db1f4ddcb6718de7b/diff/index.html">Full report</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by oowekyala — COMMENTED** [review]
Thanks! Would be nice to add a test case. I think PMDCommandLineInterfaceTest is the place

**Comment by XenoAmess** [comment]
@oowekyala 
Hi.
I added the Unit test.
I can only make sure that test is:
1. can pass.
2. can cover the NPE we found.
I'm not familiar with JCommand you use, so I can just make it like this.
Please refine if you want.

Also, I waste 10min+ on the order of imports on that test file, and I found out I cannot make it correct. need help about that.

**Comment by oowekyala** [comment]
Thanks for your updates! I now think, the NPE was in dead-code. The PMD CLI doesn't use subcommands, and this stringBuilder is only filled in if they were some... The description is also wrong: `"Optional arguments that may be put before or after the mandatory arguments" + allCommandsDescription`, which is not true, since this is about subcommands. Mocking commands like you did in the test would have exposed the NPE, but this is not a realistic usage of the `JCommander` object. That object is always created with a `PMDParameters` as argument...

I think this actually better be removed for now. Maybe we'll use subcommands at some point (#2234), but for now this code is useless.

I'll push some updates

**Review by adangel — APPROVED** [review]

**Pull request merged**
