### PR TITLE
[java] Simplify check for 'Test' annotation in JUnitTestsShouldIncludeAssertRule.

### LINKED ISSUE #1365: [java] JUnitTestsShouldIncludeAssert false positive
**Affects PMD Version:** 6.7.0

**Rule:** JUnitTestsShouldIncludeAssert

**Description:** The following two test cases are identical, but for the precise text of the annotation before them.  But they give different warnings in PMD.  My students encountered this with PMD v6.2.0, and I've just confirmed locally that it still occurs on 6.7.0.

**Code Sample demonstrating the issue:**
```java
import org.junit.Test;

class Style {
  // This triggers the JUnitTestsShouldIncludeWarning rule
  @org.junit.Test(expected = IllegalArgumentException.class)
  public void moveOutOfBoundsFrom() {
    doSomething();
  }
  // This does not
  @Test(expected = IllegalArgumentException.class)
  public void moveOutOfBoundsFrom() {
    doSomething();
  }
}
```

**Running PMD through:** Other (custom too invoking `PMD.main` programmaticallyl, referencing `<rule ref="category/java/bestpractices.xml/JUnitTestsShouldIncludeAssert" />` to load this rule)

### PR DESCRIPTION
**Pull request by winder**
Please, prefix the PR title with the language it applies to within brackets, such as *[java]* or *[apex]*. If not specific to a language, you can use *[core]*

Before submitting a PR, please check that:
 - [x] The PR is submitted against `master`. The PMD team will merge back to support branches as needed.
 - [ ] `./mvnw test` passes.
 - [X] `./mvnw pmd:check` passes.
 - [X] `./mvnw checkstyle:check` passes. [Check this for more info](https://github.com/pmd/pmd/blob/master/CONTRIBUTING.md#code-style)

**PR Description:**

Resolves #1365

`mvnw test` failed for me on master so I wasn't able to run it.

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">This changeset introduces 0 new violations and 0 new errors,<br />
removes 0 violations and 2 errors. <a href="http://chunk.io/pmd/2160e31a0b9b4279b73e5f7d80366b8f/diff/index.html">Full report</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by adangel** [comment]
@winder, Thanks for the PRs. It looks good.

Did you verify #1365 ? Does your change fix the issue?

> mvnw test and mvnw pmd:check fail for me on master so I wasn't able to run them.

This should be the case - what error(s) do you get?

**Comment by winder** [comment]
# Testing
yes, the reported issue. I split the original test into 2 files and ran them against master and my branch using these files:

**Style1.java**
```java
import org.junit.Test;

class Style {
  // This triggers the JUnitTestsShouldIncludeWarning rule
  @org.junit.Test(expected = IllegalArgumentException.class)
  public void moveOutOfBoundsFrom() {
    doSomething();
  }
}
```

**Style2.java**
```java
import org.junit.Test;

class Style {
  // This does not
  @Test(expected = IllegalArgumentException.class)
  public void moveOutOfBoundsFrom() {
    doSomething();
  }
}
```


**Reproduced on master**:
```
/opt/pmd/pmd-dist/target/pmd-bin-6.9.0-SNAPSHOT/bin$ ./run.sh pmd -d Style1.java -f text -R category/java/bestpractices.xml
Oct 08, 2018 12:11:15 PM net.sourceforge.pmd.PMD processFiles
WARNING: This analysis could be faster, please consider using Incremental Analysis: https://pmd.github.io/latest/pmd_userdocs_incremental_analysis.html
/opt/pmd/pmd-dist/target/pmd-bin-6.9.0-SNAPSHOT/bin/Style1.java:1:	Avoid unused imports such as 'org.junit.Test'
/opt/pmd/pmd-dist/target/pmd-bin-6.9.0-SNAPSHOT/bin/Style1.java:6:	JUnit tests should include assert() or fail()

/opt/pmd/pmd-dist/target/pmd-bin-6.9.0-SNAPSHOT/bin$ ./run.sh pmd -d Style2.java -f text -R category/java/bestpractices.xml
Oct 08, 2018 12:11:27 PM net.sourceforge.pmd.PMD processFiles
WARNING: This analysis could be faster, please consider using Incremental Analysis: https://pmd.github.io/latest/pmd_userdocs_incremental_analysis.html
```

**Resolved on this branch**:
```
/opt/pmd/pmd-dist/target/pmd-bin-6.9.0-SNAPSHOT/bin$ ./run.sh pmd -d Style1.java -f text -R category/java/bestpractices.xml
Oct 08, 2018 12:24:15 PM net.sourceforge.pmd.PMD processFiles
WARNING: This analysis could be faster, please consider using Incremental Analysis: https://pmd.github.io/latest/pmd_userdocs_incremental_analysis.html
/opt/pmd/pmd-dist/target/pmd-bin-6.9.0-SNAPSHOT/bin/Style1.java:1:	Avoid unused imports such as 'org.junit.Test'

/opt/pmd/pmd-dist/target/pmd-bin-6.9.0-SNAPSHOT/bin$ ./run.sh pmd -d Style2.java -f text -R category/java/bestpractices.xml
Oct 08, 2018 12:24:26 PM net.sourceforge.pmd.PMD processFiles
WARNING: This analysis could be faster, please consider using Incremental Analysis: https://pmd.github.io/latest/pmd_userdocs_incremental_analysis.html
```
------

# mvnw test / mvnw pmd:check issues

I tried running pmd:check again, previously there were about 40 errors, but now it seems to be working. I'm not sure what changed.

`mvnw test` still fails due to missing classes, should I create a new issue for this?

**mvnw test** errors during **PMD Test Framework**:
```
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.353 s <<< FAILURE! - in net.sourceforge.pmd.testframework.RuleTstTest
[ERROR] shouldCallStartAndEnd(net.sourceforge.pmd.testframework.RuleTstTest)  Time elapsed: 0.046 s  <<< ERROR!
java.lang.NoClassDefFoundError: org/jaxen/Function
	at net.sourceforge.pmd.testframework.RuleTstTest.shouldCallStartAndEnd(RuleTstTest.java:47)
Caused by: java.lang.ClassNotFoundException: org.jaxen.Function
	at net.sourceforge.pmd.testframework.RuleTstTest.shouldCallStartAndEnd(RuleTstTest.java:47)

[ERROR] shouldAssertLinenumbersSorted(net.sourceforge.pmd.testframework.RuleTstTest)  Time elapsed: 0.009 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class net.sourceforge.pmd.lang.xpath.Initializer
	at net.sourceforge.pmd.testframework.RuleTstTest.shouldAssertLinenumbersSorted(RuleTstTest.java:92)
```

**Comment by adangel** [comment]
Awesome! Then we should just add a test case for the case, you just fixed.
Please extend the file https://github.com/pmd/pmd/blob/master/pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/JUnitTestsShouldIncludeAssert.xml with your two test cases, thanks!

About the build problem: What's the result, if you execute `./mvnw clean verify`? That's executes all the steps mentioned above (it builds, runs the tests, runs pmd, and runs checkstyle).

The problem with just running the "test" goal is, that we don't have the jaxen library yet... (it's only available at the end of the "package" goal, we need to shade the interface `org.w3c.dom.UserDataHandler` away, in order to avoid duplicated classes - this interface is already provided as a java api...).
I'll update the pull-request template, to use just `./mvnw clean verify`.

**Comment by winder** [comment]
Yes, `./mvnw clean verify` runs fine

**Comment by jsotuyod** [comment]
@winder awesome! so just add the test scenario under https://github.com/pmd/pmd/blob/master/pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/JUnitTestsShouldIncludeAssert.xml and this should be ready to merged!

**Comment by winder** [comment]
@jsotuyod @adangel this should be good to go.

**Comment by jsotuyod** [comment]
@winder merged, thanks again for the PR! You are halfway there to getting your [hacktoberfest t-shirt](https://hacktoberfest.digitalocean.com) if you are taking part of that!

**Pull request merged**
