### PR TITLE
[java] Issue 968 Add logic to handle lombok private constructors with utility classes

### PR DESCRIPTION
**Pull request by clem0110**

### CODE REVIEW

**Comment by jsotuyod** [comment]
@clem0110 welcomed and thanks for the contribution! Very thorough test coverage, really appreciated.

The PR looks very good. This fetching of annotations is a good candidate for #956.

**Comment by jsotuyod** [comment]
This is merged and ready for 6.2.0.

@clem0110 if in your PR you include something such as "fixes #XXX" or "resolves #XXX", the issue with number XXX will be automatically closed upon merging 👍

**Comment by jfxg** [comment]
I run into this same issue re: NoArgsConstructor except I'm running PMD against delomboked code. It looks like @clem0110 fix focuses on identifying the lombok annotation and ignoring the rest of the rules, but in my source that PMD complains about there is no Lombok annotation. Instead, the private constructor exists but is annotated:

```
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    private MyClass() {
    }
```

Is a different fix needed? Or will the above fix also cover this case?

**Comment by adangel** [comment]
@jfxg PMD won't flag this as a potential utility class, because here the private constructor is already there. If you are seeing a different violation (e.g. different rule), please open a new issue.

**Comment by jfxg** [comment]
First, I am using a bit older version of PMD (5.4.1), so it might behave differently, but it seemed relevant that I was seeing the same issue here that was only just fixed in 6.2. It's possible 5.4 is behaving differently. I'm working on importing 6.2 into our builds to confirm.

But, just to clarify, this *is* the same UseUtilityClass rule that is failing in the delomboked code with the constructor.

source in MyClass.java:
```
package com.my.test;

import lombok.AccessLevel;
import lombok.NoArgsConstructor;

@NoArgsConstructor(access = AccessLevel.PRIVATE)
public class MyClass {
    public static String foo(){
        return "bar";
    }
}
```

PMD failure report:
```

# | File | Line | Problem
-- | -- | -- | --
1 | /local/workplace/[...snip...]/build/private/generated-src-delomboked/com/my/test/MyClass.java | 4 | All  methods are static.  Consider using a utility class instead.  Alternatively, you could add a private constructor or make the class  abstract to silence this warning.
```
The problem links to 'https://pmd.github.io/pmd-5.4.1/pmd-java/rules/java/design.html#UseUtilityClass' which is a dead link in that version, but you can see the rule is java/design "UseUtilityClass"

And the source for the Delomboked source the PMD is inspecting at .../build/private/generated-src-delomboked/com/my/test/MyClass.java:
```
// Generated by delombok at Mon Apr 23 16:00:06 PDT 2018
package com.my.test;

public class MyClass {
    public static String foo() {
        return "bar";
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    private MyClass() {
    }
}
```

**Comment by jfxg** [comment]
I just pulled the delomboked source into my project as the actual test class, and confirmed the failure, you could try to reproduce as well:

```
package com.my.test;

public class MyClass {
    @SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    private MyClass() {
    }

    public static String foo(){
        return "bar";
    }
}
```

Interestingly it passes if I remove either of the annotations on the constructor. PMD detects the constructor and doesn't fail the rule if only `@java.lang.SuppressWarnings("all")` or only `@javax.annotation.Generated("lombok")` is present. But if both of them are on the constructor, it fails.

**Comment by jfxg** [comment]
All of which makes me think this is in fact a different bug...

**Comment by adangel** [comment]
I've just tested it, this seems to be a different and old bug, that is already fixed. This file is not flagged anymore with 6.2.0.

**Pull request merged**
