### PR TITLE
Revisit unused private method rule

### PR DESCRIPTION
**Pull request by punkratz312**
## Enhance Clarity and Maintainability

Divide code into smaller functions, improving readability and maintainability. This helps identify bugs and provides clarity regarding false positives, ensuring accurate detection of code segments. This approach will assist in future identification efforts.

This legacy code is written in an imperative style, coupled through fields instead of using a fluid API. I recommend merging the cleanup, as it's primarily a refactoring effort to locate the actual bug, with the tests still passing.

@jsotuyod please see yourself:

failures:
```
public method called by private method
private method called by private method
public method not called by public method
public and public method not called
public and private method not called
```
tests:
```
<?xml version="1.0" encoding="UTF-8"?>
<test-data
        xmlns="http://pmd.sourceforge.net/rule-tests"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://pmd.sourceforge.net/rule-tests http://pmd.sourceforge.net/rule-tests_1_0_0.xsd">
    <test-code>
        <description>public method called by public method</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
                public class Foo {
                    public void bar() {
                        fooPublic();
                    }
                    public void fooPublic() {}
                }
            ]]>
        </code>
    </test-code>
    <test-code>
        <description>public method called by private method</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
                public class Foo {
                    private void bar() {
                        fooPublic();
                    }
                    public void fooPublic() {}
                }
            ]]>
        </code>
    </test-code>
    <test-code>
        <description>private method called by public method</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
                public class Foo {
                    public void bar() {
                        fooPrivate();
                    }
                    private void fooPrivate() {}
                }
            ]]>
        </code>
    </test-code>
    <test-code>
        <description>private method called by private method</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
                public class Foo {
                    private void bar() {
                        fooPrivate();
                    }
                    private void fooPrivate() {}
                }
            ]]>
        </code>
    </test-code>
    <test-code>
        <description>public method not called by public method</description>
        <expected-problems>1</expected-problems>
        <code><![CDATA[
                public class Foo {
                    public void bar() {
                    }
                    public void fooPublic() {}
                }
            ]]>
        </code>
    </test-code>
    <test-code>
        <description>private method not called by public method</description>
        <expected-problems>1</expected-problems>
        <code><![CDATA[
                public class Foo {
                    public void bar() {
                    }
                    private void fooPrivate() {}
                }
            ]]>
        </code>
    </test-code>
    <test-code>
        <description>public and public method not called</description>
        <expected-problems>2</expected-problems>
        <code><![CDATA[
                public class Foo {
                    public void bar() {}
                    public void fooPublic() {}
                }
            ]]>
        </code>
    </test-code>
    <test-code>
        <description>public and private method not called</description>
        <expected-problems>2</expected-problems>
        <code><![CDATA[
                public class Foo {
                    public void bar() {}
                    private void fooPrivate() {}
                }
            ]]>
        </code>
    </test-code>
    <test-code>
        <description>private and private method not called</description>
        <expected-problems>2</expected-problems>
        <code><![CDATA[
                public class Foo {
                    private void bar() {}
                    private void fooPrivate() {}
                }
            ]]>
        </code>
    </test-code>
```
image

### CODE REVIEW

**Review by oowekyala — CHANGES_REQUESTED** [review]
Hello, I'm a bit confused about the point of this PR.

> This legacy code is written in an imperative style, coupled through fields instead of using a fluid API. I recommend merging the cleanup, as it's primarily a refactoring effort to locate the actual bug, with the tests still passing.

This is not legacy code and there is no coupling through fields. If by imperative style you mean we use local variables, then that would be true, but I don't think it's a bad thing.  IMO the code as it was was easie to read through and understand at a glance. Splitting it into that many methods makes it appear more complex than it actually is. What was before simple straight line code is now split into many methods. IMO the one place where we could increase readability is to extract a method from the bigger lambda.

It might help to take a step back and understand what you're trying to achieve here. You say you're hunting a bug... what is it? It looks like some of your tests for the rule are failing. Since our CI doesn't have a problem with it, and it's also green on my machine, maybe that's a problem on your machine. 

Please open a ticket to describe your issue in detail before reopening a PR.

**Comment by punkratz312** [comment]
the issue might be my java version 23, thanks for the checkup

**Comment by punkratz312** [comment]
image

Is the warnings "Wrong closing tag name"? maybe an issue?

https://github.com/pmd/pmd/pull/5272

@oowekyala 

image

Multiple root tags

image

**Comment by oowekyala** [comment]
Maybe try a clean checkout from master? This line is different on master, and indeed this closing tag in the middle of the tag is breaking the xml structure. https://github.com/pmd/pmd/blob/00bf6fe2f7e67e75cd4db863378a50e0533952b0/pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UnusedPrivateMethod.xml#L588

**Pull request closed without merging**
