### PR TITLE
[apex] Add Braces Rule Set

### PR DESCRIPTION
**Pull request by up2go-rsoesemann**
Before submitting a PR, please check that:
 - [x] The PR is submitted against `master`. The PMD team will merge back to support branches as needed.
 - [x] `mvn test` passes.
 - [x] `mvn checkstyle:check` passes. [Check this for more info](https://github.com/pmd/pmd/blob/master/CONTRIBUTING.md#code-style)

**PR Description:**

Implements [apex] Add Java Braces rules #272

### CODE REVIEW

**Comment by up2go-rsoesemann** [comment]
@jsotuyod I just realized that there was 1 Error in the Apex module. Can't make any sense out of this. Did I really introduce this? I need your help with this.

> Running net.sourceforge.pmd.lang.apex.ast.ASTUserTriggerTest
> Mär 02, 2017 10:41:45 AM apex.jorje.parser.impl.BaseApexLexer dedupe
> INFORMATION: Deduped array ApexLexer.DFA23_transition. Found 7927114 shorts which is 15MB not including array overhead. Removed 7204963 shorts which is 13MB not counting array overhead. Took 15ms.
> Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.89 sec - in net.sourceforge.pmd.lang.apex.ast.ASTUserTriggerTest

**Comment by jsotuyod** [comment]
@up2go-rsoesemann that's not an error, just the parser's state machine being optimized. Usually that happens when creating it from the grammar, but since we have no access to Apex Jorje, we can't tell. Don't worry about it.

**Comment by jsotuyod** [comment]
@up2go-rsoesemann on the other hand, this error was introduced by this changeset, please review it.

```
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.103 sec <<< FAILURE! - in net.sourceforge.pmd.lang.apex.DefaultRulesetTest
loadDefaultRuleset(net.sourceforge.pmd.lang.apex.DefaultRulesetTest)  Time elapsed: 0.097 sec  <<< ERROR!
java.lang.IllegalArgumentException: Cannot set non-existant property 'cc_categories' on Rule IfStmtsMustUseBraces
	at net.sourceforge.pmd.RuleSetFactory.parsePropertyNodeBR(RuleSetFactory.java:793)
	at net.sourceforge.pmd.RuleSetFactory.parsePropertiesNode(RuleSetFactory.java:710)
	at net.sourceforge.pmd.RuleSetFactory.parseRuleReferenceNode(RuleSetFactory.java:647)
	at net.sourceforge.pmd.RuleSetFactory.parseRuleNode(RuleSetFactory.java:356)
	at net.sourceforge.pmd.RuleSetFactory.parseRuleSetNode(RuleSetFactory.java:304)
	at net.sourceforge.pmd.RuleSetFactory.createRuleSet(RuleSetFactory.java:209)
	at net.sourceforge.pmd.RuleSetFactory.createRuleSet(RuleSetFactory.java:204)
	at net.sourceforge.pmd.RuleSetFactory.createRuleSet(RuleSetFactory.java:190)
	at net.sourceforge.pmd.lang.apex.DefaultRulesetTest.loadDefaultRuleset(DefaultRulesetTest.java:19)
```

**Comment by up2go-rsoesemann** [comment]
I forgot to make the `ApexXPathRule` implement `CodeClimateRule`. This interface allows a rule to define CodeClimate (**cc**) specific properties. I changed that but the error still occurs...

@adangel You might recall our discussion around renderer specific properties. Can you please have a short look at the problem?

**Comment by up2go-rsoesemann** [comment]
FYI @jsotuyod

**Comment by adangel** [comment]
Thanks for the contribution! I guess, we should think about releasing PMD 5.6.0 soon :)

**Comment by jsotuyod** [comment]
@adangel certainly. Build cache is very usable even if some edge cases remain (ie: toggling `-shortnames` invalidates the cache). Visualforce support is there. This new ruleset is there. Comment based suppression for CPD Java...

We can probably check with @sgorbaty his plans for new rules for VF to make sure we don't leave out any by a week or two; and on our end, try to get #241, #282 and [#1513](https://sourceforge.net/p/pmd/bugs/1513/) resolved. Also, I would probably add to that list renaming `java-unusedcode/UnusedModifier` to `java-unnecessary/UnnecessaryModifier`. The other open issues can probably wait.

**Pull request merged**
