### PR TITLE
[java] Added lombok.experimental to AbstractLombokAwareRule

### LINKED ISSUE #1703: [java] UnusedPrivateField on member annotated with lombok @Delegate
**Affects PMD Version:**  6.12.0

**Rule:** UnusedPrivateField

**Description:**
Lombok `@Delegate` on a member, means that lombok will generate methods into the class which mirror the method signatures of that member variable, and the bodies of the methods are just a simple delegation to the member. Obviously it makes use of the member variable; so it should not trigger PMD's `UnusedPrivateField` rule, but it does.

https://projectlombok.org/features/Delegate.html

**Code Sample demonstrating the issue:**

```
public class Foo {
    @Delegate private Bar bar;
}
```

**Running PMD through:** *Maven* -- but with dependency override to PMD version 6.12.0.

P.S. I think there could be a workaround, using `violationSuppressXPath` to suppress the `UnusedPrivateField` on members with the `Delegate` annotation. But I haven't yet figured out the XPath to match it. If an XPath wizard wants to share the right incantation it would be much appreciated!

### PR DESCRIPTION
**Pull request by jakivey32**
Before submitting a PR, please check that:
 - [x] The PR is submitted against `master`. The PMD team will merge back to support branches as needed.
 - [x] `./mvnw clean verify` passes. This will [build](https://github.com/pmd/pmd/blob/master/BUILDING.md) and test PMD, execute PMD and checkstyle rules. [Check this for more info](https://github.com/pmd/pmd/blob/master/CONTRIBUTING.md#code-style)

**PR Description:**

Fixes #1703

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">This changeset introduces 0 new violations, 0 new errors and 0 new configuration errors,<br />
removes 0 violations, 0 errors and 0 configuration errors.<br />
<a href="https://chunk.io/pmd/fcea6173f52b4b3dad861fcf18ae2d1e/diff/index.html">Full report</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by jsotuyod** [comment]
@jakivey32 Thanks for the PR!

However, as it stands, this change would not work. The set should contain the fully quallified names of annotations to be ignored, and not simply a package name.

Also, the PR should be accompanied by proper test cases for all affected rules for completeness. Such tests would also show problems such as the one indicated before.

Please, let us know if you are unsure as to how to add such test cases.

**Comment by jakivey32** [comment]
@jsotuyod Ah, I see. Is the only annotation that needs to be ignored the @Delegate annotation?

I am unsure how to add these test cases, but I'd love to learn how!

**Comment by jsotuyod** [comment]
I'm unaware of which other experimental lombok annotations may be of interest, we'd have to check their docs… but as far as #1703 is concerned, `@Delegate` alone should suffice.

This change would affect 4 rules:
* `BeanMembersShouldSerialize`
* `ImmutableField`
* `SingularField`
* `UnusedPrivateField`

Given the autogenerated delegate methods, ignoring `@Delegate` would produce false positives in `UnusedPrivateField` and `SingularField`, however, I don't think the annotation should invalidate a report of `BeanMembersShouldSerialize` (the getter for the object itself is needed, even with delegates), nor to `ImmutableField` (the way the field is initialized is irrespective of delegate methods).

So, I'd not add this ignored rule to `AbstractLombokAwareRule`  directly, but to the specific rules: `UnusedPrivateField` and `SingularField`.

`UnusedPrivateField` already adds some annotations that only apply to that rule:

https://github.com/pmd/pmd/blob/64e66b9d30c3f090371270d1ad4e0f413c1be2d1/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/UnusedPrivateFieldRule.java#L33-L40

You would have to add the `lombok.experimental.Delegate` annotation there. Then replicate this `defaultSuppressionAnnotations` override in `SingularField` to add the annotation there as well.

Once that's done, you should add proper test cases using `@Delegate` for both rules. Doing so is quite easy. Each rule has an xml file containing code snippet as well as the expected outcome. For instance, the file `UnusedPrivateField.xml` contains already snippets for other lombok annotations:

https://github.com/pmd/pmd/blob/64e66b9d30c3f090371270d1ad4e0f413c1be2d1/pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UnusedPrivateField.xml#L532-L541

You would have to add a new `<test-code>` node, using `@Delegate` and making sure 0 violations are expected. Then doing the same with [`SingularField`](https://github.com/pmd/pmd/blob/master/pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/SingularField.xml).

To run these tests from an IDE, you can execute as JUnit tests the corresponding [`UnusedPrivateFieldTest`](https://github.com/pmd/pmd/blob/master/pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/bestpractices/UnusedPrivateFieldTest.java) and [`SingularFieldTest`](https://github.com/pmd/pmd/blob/master/pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/design/SingularFieldTest.java), which will read these xml files and setup the test cases automatically.

**Comment by jakivey32** [comment]
@jsotuyod  Okay, I've added `lombok.experimental.Delegate` to both Rules. However, after I added these test cases to both xml files:

TestCaseXML


I was unable to figure out how to actually run the JUnit tests (on VSCode). I can see the tests are there, but when I try to run them, nothing happens.

**Comment by jsotuyod** [comment]
I'm unsure of how to do this on VSCode in particular, but those test classes I mentioned ([`UnusedPrivateFieldTest`](https://github.com/pmd/pmd/blob/master/pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/bestpractices/UnusedPrivateFieldTest.java) and [`SingularFieldTest`](https://github.com/pmd/pmd/blob/master/pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/design/SingularFieldTest.java)) extend a base `PmdRuleTst`, which configures the JUnit runner to use…

In Eclipse I can simply ask the IDE to run the class as a JUnit test…

image

**Comment by adangel** [comment]
@jakivey32 If you build it outside of a IDE as described in [BUILDING.md](https://github.com/pmd/pmd/blob/master/BUILDING.md) (via `./mvnw clean verify`) all the unit tests are run as well.

**Pull request merged**
