### PR TITLE
[apex] New ruleset for Apex security

### PR DESCRIPTION
**Pull request by sgorbaty**
Hi PMD!

I added a set of new rules that allows detection of the following potential security issues:
- Reflected XSS via URL parameter
- Reflected XSS via disabled escaping
- Sharing violation
- CSRF when DML happens in a controller constructor / init method
- Open Redirect detection
- SOQL injection from merging unescaped variables
- Insecure HTTP Endpoint 
- Unsafe crypto practices

All new code is accompanied with unit tests. 

More to come!

Cheers,
Sergey

### CODE REVIEW

**Comment by jsotuyod** [comment]
First of all, let me say this is awesome! We really appreciate it.

I'll try to review it over the weekend, but may take me some time (2k LoCs is quite a bit).

In the future, feel free to send independent PRs per-rule as you get them ready. No need to submit a complete ruleset.

**Comment by sgorbaty** [comment]
Thanks @jsotuyod! I look forward to your feedback!

**Comment by up2go-rsoesemann** [comment]
@jsotuyod I created the inital Apex support with @adangel a year ago and I can just say this is well written and tested and already rolled out to production (using a SNAPSHOT build of PMD) in my Code Climate engine ApexMetrics (https://github.com/Up2Go/codeclimate-apexmetrics)

Back then I promised Andreas to keep an eye on every Apex PR and this one is done very well ;-)

Can you say when this might be release with PMD including the Eclipse plugin? I am asking because Salesforce/Apex developers often use and Eclipse based IDE and love the plugin.

**Comment by corycowgill** [comment]
This will be incredibly useful to engineers on the platform! As of right now Checkmarx has a (very expensive) monopoly on the security tool that performs the Apex static code analysis. I didn't have much interest in the PMD tool until I saw this commit!

**Comment by jsotuyod** [comment]
This has been manually merged into both `master` (PMD 5.6.0) and `pmd/5.5.x` (PMD 5.5.3).

Sorry it took me longer than expected. Thanks again for the amazing work.

We don't have a specific release date yet, we are currently discussing setting up a more predictable release cycle.

**Pull request closed without merging**
