### PR TITLE
[java] Update comment rules for java

### PR DESCRIPTION
**Pull request by oowekyala**
## Describe the PR

* Remove the deprecated CommentUtil, AbstractCommentRule
* There's a new "comment assignment pass", which assigns javadoc comments to the relevant nodes using a data key. The implementation is much more straightforward than before, and is done exactly once, instead of once per AbstractCommentRule (and so, zero times if a ruleset has no AbstractCommentRule). But it fails to detect the comment when there are annotations or modifiers before the comment, which is a rare corner case IMO. We can improve that later
* The interface JavadocCommentOwner can be used to access them.
* I wonder, whether FormalComment should be a regular java node, manually inserted in the tree by this pass. We can question that later.
* This adds a compareLocation method to the Node interface, which this PR was using before I simplified the implementation. So it's unused, but I think this is relevant as many usages of the methods getBeginLine/getEndLine are actually just used to sort some nodes. This may be implemented more efficiently by nodes (eg, jjtree nodes can compare their offsets in the file)
* Reactivate tests of most rules of the documentation category:
  * UncommentedEmptyMethodBody
  * CommentRequired
  * CommentSize
  * CommentContent

## Related issues

- Several items of #2701
  

## Ready?

- [x] Added unit tests for fixed bug/feature
- [x] Passing all unit tests
- [x] Complete build `./mvnw clean verify` passes (checked automatically by travis)
- [x] Added (in-code) documentation (if needed)

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">No java rules are changed!</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by oowekyala** [comment]
@adangel Apparently danger fails on the latest commits because of a missing master baseline zip:

https://travis-ci.org/github/pmd/pmd/jobs/736633219#L7492-L7502

**Comment by oowekyala** [comment]
Actually the diff is weird because the file names are truncated in the PR diff?

Eg this section has just the file name and not its full path

https://chunk.io/pmd/038abe34ece14f87822db43bb27fd398/diff2/checkstyle/index.html#A14249

Compare to the baseline for the same file

https://chunk.io/pmd/038abe34ece14f87822db43bb27fd398/diff2/checkstyle/index.html#A1

**Comment by adangel** [comment]
> @adangel Apparently danger fails on the latest commits because of a missing master baseline zip:
> 
> https://travis-ci.org/github/pmd/pmd/jobs/736633219#L7492-L7502

I guess, this was a temporary hickup downloading the baseline from sourceforge. The `wget` command didn't fail (if it did, we would have seen a error message there already), it downloaded something. But maybe the file was not complete or corrupt (due to mirroring on sourceforge hosts?).

I see, that the regression tester runs again...

**Comment by adangel** [comment]
> Actually the diff is weird because the file names are truncated in the PR diff?

Only the first part of the path should be truncated (e.g. the working directory), so that it doesn't matter, where exactly you run the regression tester.

The baseline looks Ok: checkstyle/src/it/java/com/google/checkstyle/test/base/AbstractIndentationTestSupport.java
But pmd7 doesn't: AbstractIndentationTestSupport.java

I feel like I remember having fixed this already.... hm.... I think, this was the path of processing errors, which was wrong (269f5bd79b8796f11df87cb94551d8cb353bc393). Maybe that's something new? I wonder, from where it came....

**Comment by adangel** [comment]
@oowekyala The new regression report is available. We have many removed violations compared to master:

> Compared to master:
This changeset introduces 4862 new violations, 9 new errors and 0 new configuration errors,
removes 24436 violations, 16 errors and 2 configuration errors.
https://chunk.io/pmd/e39b418f45cf42b683c24592dd69dc28/diff2/index.html

One example is this:
In [OuterTypeFilenameTest.java](https://github.com/checkstyle/checkstyle/blob/checkstyle-8.10/src/it/java/com/google/checkstyle/test/chapter2filebasic/rule21filename/OuterTypeFilenameTest.java) we should report the missing comment for the 3 test methods, but we apparently don't. The first method is annotated with `@Override`, so we don't require comment for "getPackageLocation()", which is Ok. Maybe that leads to skipping the check for the other methods?

I'll look into this....

**Comment by adangel** [comment]
Ok, so this is what happens:

We see the annotation `@Test`, figure out, it is `@org.junit.Test`, but junit is not on the auxclasspath. So, this classref is unresolved. When comparing to `@java.lang.Override`, we consider it by default a subtype:

https://github.com/pmd/pmd/blob/9aa9e8cd975f58d23e8330057700b0edaa8c1ce7/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/TypeOps.java#L390-L394

This results then in a false negative. It seems, that we have on master a different default behavior for incomplete auxclasspaths. Returning here simply `Convertibility.NEVER` would solve this special case, but maybe it's not too bad, and we should leave it. It would give us an argument: "you need to call PMD correctly to get accurate results".

I'll continue now on pmd/pmd-regression-tester#48, so that we call PMD correctly during regression testing.

**Comment by adangel** [comment]
Updated numbers for comparing this PR against master for checkstyle is available: https://chunk.pmd-code.org/pmd/f465ddd3-2188-4976-9f61-f16591faea2c/diff/index.html
The numbers look much better now....

* 1076 new violations, 420 removed violations
* 7 new errors, 21 removed errors

**Comment by adangel** [comment]
Here's the preview for spring-framework comparing this PR against master: https://chunk.pmd-code.org/pmd/37f43255-f654-4295-a72b-76e83ef2a06e/diff/index.html

The numbers look much better here as well:

* 4296 new violations, 3458 removed violations
* 3 new errors, 22 removed errors

**Comment by oowekyala** [comment]
> This results then in a false negative. It seems, that we have on master a different default behavior for incomplete auxclasspaths. Returning here simply Convertibility.NEVER would solve this special case, but maybe it's not too bad, and we should leave it. It would give us an argument: "you need to call PMD correctly to get accurate results".

Thanks for diagnosing this. I think isConvertible needs to stay that way for type inference to work properly (ie, be liberal when inferring unresolved types). But I changed TypeTestUtil to use a better strategy (ie, always return false if we're not sure, which is the behavior of the rest of TypeTestUtil)

**Comment by oowekyala** [comment]
Quick review of the regression report:

This fixes many FNs of CommentRequired
- [Annotation methods](https://chunk.io/pmd/c344de649271438095f0579aa8cae4d1/diff2/checkstyle/index.html#A4)
- [Misplaced comment on field](https://chunk.io/pmd/c344de649271438095f0579aa8cae4d1/diff2/checkstyle/index.html#A1), previously the comment that is on the previous enum constant was attributed to this field. Same [here](https://chunk.io/pmd/c344de649271438095f0579aa8cae4d1/diff2/checkstyle/index.html#A348)
- [Mispacd comment on classes](https://chunk.io/pmd/c344de649271438095f0579aa8cae4d1/diff2/checkstyle/index.html#A287) 
- [Misplaced comment on import declaration](https://chunk.io/pmd/c344de649271438095f0579aa8cae4d1/diff2/checkstyle/index.html#A14), though I'm not so sure about this one

Line numbers changed a bit, eg [this violation](https://github.com/checkstyle/checkstyle/blob/checkstyle-8.10/src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputMethodParamPad.java#L25) is reported on the method identifier and not the return type, this is expected.

A few files are shown as if all violations are removed: those are the files excluded by the exclude pattern, refs 331f8f9d117e87da378493840b397265566c39db

But notably, CommentRequired still does not report on annotation type declarations, and record declarations.

I think globally this is very positive, this new comment assignment method works better than the old.

**Pull request merged**
