### PR TITLE
[core] Add the 'empty' Renderer which writes nothing.

### PR DESCRIPTION
**Pull request by ryan-gustafson**
**PR Description:**
Add the 'empty' Renderer which writes nothing.

### CODE REVIEW

**Comment by jsotuyod** [comment]
I may have missed it, but what is your intended use for this renderer? Is it really to be a publicly available renderer, or just an internal one we use for a specific testing / ci scenario?

**Comment by ryan-gustafson** [comment]
I've been improving the benchmarking support (PR soon), and needed to focus on the stdout/stderr output in an IDE console without the noise of the report, and an 'empty' report was what I was looking for.  I didn't really want to send it to a file that I later had to delete.

I hadn't considered making it non-public, there's not currently support for that.  Suppressing advertising in the -help is possible I suppose.

As far as whether we need it, probably not.  But it is simple and flexible for when the desire arises.  I've always enjoyed using tools with options to disable features for corner case uses or even to aid in problem diagnostics (e.g. bisection: hmm looks like it's not the report rendering that's causing the OOM).

**Comment by jsotuyod** [comment]
Actually, there's somewhat of support. If you don't include the renderer in the factory, and simply refer to the renderer by fully qualified class name, it's usable, but never shown in help / easily accessible by unintended users

**Comment by ryan-gustafson** [comment]
Should I put the class in the default package and rename it to `empty` ? ;)

Point taken on the FQCN support, I didn't look that closely.  However my goal here was ease of use for a specific kind of use case.  `-f empty` being the ultimate in ease/speed.   Just sending to a random file and deleting afterward being second, although clearly sloppy.  Using an FQCN decidedly harder than either of those, and I doubt I'll ever remember an FQCN.

I'm out of compelling arguments.

**Comment by adangel** [comment]
I assume, this empty renderer is less useful for end-users (since they want to see the violations...), but more useful for developers/tool integrators.
I'd be open to add it, even with the possibility to have the `-f empty` shortcut. But somehow, we need to mark this renderer then as "developer aid" (e.g. suppressing in the help output). We could have an extra "developers toolkit" category in the documentation, that explains such more advanced possibilities.

**Comment by adangel** [comment]
I've decided to merge it into 5.7.0.
As the exit code is still valid (e.g. != 0 if there are violations), it might be used as a simple quality gate check when one just wants to verify, there are no rule violations.
And of course, it'll be helpful for developers.

**Pull request merged**
