### PR TITLE
[doc] Add qa-eclipse as new tool

### PR DESCRIPTION
**Pull request by akshatbahety**
Added a qa-Eclipse plugin to the table.

**PR Description:**
In reference to the issues #909 added the plugin to the list of tools available.

### CODE REVIEW

**Comment by akshatbahety** [comment]
@adangel I would keep those points in mind and do the changes accordingly.

Thanks for all the help.

**Comment by adangel** [comment]
@akshatbahety Let me know, if you need help.

**Comment by akshatbahety** [comment]
@adangel I made the changes but the build is failing i don't understand why.

**Comment by oowekyala** [comment]
@akshatbahety The error is not on your part, don't worry

Some tests use random numbers, and it seems the acceptable range of values has an off-by-one error. This build failure had a 1/600 chance to happen... maybe play the lottery tomorrow ;)

Anyway I'll get this fixed asap, sorry about it

**Comment by adangel** [comment]
Merged! Congrats to your 2nd contribution!

**Pull request merged**
