### PR TITLE
Java 11 and OpenJFX

### PR DESCRIPTION
**Pull request by adangel**
This uses the available openjfx dependencies instead of relying that jfx is available. With that change, PMD builds under Linux with plain OpenJDK 11.
Since the openjfx jars are included as dependencies, we don't use the module system of java9 anymore when running the Designer, so we don't need the extra vm flags. The openjfx jars are just available on the classpath.

The resulting pmd-bin-...zip is also bigger, since the openjfx jars are included now.

However, the resulting pmd-bin-....zip would only be runnable right now on Linux, since the dependencies automatically include the platform dependent part.
This happens in the parent pom of openjfx: https://search.maven.org/#artifactdetails%7Corg.openjfx%7Cjavafx%7C11-ea%2B19%7Cpom

```
        <profile>
            <id>linux</id>
            <activation>
                <os>
                    <name>linux</name>
                </os>
            </activation>
            <properties>
                <javafx.platform>linux</javafx.platform>
            </properties>
        </profile>
```

So, we probably need to add all dependencies in pmd-dist explicitly and select the correct platform in our run.sh script...

### CODE REVIEW

**Comment by oowekyala** [comment]
An alternative to bloating our distribution with all platform-specific dependencies would be to wrap the designer with a script identifying the JRE, and downloading the correct OpenJFX on the first run if needed. I'm not sure how the pom would look like then, to make it build...

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">No java rules are changed!</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by adangel** [comment]
I've decided to add the openjfx dependencies as provided, so that they are available during runtime, but won't be included in our binary distribution.

There are two points, we need to solve: building PMD and running PMD/Designer.

## Building
Building PMD looks very straightforward - I'm currently testing various combinations:

| OS    | Java Version | Result |
| --- | --- | --- |
| Linux | openjdk 11-ea 25 |  :heavy_check_mark: |
| Linux | openjdk 10       |  :heavy_check_mark: |
| Linux | openjdk  9       | :x: openjfx is compiled with java10 - unit test execution fails |
| Linux | oracle jdk 11-ea 25 |  :heavy_check_mark: |
| Linux | oracle jdk 10       |  :heavy_check_mark: |
| Linux | oracle jdk  9       | :x: openjfx is compiled with java10 - unit test execution fails |
| Windows | openjdk 11-ea 25 | :heavy_check_mark: |
| Windows | openjdk 10       | :white_large_square: |
| ~~Windows~~ | ~~openjdk  9~~       |  |
| Windows | oracle jdk 11-ea 25 | :white_large_square: |
| Windows | oracle jdk 10       | :white_large_square: |
| ~~Windows~~ | ~~oracle jdk  9~~       |  |
| MacOSX | openjdk 11-ea 25 | :white_large_square: |
| MacOSX | openjdk 10       | :white_large_square: |
| ~~MacOSX~~ | ~~openjdk  9~~       |  |
| MacOSX | oracle jdk 11-ea 25 | :white_large_square: |
| MacOSX | oracle jdk 10       | :white_large_square: |
| ~~MacOSX~~ | ~~oracle jdk  9~~       |  |

Summary so far: We need to raise our requirement for building to at least java10. I wouldn't be surprised, that we need to raise it to java11 once both openjfx11 and java11 are released.

Note: we use openjfx11 for building - which might be incompatible with javafx8 included in the older java builds...

## Running PMD

It took me a while to get openjfx working on Windows, but now I know, that the `bin`-subdirectory of the openjfx-sdk needs to be on the `PATH` under Windows, so that the necessary DLLs are found... strangely, I can't reproduce it anymore (I installed since then oracle jdk9 - maybe this put something into C:\Windows\System32\??)

I'll probably restore the `run.sh` script in order to be able to react differently on different java versions.

> downloading the correct OpenJFX on the first run

That's an interesting idea. However, I won't do this in this PR. My plan is, to describe/document, what and how one must install (java, javafx). We could not only download javafx, but also java... But at least for Windows, I would prefer then using something like http://nsis.sourceforge.net/ to have a real installer. Alternatively, we could package a pmd+java distribution. In the far future, if we use java modules for PMD, we could even use jlink to create an own runtime image...

So far, my idea is, to require a `JAVAFX_HOME` environment variable (in addition to `JAVA_HOME`). This needs to be setup once, when installing java/javafx.

There are also a couple of combinations possible, for running the Designer:

| OS | Java Version | Result | Remarks |
| --- | --- | ---| --- |
| Linux | oracle java 8 | :white_large_square: | JavaFX is included, no modules |
| Linux | oracle java 9+10 | :white_large_square: | JavaFX is included as a module |
| Linux | oracle java 11, openjdk 9+ | :white_large_square: | JavaFX is *not* included |
| Windows | oracle java 8 | :white_large_square: | JavaFX is included, no modules |
| Windows | oracle java 9+10 | :white_large_square: | JavaFX is included as a module |
| Windows | oracle java 11, openjdk 9+ | :white_large_square: | JavaFX is *not* included |
| MacOSX | oracle java 8 | :white_large_square: | JavaFX is included, no modules |
| MacOSX | oracle java 9+10 | :white_large_square: | JavaFX is included as a module |
| MacOSX | oracle java 11, openjdk 9+ | :white_large_square: | JavaFX is *not* included |


Java and JavaFX can be downloaded from:
* Oracle Java: http://www.oracle.com/technetwork/java/javase/downloads/index.html
* OpenJDK: http://jdk.java.net/
* OpenJFX: http://jdk.java.net/ (currently only preview, I expect that it will be available after release on the same page)

**Comment by adangel** [comment]
I've now updated the build and the run-scripts. So far, it seems to be working...

@jsotuyod You are using MacOSX, correct? Could you test, whether the Designer starts for you? Thanks!

For the openjdk builds and oracle java 11, you need additionally the openjfx sdk from http://jdk.java.net/openjfx/ . Download the SDK zip (*not* the JMODs), extract it somewhere and set a environment variable JAVAFX_HOME, e.g.

    export JAVAFX_HOME=$HOME/javafx-sdk-11

Then it should just work, when you execute `run.sh designer`.

Btw - I've updated travis to build PMD also on macosx...

I guess, we need to improve the documentation...

**Comment by jsotuyod** [comment]
@adangel sorry for the huge delay. I'm upgrading my machine to Java 10, and I'll do a clean build and let you know.

**Comment by jsotuyod** [comment]
I confirm using Java 10 on MacOS X just works. This looks good to merge IMO.

I can try an early access Java 11 too if needed. @adangel anything else before merging?

**Pull request merged**
