### PR TITLE
[ci] Regression Tester Test - do not merge

### PR DESCRIPTION
**Pull request by adangel**
## Describe the PR

* Follow up on #3336
* Make the rule AbstractClassWithoutAbstractMethod fail randomly
* The first run of pmd regression tester should show, that many violations have been removed when compared to master.

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          2 Messages
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">Compared to pmd/7.0.x:<br />
This changeset changes 0 violations,<br />
introduces 0 new violations, 0 new errors and 0 new configuration errors,<br />
removes 141 violations, 0 errors and 0 configuration errors.<br />
<a href="https://chunk.io/pmd/84472043b7524aabade1d81ed91915fa/diff1/index.html">Full report</a></td>
    </tr>
    <tr>
      <td>:book:</td>
      <td data-sticky="true">Compared to master:<br />
This changeset changes 0 violations,<br />
introduces 1 new violations, 1 new errors and 0 new configuration errors,<br />
removes 304620 violations, 8 errors and 2 configuration errors.<br />
<a href="https://chunk.io/pmd/84472043b7524aabade1d81ed91915fa/diff2/index.html">Full report</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by adangel** [comment]
I think, that works quite well: Instead of removing 304620 violations, now only 147 violations are removed. The report is only about the changed rule.

**Comment by adangel** [comment]
Next steps are probably:
* merge all the pmd-regression-tester PRs and release a new version
* apply the following commits from here to master
    * 709e5e8 - display size of created regression tester report
    * 85864e5 - compress the report before upload
    * part of 4701647 - the `-B` flag for building checkstyle should be used
    * and update pmd-regression-tester
    * merge master -> pmd/7.0.x
* apply the following commits from there to pmd/7.0.x
    * 38e3430 - enables `--filter-with-patch-config`
    * 4701647 - adds openjdk-11

**Comment by adangel** [comment]
All changes from the previous comment are now applied to master and pmd/7.0.x.

**Pull request closed without merging**
