### PR TITLE
Add CloneMethodReturnTypeMustMatchClassName rule

### PR DESCRIPTION
**Pull request by DTecheira**
If we have a class that implements cloneable the return type of our clone method should match with the class name instead of returning Object.

This makes sense since clone is expected to return an exact copy of the object; and since the return type is not part of the signature, it's still a valid override.

```java
public class Foo implements Cloneable {
    @Override
    public Object clone() { // Should be Foo
    }
}
```
This is not required by the contract of Object.clone (even the [Javadoc says so] (http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html#clone)), but is a sane default; and exceptions may suppress this rule were needed.

### CODE REVIEW

**Comment by jsotuyod** [comment]
To bare in mind, doing this is only valid (an recommended) in Java 5+.

**Comment by adangel** [comment]
You are right, thanks for the hint.
It is actually possible to make this rule java 5+ only: by adding the attribute `minimumLanguageVersion="1.5"` in the ruleset.

**Comment by jsotuyod** [comment]
Awesome, didn't know! Do you want @DTecheira to change it or will you do it yourself when you merge?

**Comment by adangel** [comment]
I can do it, when I merge it. However, it will take probably 2 more weeks before I find time to work on this.

**Comment by jsotuyod** [comment]
If there is anyway in which we can help just let us know! At @Monits we make heavy use of PMD, and just as we did these few rules @DTecheira submitted, we are planning on working on a crash and a couple FP on some existing rules on the next few days.

We are more than open to invest development time on other things too if that will help you / PMD. It's our way of giving back to such an amazing tool. Feel free to contact me to coordinate efforts.

**Comment by DTecheira** [comment]
Sorry for the delay, I will add this, today.

**Comment by DTecheira** [comment]
Done

**Comment by adangel** [comment]
Thanks!

**Pull request merged**
