### PR TITLE
[java] Update many Java rules

### PR DESCRIPTION
**Pull request by jsotuyod**
## Describe the PR

Updated:

* NonStaticInitializer
* MissingSerialVersionUID
* InstantiationToGetClass
* FinalizeShouldBeProtected
* FinalizeOverloaded
* FinalizeOnlyCallsSuperFinalize
* FinalizeDoesNotCallSuperFinalize

## Ready?

- [ ] Added unit tests for fixed bug/feature
- [ ] Passing all unit tests
- [ ] Complete build `./mvnw clean verify` passes (checked automatically by github actions)
- [ ] Added (in-code) documentation (if needed)

### CODE REVIEW

**Comment by pmd-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Running pmdtester failed, this message is mainly used to remind the maintainers of PMD.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by jsotuyod** [comment]
@adangel @oowekyala any idea of why the regression tester may be failing?

It reports a bunch of NPEs, but some of them even occur on rules such as `SuspiciousHashcodeMethodNameRule` which are still commented out in `.ci/files/all-java.xml`

**Comment by oowekyala** [comment]
I think if you only edit one category file, the regression tester executes the category (ignoring the `.ci/files/all-java.xml`). This is annoying and should probably be removed from the regression tester while we update rules for pmd 7.

IIRC you can workaround this by touching eg codestyle.xml and adding a newline or something harmless. But this also applies to many other open prs...

**Comment by adangel** [comment]
@jsotuyod Please merge in the latest pmd/7.0.x - this should make the regression tester run again (see #3399).

**Comment by adangel** [comment]
Or enable the following checkbox in this PR:

grafik

Then I can push to your branch...

**Comment by oowekyala** [comment]
> Or enable the following checkbox in this PR:
> 
> grafik
> 
> Then I can push to your branch...

@jsotuyod Please do this so we can help finish this pr

**Pull request merged**
