### PR TITLE
[java] Fix ClassCastException in AccessorClassGeneration

### LINKED ISSUE #352: [java] AccessorClassGeneration throws ClassCastException when seeing array construction
The rule `java/design/AccessorClassGeneration` fails with the following exception trace:
```
Caused by: java.lang.ClassCastException: net.sourceforge.pmd.lang.java.ast.ASTArrayDimsAndInits cannot be cast to net.sourceforge.pmd.lang.java.ast.ASTArguments
	at net.sourceforge.pmd.lang.java.rule.design.AccessorClassGenerationRule.visit(AccessorClassGenerationRule.java:78)
	at net.sourceforge.pmd.lang.java.ast.ASTAllocationExpression.jjtAccept(ASTAllocationExpression.java:21)
	at net.sourceforge.pmd.lang.java.rule.JavaRuleChainVisitor.visit(JavaRuleChainVisitor.java:41)
```

Using the following test case for `AccessorClassGeneration.xml`:
```
    <test-code>
        <description><![CDATA[
Array initializer is not a class body
     ]]></description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    private class Bar {
        private int size;

        private Bar() {
        }

        void bar() {
            new Bar[size];
        }
    }
}
     ]]></code>
    </test-code>
```

This is related to issue https://github.com/pmd/pmd/issues/291 and pull request https://github.com/pmd/pmd/pull/293 in some fashion.

### PR DESCRIPTION
**Pull request by jsotuyod**
- Fixes #352

### CODE REVIEW

**Comment by ryan-gustafson** [comment]
Are there process guidelines I can follow on these?  Unfortunately, I'm more use to Bitbucket than Github, and I've no clue on the PMD specific guidelines.

**Comment by jsotuyod** [comment]
@ryan-gustafson now we are only merging to master the process is:

```
$ git fetch upstream pull/<ID>/head:pr-<ID>
$ git checkout pr-<ID>
$ mvn test checkstyle:check # usually not necessary, if Travis built and passed
# If necessary edit and commit src/site/markdown/overview/changelog.md, not on this case as I already did that
$ git checkout master
$ git merge --no-ff pr-<ID>
$ git push upstream # optionally push to any extra fork / remote
```

This is all assuming `upstream` is the name of the remote pointing to this repo (if you directly forked this repo that would be origin), and replacing `<ID>` with whatever the PR is is (in this case 353).

Notice that if you don't need to edit the changelog, nor run mvn test / checkstyle (Travis passed), nor merge to any other branches; as is in this very specific PR, you *could* just merge the PR through the Github's web UI with the "Merge pull request" green button below; but that of course is not the most common scenario.

**Comment by ryan-gustafson** [comment]
There used to be notes for making releases, doing site maintenance, etc.  Would it perhaps be better to have handling of PRs as part of say `pmd-dist/README.md`?  If only to semi-formalize the process, and facilitate discussion?  I'm personally not big on remembering random task lists very well.  I'll have to find some magical place to stuff the commands you list above...

**Comment by jsotuyod** [comment]
@ryan-gustafson release process is still [on the site](https://pmd.github.io/pmd-5.5.5/customizing/pmd-release-process.html) and has even been updated to the latest changes on Travis automation / Github milestone handling.

Writing something for PR merging could be done, although I don't particularly need it (after merging a couple dozen PRs it's pretty much automatic), but I did check notes passed down by @adangel via email on the first few, so I understand your point.

We are however considering some changes to how we handle branches and releases on the mailing list, possibly moving to a rolling release on master (except hot fixes), which would greatly simplify the process.

**Pull request merged**
